import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url),E=require('../../economy.js');const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=process.env.COLD_OUTPUT||'/tmp/story-cold-focus',base=process.env.COLD_BASE||'http://127.0.0.1:8768',formal=process.env.COLD_FORMAL==='1';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),rows=[];
const frames=p=>p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
async function close(p,how){if(how==='Escape')await p.keyboard.press('Escape');else await p.locator(how==='return'?'#mOk':'#mX').click();await p.waitForFunction(()=>!document.querySelector('#storyReplay'));}
try{
for(const entry of (formal?['/','/pet/game/']:['/preview/','/preview/pet/game/']))for(const width of [320,393])for(const how of ['Escape','return','X']){
 const c=await browser.newContext({viewport:{width,height:width===320?568:852},hasTouch:true,isMobile:true}),p=await c.newPage(),errors=[],requested=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().includes('/storycards/'))requested.push(r.url())});
 const old=E.newState(Date.now());old.coins=12345;old.taps=1;old.muted=true;old.gacha.owned=['c_apron','k_1','k_8'];
 await c.addInitScript(({old,formal})=>{const key=formal?'tangzhe-save':'tangzhe-preview-save';localStorage.setItem(key,JSON.stringify(old));localStorage.setItem(key+'-bak',JSON.stringify(old));localStorage.setItem(formal?'tangzhe-preview-save':'tangzhe-save','UNTOUCHED');let t;Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}})},{old,formal});
 let catRelease,redRelease,catSeen=false,redSeen=false,catRequest,redRequest;const catRequested=new Promise(r=>catRequest=r),redRequested=new Promise(r=>redRequest=r);const catGate=new Promise(r=>catRelease=r),redGate=new Promise(r=>redRelease=r);
 await p.route('**/pet/art/cat/manifest.json*',async route=>{catSeen=true;catRequest();await catGate;await route.continue()});await p.route('**/pet/art/red_panda/manifest.json*',async route=>{redSeen=true;redRequest();await redGate;await route.continue()});
 await p.goto(base+entry,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tzz&&document.body.dataset.petReady==='1');await catRequested;assert(catSeen);await p.evaluate(()=>{__tzz.setTab('col');__tzz.renderTab()});
 const card=()=>p.locator('.story-open[data-arg="k_8"]');await card().evaluate(el=>{el.scrollIntoView({block:'center',behavior:'instant'});el.focus({preventScroll:true});window.coldOpener=el});await card().locator('[data-story-state="ready"]').waitFor();
 const original=await p.evaluate(()=>({top:document.querySelector('#panel').scrollTop,x:scrollX,y:scrollY,main:localStorage.getItem(__tzz.SAVE_KEY),bak:localStorage.getItem(__tzz.BAK_KEY)}));assert(original.top>0);await p.keyboard.press('Enter');await p.locator('#storyReplay').waitFor();
 catRelease();await p.waitForFunction(()=>!!PetGame.assetOf('cat'));await frames(p);
 assert(await p.evaluate(()=>coldOpener.isConnected),'pet resource arrival replaced unchanged collection opener');assert.equal(await p.locator('#panel').evaluate(el=>el.scrollTop),original.top);assert.equal(await p.evaluate(()=>document.activeElement.id),'mOk');
 await close(p,how);assert(await card().evaluate(el=>el===document.activeElement));assert.equal(await p.locator('#panel').evaluate(el=>el.scrollTop),original.top);await redRequested;assert(redSeen);
 redRelease();await p.waitForFunction(()=>!!PetGame.assetOf('red_panda'));await frames(p);assert(await card().evaluate(el=>el===document.activeElement));assert(await p.evaluate(()=>coldOpener.isConnected));assert.equal(await p.locator('#panel').evaluate(el=>el.scrollTop),original.top);
 // A real content change must replace nodes but preserve focused story and scroll.
 await p.evaluate(()=>{__tzz.state.cur=1;__tzz.renderTab()});assert(!await p.evaluate(()=>coldOpener.isConnected));assert(await card().evaluate(el=>el===document.activeElement));assert.equal(await p.locator('#panel').evaluate(el=>el.scrollTop),original.top);
 await p.keyboard.press('Enter');await p.evaluate(()=>{__tzz.state.cur=0;__tzz.renderTab()});await close(p,how);assert(await card().evaluate(el=>el===document.activeElement));assert.equal(await p.locator('#panel').evaluate(el=>el.scrollTop),original.top);
 for(const method of ['return','Escape','X']){await p.keyboard.press('Enter');await p.locator('#storyReplay').waitFor();await close(p,method);await frames(p);assert(await card().evaluate(el=>el===document.activeElement));assert.equal(await p.locator('#panel').evaluate(el=>el.scrollTop),original.top);}
 assert.equal(await p.evaluate(()=>localStorage.getItem(__tzz.SAVE_KEY)),original.main);assert.equal(await p.evaluate(()=>localStorage.getItem(__tzz.BAK_KEY)),original.bak);assert.equal(await p.evaluate(()=>__tzz.state.coins),12345);assert(requested.every(u=>/story_k_(1|8)\.webp/.test(u)));assert.deepEqual(errors,[]);await p.screenshot({path:out+'/'+(entry.includes('/game/')?'standalone':'main')+'-'+width+'-'+how+'.png'});rows.push({entry,width,close:how,status:'pass',delayedCatDuringDialog:true,delayedRedPandaAfterClose:true,unchangedNodesRetained:true,changedNodesRestoreFocus:true,scrollUnchanged:true,repeatedOpenClose:true,noSaveChanges:true});await c.close();fs.writeFileSync(out+'/results.json',JSON.stringify(rows,null,2));
}
console.log(rows.length+' cold-resource focus/scroll cases passed');
}finally{await browser.close();}
