// Isolated saves, real supplied art, and actual legacy root-v14 state fixtures.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),legacyE=require('../../economy.js');
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=new URL(process.env.STORY_TEST_OUTPUT||'./story-output/',import.meta.url);fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),results=[];
async function setup(entry,fixture){
 const c=await b.newContext({viewport:{width:fixture.width,height:fixture.height||852},isMobile:true,hasTouch:true,deviceScaleFactor:1});await c.addInitScript(()=>{let t;Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}})});const p=await c.newPage(),errors=[],requested=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{const m=r.url().match(/storycards\/story_(k_\d+)\.webp/);if(m)requested.push(m[1])});
 const boot=async()=>{await p.waitForFunction(()=>window.__tzz);await p.evaluate(async()=>{for(let i=0;i<4;i++){if(__tzz.modalOpen())__tzz.closeModal();await new Promise(r=>setTimeout(r,60))}__tzz.setTab('col');__tzz.renderTab()})};
 await p.goto((process.env.STORY_TEST_BASE||'http://127.0.0.1:8765')+entry);await boot();const old=legacyE.newState(Date.now());old.coins=12345;old.muted=true;old.gacha.owned=['c_apron',...fixture.owned];old.gacha.last=null;
 await p.evaluate(s=>{localStorage.setItem(__tzz.SAVE_KEY,JSON.stringify(s));localStorage.setItem(__tzz.BAK_KEY,JSON.stringify(s));localStorage.setItem('tangzhe-save','FORMAL-SENTINEL')},old);await p.reload();await boot();
 const snapshot=()=>p.evaluate(()=>JSON.stringify({state:__tzz.state,main:localStorage.getItem(__tzz.SAVE_KEY),bak:localStorage.getItem(__tzz.BAK_KEY),formal:localStorage.getItem('tangzhe-save')}));return {c,p,errors,requested,boot,snapshot};
}
for(const entry of ['/preview/','/preview/pet/game/'])for(const fixture of [{width:320,height:568,owned:['k_1','k_4']},{width:375,owned:[]},{width:393,owned:Array.from({length:8},(_,i)=>'k_'+(i+1))}]){
 const {c,p,errors,requested,boot,snapshot}=await setup(entry,fixture),before=await snapshot(),tag=(entry.includes('/game/')?'standalone':'main')+'-'+fixture.width;
 assert.equal(await p.locator('.story-open').count(),fixture.owned.length);assert.equal(await p.locator('.story.no').count(),8-fixture.owned.length);assert.equal(await p.locator('.story.no [data-act],.story.no img').count(),0);
 for(const id of ['k_missing','c_apron',...Array.from({length:8},(_,i)=>'k_'+(i+1)).filter(id=>!fixture.owned.includes(id))]){await p.evaluate(id=>__tzz.act('card',id),id);assert.equal(await p.locator('#storyReplay').count(),0)}
 for(const [i,id] of fixture.owned.entries()){
  const card=p.locator(`.story-open[data-arg="${id}"]`);await card.scrollIntoViewIfNeeded();await card.locator('.story-art[data-story-state="ready"]').waitFor();const thumb=await card.locator('img').evaluate(im=>({url:im.src,w:im.naturalWidth,h:im.naturalHeight}));assert.equal(thumb.w,1024);assert.equal(thumb.h,768);await card.focus();await p.keyboard.press('Enter');const expected=legacyE.ITEM_BY_ID[id];assert.equal(await p.locator('#storyReplayTitle').innerText(),expected.name);assert.equal(await p.locator('#storyReplay .mnote').innerText(),expected.text);await p.locator('#storyReplay [data-story-state="ready"]').waitFor();const big=await p.locator('#storyReplay img').evaluate(im=>({url:im.src,w:im.naturalWidth,h:im.naturalHeight,fit:getComputedStyle(im).objectFit}));assert.deepEqual(big,{...thumb,fit:'contain'});assert.equal(await p.locator('#storyReplay .story-art-status').isVisible(),false);await p.locator('#storyReplay').evaluate(el=>Promise.all(el.closest('.mpanel').getAnimations().map(a=>a.finished)));assert((await p.locator('#storyReplay img').boundingBox()).width>(await card.locator('img').boundingBox()).width*1.5);
  assert.equal(await p.locator('#storyReplay').evaluate(el=>el.scrollWidth>el.clientWidth),false);await p.screenshot({path:new URL(`${tag}-${id}-replay.png`,out).pathname});
  if(i%2)await p.locator('#mX').click();else await p.keyboard.press('Escape');assert.equal(await p.locator('#storyReplay').count(),0);assert(await card.evaluate(el=>el===document.activeElement));assert.equal(await snapshot(),before);await card.click();await p.locator('#mOk').click();assert.equal(await snapshot(),before);
 }
 assert(requested.every(id=>fixture.owned.includes(id)),'locked illustration was requested');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await p.locator('.story').first().scrollIntoViewIfNeeded();await p.screenshot({path:new URL(`${tag}-collection.png`,out).pathname});await p.reload();await boot();assert.deepEqual(await p.evaluate(()=>__tzz.state.gacha.owned),['c_apron',...fixture.owned]);assert.equal(await p.evaluate(()=>__tzz.state.coins),12345);assert.equal(await p.evaluate(()=>__tzz.E.cardsComplete(__tzz.state)),fixture.owned.length===8);
 const row={entry,width:fixture.width,height:fixture.height||852,owned:fixture.owned,status:'pass',realArtAndMapping:true,lockedImagesNotRequested:true,legacyRootSave:true,originalText:true,readOnlyReplay:true,keyboardAndFocus:true,reloadProgress:true,noRepeatRewards:true,errors};results.push(row);fs.writeFileSync(new URL('results.json',out),JSON.stringify(results,null,2));console.log(JSON.stringify(row));await c.close();
}
for(const entry of ['/preview/','/preview/pet/game/']){
 const fixture={width:320,height:568,owned:['k_1','k_4']},o=await setup(entry,fixture),{c,p,errors,snapshot}=o;let release;const gate=new Promise(r=>release=r);await p.route('**/storycards/story_k_1.webp*',async route=>{await gate;await route.fulfill({status:entry.includes('/game/')?200:404,contentType:'image/webp',body:'invalid illustration fixture'})});
 await p.evaluate(()=>__tzz.renderTab());const before=await snapshot(),card=p.locator('.story-open[data-arg="k_1"]');await card.scrollIntoViewIfNeeded();await card.click();await p.locator('#storyReplay [data-story-state="loading"]').waitFor();assert.equal(await p.locator('#storyReplay .story-art-status').innerText(),'插图加载中…');assert.equal(await snapshot(),before);
 // Close while an image is pending, then finish its failed response and reopen.
 await p.keyboard.press('Escape');release();await card.locator('[data-story-state="error"]').waitFor();assert.equal(await snapshot(),before);await card.focus();await p.keyboard.press('Enter');await p.locator('#storyReplay [data-story-state="error"]').waitFor();assert.equal(await p.locator('#storyReplay img').isVisible(),false);assert.equal(await p.locator('#storyReplay .story-art-status').innerText(),'插图暂时无法加载，仍可阅读故事文字。');assert.equal(await p.locator('#storyReplay .mnote').innerText(),legacyE.ITEM_BY_ID.k_1.text);await p.locator('#storyReplay').evaluate(el=>Promise.all(el.closest('.mpanel').getAnimations().map(a=>a.finished)));await p.screenshot({path:new URL(`${entry.includes('/game/')?'standalone':'main'}-320-fallback.png`,out).pathname});await p.locator('#mX').click();assert(await card.evaluate(el=>el===document.activeElement));assert.equal(await snapshot(),before);
 await p.locator('.story-open[data-arg="k_4"]').click();await p.locator('#storyReplay [data-story-state="ready"]').waitFor();await p.locator('#mOk').click();assert.equal(await snapshot(),before);assert.deepEqual(errors,[]);const row={entry,width:320,status:'pass',pendingClose:true,failure:entry.includes('/game/')?'corrupt-image':'HTTP404',explicitTextFallback:true,otherImageStillWorks:true,stateAndFocusPreserved:true};results.push(row);fs.writeFileSync(new URL('results.json',out),JSON.stringify(results,null,2));console.log(JSON.stringify(row));await c.close();
}
await b.close();
