import fs from 'node:fs';import assert from 'node:assert/strict';const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=process.env.CEO_EMBED_OUTPUT||'/tmp/ceo-embedded';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),rows=[];
for(const width of [320,393]){const c=await browser.newContext({viewport:{width,height:852},deviceScaleFactor:1});await c.addInitScript(()=>{let t;Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}})});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765/preview/');await p.waitForFunction(()=>window.__tzz);await p.evaluate(async()=>{for(let n=0;n<5;n++){if(__tzz.modalOpen())__tzz.closeModal();await new Promise(r=>setTimeout(r,50))}const E=__tzz.E,s=E.newState(Date.now());s.rev=__tzz.state.rev;s.coins=123456789;s.muted=true;s.shops.forEach(x=>{x.open=true;x.lv=1;x.emp=0});Object.values(s.ceos).forEach(x=>{x.unlocked=true;x.lv=1});s.crossSeen=Object.fromEntries(Object.keys(E.CROSS).map(k=>[k,true]));s.zombie=ZBCore.norm({lv:{atk:3,rate:4,hp:5,ult:6},cleared:7});__tzz.state=s;if(!__tzz.persist())throw Error('fixture save');__tzz.switchShop(0);__tzz.setTab('shop');__tzz.renderTab();localStorage.setItem('tangzhe-save','FORMAL-SENTINEL')});let prices=null;
 for(const id of ['c77','pearl','otaku','rocket','c77']){
  if(await p.evaluate(()=>__tzz.zbCeo())!==id){await p.evaluate(()=>__tzz.setTab('ceo'));await p.locator(`[data-act="assign"][data-arg="${id}"]`).click();await p.locator('[data-pick="0"]').click();await p.locator('#pvYes').click();await p.evaluate(()=>{__tzz.setTab('shop');__tzz.renderTab()})}
  const before=await p.evaluate(()=>({coins:__tzz.state.coins,zombie:JSON.stringify(__tzz.state.zombie),ceo:__tzz.zbCeo()}));assert.equal(before.ceo,id);await p.locator('[data-act="zombie"]').click();const frame=await p.locator('#zbFrame').contentFrame();await frame.locator('#train .tr').first().waitFor();await p.waitForFunction(id=>document.querySelector('#zbFrame').contentWindow.__zb?.ceo===id,id);
  const actual=await frame.locator('body').evaluate(()=>({embed:__zb.EMBED,ceo:__zb.ceo,coins:__zb.proto.coins,zombie:ZBCore.norm(__zb.proto),prices:__zb.TRAIN.map(t=>__zb.price(t,__zb.proto.lv[t.id])),hero:ZBCore.HEROES[__zb.ceo],protoSaved:localStorage.getItem(__zb.PROTO_KEY)}));assert(actual.embed);assert.equal(actual.ceo,id);assert.equal(actual.coins,before.coins);assert.equal(actual.coins,123456789);assert.deepEqual(actual.zombie,JSON.parse(before.zombie));assert.equal(actual.protoSaved,null);if(prices)assert.deepEqual(actual.prices,prices);else prices=actual.prices;
  const names=await frame.locator('#train .t b').allTextContents();assert(names[0].includes(actual.hero.atk));assert(names[1].includes(actual.hero.atk));assert(names[2].includes(actual.hero.name));assert(names[3].includes(actual.hero.ult));assert.equal(await frame.locator('body').evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await frame.locator('#train').scrollIntoViewIfNeeded();await p.screenshot({path:`${out}/embedded-${width}-${id}.png`});await frame.locator('#exitBtn').click();await p.waitForFunction(()=>!__tzz.zbOpen);assert.equal(await p.evaluate(()=>__tzz.state.coins),before.coins);assert.equal(await p.evaluate(()=>JSON.stringify(__tzz.state.zombie)),before.zombie);assert.equal(await p.evaluate(()=>localStorage.getItem('tangzhe-save')),'FORMAL-SENTINEL');rows.push({width,ceo:id,names,embedded:true,realAssignmentUI:true,realMessageChannel:true,coins:actual.coins,sharedLevelsAndPrices:true,status:'pass'});
 }assert.deepEqual(errors,[]);await c.close();}
await browser.close();fs.writeFileSync(`${out}/results.json`,JSON.stringify(rows,null,2));console.log(`${rows.length} actual host iframe / CEO assignment cases passed`);
