// Disposable browser fixtures: no production save or economy changes.
import fs from 'node:fs';import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=process.env.FOLLOWUP_OUTPUT||'/tmp/followup-output';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),rows=[];
for(const [entry,width] of [['/preview/',320],['/preview/pet/game/',393]]){
 const c=await browser.newContext({viewport:{width,height:852},deviceScaleFactor:1});await c.addInitScript(()=>{window.qaFrames=[];window.requestAnimationFrame=fn=>(qaFrames.push(fn),qaFrames.length);window.qaFrame=()=>{const q=qaFrames.splice(0);q.forEach(fn=>fn(10000))}});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765'+entry);await p.waitForFunction(()=>window.__tzz);
 const ids=await p.evaluate(()=>{while(__tzz.modalOpen())__tzz.closeModal();const s=__tzz.E.newState(Date.now());s.rev=__tzz.state.rev;s.coins=123456;s.muted=true;s.shops.forEach(x=>{x.open=true;x.lv=1;x.emp=0});s.gacha.owned=__tzz.E.ITEMS.filter(x=>x.type==='decor').map(x=>x.id);s.decorHidden=[...s.gacha.owned];__tzz.state=s;__tzz.clearVisitors();__tzz.setTab('shop');__tzz.resize();qaFrame();qaFrame();localStorage.setItem('tangzhe-save','FORMAL-SENTINEL');return s.gacha.owned});await p.waitForTimeout(1500);await p.evaluate(()=>{qaFrame();qaFrame()});
 const invariant=()=>p.evaluate(()=>JSON.stringify({coins:__tzz.state.coins,rate:__tzz.E.baseRate(__tzz.state),owned:__tzz.state.gacha.owned,formal:localStorage.getItem('tangzhe-save')}));const before=await invariant();
 for(let shop=0;shop<4;shop++)for(const id of ids){
  await p.evaluate(shop=>{__tzz.switchShop(shop);__tzz.setTab('shop');qaFrame();qaFrame();const cv=document.querySelector('#scene');window.qaPixels=Array.from(cv.getContext('2d').getImageData(0,0,cv.width,cv.height).data)},shop);
  if(shop===0)await p.locator('#stage').screenshot({path:`${out}/baseline-${id}.png`});await p.evaluate(()=>{__tzz.setTab('col');__tzz.renderTab()});const card=p.locator(`[data-decor="${id}"]`);assert.equal(await card.locator('.decor-state').innerText(),'已收起');assert.equal(await card.locator('button').innerText(),'摆出');await card.locator('button').click();await p.evaluate(()=>{qaFrame();__tzz.renderTab()});assert.equal(await card.locator('.decor-state').innerText(),'已摆出 · 四家店',JSON.stringify(await p.evaluate(()=>({hidden:__tzz.state.decorHidden,blocked:__tzz.saveBlocked,toast:document.querySelector('#toast')?.textContent,frames:qaFrames.length}))));assert.equal(await card.locator('button').innerText(),'收起');await p.locator('.decor-view').click();await p.evaluate(()=>{qaFrame();qaFrame()});
  const pixels=await p.evaluate(()=>{const cv=document.querySelector('#scene'),d=cv.getContext('2d').getImageData(0,0,cv.width,cv.height).data;let count=0;for(let y=0;y<cv.height-1;y++)for(let x=0;x<cv.width-1;x++){const i=(y*cv.width+x)*4;if(d[i]!==qaPixels[i]||d[i+1]!==qaPixels[i+1]||d[i+2]!==qaPixels[i+2])count++}return count});assert(pixels>12,`${id} shop ${shop} invisible`);assert.equal(await invariant(),before);if(shop===0)await p.locator('#stage').screenshot({path:`${out}/decor-${width}-${id}.png`});
  await p.evaluate(id=>{__tzz.act('decor',id);qaFrame();qaFrame()},id);const restored=await p.evaluate(()=>{const cv=document.querySelector('#scene'),d=cv.getContext('2d').getImageData(0,0,cv.width,cv.height).data;/* Fractional CSS canvas height leaves an antialiased bottom edge; compare the full interior. */for(let y=0;y<cv.height-1;y++)for(let x=0;x<cv.width-1;x++)for(let ch=0;ch<4;ch++){const i=(y*cv.width+x)*4+ch;if(d[i]!==qaPixels[i])return false}return true});assert(restored,`${id} shop ${shop} did not restore canvas interior`);rows.push({entry,width,shop,id,pixels,status:'pass'});
 }
 await p.evaluate(()=>{__tzz.setTab('col');__tzz.renderTab()});await p.locator('.decor-card').first().scrollIntoViewIfNeeded();await p.screenshot({path:`${out}/decor-${width}-collection.png`});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 // Transaction rollback: quota failure must not claim a changed state.
 const stateBefore=await p.evaluate(()=>JSON.stringify(__tzz.state.decorHidden));await p.evaluate(id=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===__tzz.SAVE_KEY)throw Error('quota fixture');return old.call(this,k,v)};__tzz.act('decor',id);Storage.prototype.setItem=old;__tzz.renderTab()},ids[0]);assert.equal(await p.evaluate(()=>JSON.stringify(__tzz.state.decorHidden)),stateBefore);assert.deepEqual(errors,[]);await c.close();
}
for(const width of [320,393]){
 const c=await browser.newContext({viewport:{width,height:852},deviceScaleFactor:1});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765/preview/zombie/');await p.waitForFunction(()=>window.__zb);let prices=null;
 for(const ceo of ['c77','pearl','otaku','rocket','c77']){
  const r=await p.evaluate(ceo=>{const z={lv:{atk:3,rate:4,hp:5,ult:6},cleared:7};__zb.onState({zb:'state',ceo,coins:123456789,z});return {hero:ZBCore.HEROES[ceo],lv:{...__zb.proto.lv},prices:__zb.TRAIN.map(t=>__zb.price(t,__zb.proto.lv[t.id])),coins:__zb.proto.coins,clear:__zb.proto.cleared,storage:localStorage.getItem(__zb.PROTO_KEY)}},ceo);
  const names=await p.locator('#train .t b').allTextContents(),desc=await p.locator('#train .t small').allTextContents();assert(names[0].includes(r.hero.atk));assert(names[1].includes(r.hero.atk));assert(names[2].includes(r.hero.name));assert(names[3].includes(r.hero.ult));assert(desc[0].includes('×1.52'));assert(desc[1].includes('0.45 秒'));assert(desc[2].includes('176'));assert(desc[3].includes('×2.99'));if(prices)assert.deepEqual(r.prices,prices);else prices=r.prices;assert.equal(r.coins,123456789);assert.equal(r.clear,7);assert.equal(r.storage,null);assert.deepEqual(r.lv,{atk:3,rate:4,hp:5,ult:6});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#train').scrollIntoViewIfNeeded();await p.screenshot({path:`${out}/ceo-${width}-${ceo}.png`});rows.push({width,ceo,names,descriptions:desc,sharedLevelsAndPrices:true,status:'pass'});
 }assert.deepEqual(errors,[]);await c.close();
}await browser.close();fs.writeFileSync(`${out}/results.json`,JSON.stringify(rows,null,2));console.log(`${rows.length} decoration / CEO cases passed, transaction rollback and no overflow passed`);
