// Local isolated storage only; proves current shared-prototype behavior, not storage isolation.
import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const B=process.env.INTEGRATION_BASE||'http://127.0.0.1:8783',browser=await chromium.launch(),rows=[];
try{
 const c=await browser.newContext(),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await c.addInitScript(()=>{Date.now=()=>1790000000000});
 await p.goto(B+'/');await p.waitForFunction(()=>window.__tzz);
 const before=await p.evaluate(()=>{const t=__tzz;t.closeModal();const rev=t.state.rev;t.state=t.E.newState(Date.now());t.state.rev=rev;t.state.coins=12345;t.state.muted=true;t.state.taps=1;t.state.zombie=ZBCore.norm({cleared:50,endBest:{t:300,kills:9}});ZBCore.applyResult(t.state.zombie,{mode:'endless',t:650,kills:42,runId:'integrationrun'});if(!t.persist())throw Error('persist');localStorage.setItem('tangzhe-preview-save','PREVIEW-SENTINEL');return JSON.stringify(t.state.zombie)});
 for(const path of ['/pet/game/','/']){await p.goto(B+path);await p.waitForFunction(()=>window.__tzz);assert.equal(await p.evaluate(()=>JSON.stringify(__tzz.state.zombie)),before);assert.equal(await p.evaluate(()=>__tzz.state.coins),12345);assert(await p.evaluate(()=>__tzz.persist()));assert.equal(await p.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('tangzhe-save')).zombie)),before);}
 await p.evaluate(()=>{__tzz.closeModal();__tzz.act('zombie')});await p.waitForFunction(()=>document.querySelector('#zbFrame').contentWindow.__zb?.proto.ready);const f=p.frames().find(f=>f.url().includes('/zombie/'));assert.equal(new URL(f.url()).searchParams.get('v'),'15c');assert.equal(await p.evaluate(()=>new URL(document.querySelector('script[src^="zombie/zbcore"]').src).searchParams.get('v')),'15c');assert.equal(await f.evaluate(()=>JSON.stringify(ZBCore.norm(__zb.proto))),before);assert.deepEqual(await f.evaluate(()=>[...document.querySelectorAll('script[src],link[href*="zombie.css"]')].filter(e=>!/zbsfx/.test(e.src||e.href)).map(e=>new URL(e.src||e.href).searchParams.get('v'))),['15c','15c','15c']);assert.equal(await p.evaluate(()=>localStorage.getItem('tangzhe-preview-save')),'PREVIEW-SENTINEL');assert.deepEqual(errors,[]);rows.push({case:'endTop/root-pet-persist-root/parent-child-norm-cache/coins-sentinel',pass:true});await c.close();
 const d=await browser.newContext(),a=await d.newPage(),b=await d.newPage();await d.addInitScript(()=>{if(!localStorage.getItem('fixture')){localStorage.setItem('fixture','1');localStorage.setItem('tangzhe-zombie-proto',JSON.stringify({cleared:50,endBest:{t:300,kills:9},coins:5e10}));localStorage.setItem('tangzhe-save','FORMAL-SENTINEL');localStorage.setItem('tangzhe-preview-save','PREVIEW-SENTINEL')}});
 await a.goto(B+'/zombie/');await b.goto(B+'/preview/zombie/');for(const p of [a,b])await p.waitForFunction(()=>window.__zb);
 const keys=await a.evaluate(()=>[__zb.PROTO_KEY,__zb.TOP_KEY,__zb.LOCK]);assert.deepEqual(await b.evaluate(()=>[__zb.PROTO_KEY,__zb.TOP_KEY,__zb.LOCK]),keys);
 const save=(p,id,t)=>p.evaluate(([id,t])=>__zb.saveProto(z=>ZBCore.applyResult(z,{mode:'endless',t,kills:1,runId:id})),[id,t]);assert.deepEqual(await Promise.all([save(a,'formalrun',600),save(b,'previewrun',700)]),[true,true]);await a.reload();await b.reload();for(const p of [a,b]){await p.waitForFunction(()=>window.__zb);assert.deepEqual(await p.evaluate(()=>__zb.proto.endTop.map(e=>e.id)),['previewrun','formalrun','legacy6fhc']);assert.deepEqual(await p.evaluate(()=>[localStorage.getItem('tangzhe-save'),localStorage.getItem('tangzhe-preview-save')]),['FORMAL-SENTINEL','PREVIEW-SENTINEL']);}
 rows.push({case:'shared-prototype-keys-lock-and-merged-scores-confirmed',pass:true,keys,risk:'Formal and preview standalone prototypes share scores and training; not isolated.'});await d.close();
}finally{await browser.close();}
fs.writeFileSync(process.env.ZB_INTEGRATION_OUT||'/tmp/zbtop-integration.json',JSON.stringify(rows,null,2));console.log(JSON.stringify(rows));
