import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const repo=process.env.INTEGRATION_REPO,base=process.env.INTEGRATION_BASE||'http://127.0.0.1:8783',fixed=process.env.EXPECT_PROTECTED==='1',out=process.env.ZB_OLD_OUT||'/tmp/old-parent.json';const browser=await chromium.launch(),rows=[];
try{for(const mode of ['version-fetch-fails','reload-flag-already-set']){
 const c=await browser.newContext(),p=await c.newPage();let old=false,versionRequests=0;const errors=[];p.on('pageerror',e=>errors.push(e.message));await c.addInitScript(()=>{Date.now=()=>1790000000000});
 await c.route('**/*',async route=>{const u=new URL(route.request().url());if(old&&u.pathname==='/version.json'){versionRequests++;if(mode==='version-fetch-fails')return route.abort('failed');return route.fulfill({contentType:'application/json',body:JSON.stringify({v:'15c'})});}if(old&&(/\.(js|css|html)$/.test(u.pathname)||u.pathname==='/'||u.pathname==='/zombie/')){const path=u.pathname==='/'?'index.html':u.pathname==='/zombie/'?'zombie/index.html':u.pathname.slice(1);try{const body=execFileSync('git',['-C',repo,'show','f597999:'+path]);return route.fulfill({contentType:path.endsWith('.js')?'application/javascript':path.endsWith('.css')?'text/css':'text/html',body});}catch{}}await route.continue();});
 await p.goto(base+'/');await p.waitForFunction(()=>window.__tzz);const seed=await p.evaluate(()=>{const t=__tzz,rev=t.state.rev,s=t.E.newState(Date.now());s.rev=rev;s.coins=12345;s.taps=1;s.muted=true;s.shops.forEach(x=>x.emp=0);s.integrationSentinel={untouched:'preserve'};s.zombie=ZBCore.norm({cleared:50,endBest:{t:700,kills:7},endTop:[{t:700,kills:7,id:'firstrun',at:1},{t:500,kills:5,id:'secondrun',at:2}]});t.state=s;t.closeModal();if(!t.persist())throw Error('seed save');sessionStorage.setItem('tzz-reload-15c','1');return JSON.parse(localStorage.getItem('tangzhe-save'));});
 old=true;await p.goto(base+'/');await p.waitForFunction(()=>window.__tzz);await p.evaluate(()=>{__tzz.closeModal();__tzz.openZombie()});await p.waitForFunction(()=>document.querySelector('#zbFrame').contentWindow.__zb?.proto.ready);assert.equal(await p.evaluate(()=>Array.isArray(__tzz.state.zombie.endTop)),false);const oldSaved=await p.evaluate(()=>{__tzz.closeZombie();if(!__tzz.persist()||!__tzz.persist())throw Error('old persist');return JSON.parse(localStorage.getItem('tangzhe-save'));});assert(!oldSaved.zombie.endTop);assert.equal(oldSaved.coins,12345);assert.deepEqual(oldSaved.integrationSentinel,seed.integrationSentinel);assert(versionRequests>0);
 old=false;await p.goto(base+'/');await p.waitForFunction(()=>window.__tzz);await p.evaluate(()=>{__tzz.closeModal();__tzz.openZombie()});await p.waitForFunction(()=>document.querySelector('#zbFrame').contentWindow.__zb?.proto.ready);const recovered=await p.evaluate(()=>{__tzz.closeZombie();if(!__tzz.persist())throw Error('new persist');return JSON.parse(localStorage.getItem('tangzhe-save'));});assert.equal(recovered.coins,12345);assert.deepEqual(recovered.integrationSentinel,seed.integrationSentinel);if(fixed)assert.deepEqual(recovered.zombie.endTop,seed.zombie.endTop);else{assert.equal(recovered.zombie.endTop.length,1);assert.match(recovered.zombie.endTop[0].id,/^legacy/);}assert.deepEqual(errors,[]);rows.push({mode,fixed,seedTop:seed.zombie.endTop,oldTopAbsent:!oldSaved.zombie.endTop,oldMirror:oldSaved.zombieEndTopV1||null,recoveredTop:recovered.zombie.endTop,coins:recovered.coins,versionRequests,errors});await c.close();
}}finally{await browser.close();}fs.writeFileSync(out,JSON.stringify(rows,null,2));console.log(JSON.stringify(rows));
