import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url), here=path.dirname(new URL(import.meta.url).pathname);
const root=path.resolve(process.env.TOAST_ROOT||here);
const E=require(path.join(root,'economy.js'));
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const results=[]; const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep)&&f!==root){res.writeHead(403).end();return;}try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r)); const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true});
const entries=process.env.TOAST_ENTRIES?process.env.TOAST_ENTRIES.split(','):['/','/pet/game/','/preview/','/preview/pet/game/'];
const shot=p=>p.evaluate(()=>({text:document.querySelector('#toast').textContent,visible:!document.querySelector('#toast').classList.contains('hidden'),role:document.querySelector('#toast').getAttribute('role')}));
async function setup(entry){const c=await browser.newContext({viewport:{width:393,height:852}});const st=E.newState(Date.now());st.coins=100000;st.muted=true;st.taps=1;
 await c.addInitScript(({st,preview})=>{const k=preview?'tangzhe-preview-save':'tangzhe-save';localStorage.setItem(k,JSON.stringify(st));localStorage.setItem(k+'-bak',JSON.stringify(st));localStorage.setItem(preview?'tangzhe-save':'tangzhe-preview-save','ISOLATION-SENTINEL');let t;Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}});},{st,preview:entry.includes('preview')});
 await c.route('**/app.js*',async route=>{const response=await route.fetch();let source=await response.text();assert(source.includes('window.__tzz = {'),'probe insertion point');source=source.replace('window.__tzz = {','window.__toastProbe={normal:(...a)=>toast(...a),error:msg=>saveFailNote({stage:"save"},msg),feedback:()=>failBuy(document.createElement("button"),"金币不够")};\nwindow.__tzz = {');await route.fulfill({response,body:source});});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+entry);await p.waitForFunction(()=>window.__tzz&&window.__toastProbe);await p.clock.install();await p.clock.pauseAt(new Date(Date.now()+1000));await p.clock.runFor(4000);return {c,p,errors};}
async function test(entry,name,fn){if(process.env.TOAST_CASE_MATCH&&!name.includes(process.env.TOAST_CASE_MATCH))return;let x;try{x=await setup(entry);const detail=await fn(x.p);assert.deepEqual(x.errors,[],'page errors');results.push({entry,name,status:'pass',detail});}catch(e){results.push({entry,name,status:'fail',error:e.message});}finally{await x?.c.close();}}
const error=p=>p.evaluate(()=>__toastProbe.error('回归测试没有生效'));
const normal=(p,msg='普通提示',ms=1900)=>p.evaluate(({msg,ms})=>__toastProbe.normal(msg,ms),{msg,ms});
const expectError=async p=>{const s=await shot(p);assert(s.visible&&s.text.includes('保存失败'),JSON.stringify(s));return s;};
for(const entry of entries){
 if(process.env.TOAST_EXTENDED){
 await test(entry,'extended: capacity one under 100 ambient notices',async p=>{await error(p);await p.evaluate(()=>{for(let i=0;i<100;i++)__toastProbe.normal('N'+i,1900,'','ambient')});await expectError(p);await p.clock.runFor(2800);const s=await shot(p);assert.equal(s.text,'N99');await p.clock.runFor(1900);assert.equal((await shot(p)).visible,false);return s;});
 await test(entry,'extended: necessary feedback followed by ambient event',async p=>{await error(p);await p.evaluate(()=>{__toastProbe.feedback();__toastProbe.normal('人造太阳：超频30秒！',1900,'','ambient')});await p.clock.runFor(2800);const s=await shot(p);assert(s.text.includes('金币不够'),JSON.stringify(s));return s;});
 await test(entry,'extended: overdue hold plus new feedback does not resurrect old queue',async p=>{await error(p);await normal(p,'旧提示');await p.evaluate(()=>{const original=performance.now.bind(performance);performance.now=()=>original()+60000;__toastProbe.normal('新操作成功')});await p.clock.runFor(1900);const s=await shot(p);assert.notEqual(s.text,'旧提示',JSON.stringify(s));return s;});
 }
 await test(entry,'normal one second after error cannot replace it',async p=>{await error(p);await p.clock.runFor(1000);await normal(p);return expectError(p);});
 await test(entry,'same-frame tea/book/tech save error survives',async p=>{const r=await p.evaluate(()=>{const t=__tzz;t.state.gacha.owned.push('s_fountain','s_portal','s_sun');t.state.shops.forEach(s=>{s.open=true;s.emp=1});t.state.cur=0;const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===t.BAK_KEY)throw Error('injected backup fault');return set.call(this,k,v)};const coins=t.state.coins;t.forceSupers();return {coinsBefore:coins,coinsAfter:t.state.coins};});assert.equal(r.coinsAfter,r.coinsBefore);return {r,toast:await expectError(p)};});
 await test(entry,'replacement cancels previous normal timer',async p=>{await normal(p,'旧普通提示',100);await p.clock.runFor(50);await error(p);await p.clock.runFor(100);return expectError(p);});
 await test(entry,'consecutive errors survive original timer deadline',async p=>{await error(p);await p.clock.runFor(1000);await p.evaluate(()=>__toastProbe.error('第二次失败'));await p.clock.runFor(1850);return expectError(p);});
 await test(entry,'normal display recovers after error ends',async p=>{await error(p);await p.clock.runFor(3000);await normal(p,'恢复普通提示');const s=await shot(p);assert(s.visible&&s.text==='恢复普通提示');await p.clock.runFor(2000);assert.equal((await shot(p)).visible,false);return s;});
 await test(entry,'necessary operation feedback is retained behind error',async p=>{await error(p);await p.evaluate(()=>__toastProbe.feedback());await expectError(p);await p.clock.runFor(2850);const s=await shot(p);assert(s.visible&&s.text.includes('金币不够'),JSON.stringify(s));return s;});
 await test(entry,'in-app tab switch preserves visible error',async p=>{await error(p);await p.evaluate(()=>{__tzz.setTab('col');__tzz.setTab('home')});return expectError(p);});
 await test(entry,'simulated hide/resume accepts new feedback',async p=>{await error(p);await p.evaluate(()=>{__tzz.pets.manual(false);Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await p.clock.fastForward(60000);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));__tzz.pets.manual(true)});await normal(p,'恢复前台');const s=await shot(p);assert(s.visible&&s.text==='恢复前台');return s;});
 for(const mode of ['main-throw','main-silent','bak-throw','bak-silent'])await test(entry,'wallet baseline isolation: '+mode,async p=>{const r=await p.evaluate(mode=>{const t=__tzz,other=t.SAVE_KEY.startsWith('tangzhe-preview')?'tangzhe-save':'tangzhe-preview-save';const set=Storage.prototype.setItem;const historical=JSON.parse(localStorage.getItem(t.SAVE_KEY));historical.coins-=17;set.call(localStorage,t.BAK_KEY,JSON.stringify(historical));const snap=()=>({coins:t.state.coins,main:localStorage.getItem(t.SAVE_KEY),bak:localStorage.getItem(t.BAK_KEY),other:localStorage.getItem(other)});const before=snap();const target=mode.startsWith('main')?t.SAVE_KEY:t.BAK_KEY;Storage.prototype.setItem=function(k,v){if(k===target){if(mode.endsWith('throw'))throw Error('injected write fault');return;}return set.call(this,k,v)};const tr=t.txn(s=>{s.coins+=123;return {ok:true}},0,'金币没有改变');return {before,after:snap(),ok:tr.ok};},mode);const equal=Object.fromEntries(Object.keys(r.before).map(k=>[k,r.before[k]===r.after[k]]));const silentPreview=entry.includes('preview')&&mode==='main-silent';assert.equal(r.ok,silentPreview);assert(equal.main&&equal.other,JSON.stringify(equal));assert.equal(r.after.coins,r.before.coins+(silentPreview?123:0));assert.equal(r.after.bak,mode.startsWith('main')?r.before.main:r.before.bak);return {classification:silentPreview?'known-preview-injected-silent-write':mode.startsWith('main')?'expected-rolling-backup':'transaction-rollback',equal,ok:r.ok};});
 if(!process.env.TOAST_EXTENDED)results.push({entry,name:'normal queue capacity and expiry policy',status:'pending-policy',reason:'See separate queue suite for candidate policy; baseline has no queue.'});
}
await browser.close();await new Promise(r=>server.close(r));
const report={root,sha:execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),browser:'Chromium; no physical device/WebKit',instrumentation:'In-memory route inserts accessors only; source files unchanged. Synthetic visibility events, not OS suspension.',results,counts:Object.fromEntries(['pass','fail','pending-policy'].map(s=>[s,results.filter(r=>r.status===s).length]))};
fs.writeFileSync(process.env.TOAST_OUTPUT||'/tmp/toast-regression-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.counts.fail)process.exitCode=1;
