// Local integrated TD/15b/toast scenario; fresh context, synthetic state, no live saves.
import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const base=process.env.INTEGRATION_BASE||'http://127.0.0.1:8781';const browser=await chromium.launch();const rows=[];
try{for(const width of [320,393]){
 const c=await browser.newContext({viewport:{width,height:852},hasTouch:true,isMobile:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await c.addInitScript(()=>{Date.now=()=>1790000000000;let t;Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}});const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===window.__failKey)throw Error('injected');return set.call(this,k,v)};});
 await c.route('**/app.js*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text()).replace('window.__tzz = {','window.__integrationAmbient=()=>toast("人造太阳提示",2400,"","ambient");window.__tzz = {')});});
 await p.goto(base+'/');await p.waitForFunction(()=>window.__tzz&&PetGame.speciesReady('dog'));
 await p.evaluate(()=>{const t=__tzz,E=t.E,s=E.testHomesState(Date.now(),2);s.rev=t.state.rev;s.coins=1e10;s.totalEarned=1;s.muted=true;s.taps=1;s.cur=3;s.shops.forEach(x=>x.emp=0);s.gacha.owned=['k_1','c_apron'];E.homeOf(s,'c77').placed=[];for(const [id,x,y] of [['furn_bed',2,0],['furn_sofa',0,3]]){E.buyFurniture(s,id);if(!E.placeItem(s,'c77',id,x,y,0,'floor').ok)throw Error('furniture fixture');}const buy=PetGame.buy(s,E,'c77',Date.now(),t.pet.M,()=>true,false,{species:'dog'});if(!buy.ok)throw Error(buy.why);t.state=s;t.closeModal();if(!t.persist())throw Error('seed persist');t.setTab('shop');t.switchShop(3);t.renderTab();localStorage.setItem('tangzhe-preview-save','CROSS-PREVIEW-SENTINEL');});
 const capture=()=>p.evaluate(()=>JSON.stringify({gacha:__tzz.state.gacha,pets:__tzz.state.pets.list.map(({uid,species,room,boughtAt})=>({uid,species,room,boughtAt})),homes:__tzz.state.homes}));
 const before=await capture(),coins=await p.evaluate(()=>__tzz.state.coins);
 await p.locator('[data-act="td"]').click();await p.waitForFunction(()=>__tzz.tdOpen);const frame=await p.waitForFunction(()=>document.querySelector('#tdFrame').contentWindow.__td?.proto.ready).then(()=>p.frames().find(f=>f.url().includes('/td/index.html')));assert(frame);
 await p.evaluate(()=>__failKey='tangzhe-save');await frame.locator('[data-up="bbq"]').click();await frame.waitForFunction(()=>!__td.pend);assert.equal(await p.evaluate(()=>__tzz.state.coins),coins);assert.equal(await capture(),before);
 await p.evaluate(()=>__integrationAmbient());assert((await p.locator('#toast').textContent()).includes('保存失败'));assert.equal(await p.locator('#toast').getAttribute('role'),'alert');
 await frame.locator('#exitBtn').click();await p.waitForFunction(()=>!__tzz.tdOpen);assert(await p.locator('#toast').isVisible());
 await p.evaluate(()=>__failKey=null);await p.locator('[data-act="td"]').click();await p.waitForFunction(()=>document.querySelector('#tdFrame').contentWindow.__td?.proto.ready);const f=p.frames().find(f=>f.url().includes('/td/index.html'));await f.locator('[data-up="bbq"]').click();await f.waitForFunction(()=>!__td.pend);assert.equal(await p.evaluate(()=>__tzz.state.coins),coins-1e6);await f.locator('#exitBtn').click();await p.waitForFunction(()=>!__tzz.tdOpen);
 await p.evaluate(()=>{__tzz.setTab('col');__tzz.act('card','k_1')});await p.locator('#storyReplay [data-story-state="ready"]').waitFor();await p.locator('#mOk').click();assert.equal(await capture(),before);
 await p.evaluate(()=>{__tzz.setTab('home');__tzz.homeAct('homeWho','c77');__tzz.homeAct('homeSub','room');__tzz.renderTab();__tzz.pets.draw();});await p.locator('[data-fid="furn_bed"] img').evaluate(i=>i.decode());await p.locator('[data-fid="furn_bed"]').click();await p.evaluate(()=>{for(let i=0;i<300;i++)__tzz.homeAdvanceActor(1/60);__tzz.pets.draw()});await p.waitForFunction(()=>{__tzz.homeDrawActor();return document.querySelector('#homeActor').classList.contains('posed')});assert.equal(await p.evaluate(()=>__tzz.homeActor.c77.pose.kind),'lie');assert.equal(await p.evaluate(()=>__tzz.state.td.lv.bbq),1);
 const savedTD=await p.evaluate(()=>JSON.stringify(__tzz.state.td));await p.goto(base+'/pet/game/');await p.waitForFunction(()=>window.__tzz);assert.equal(await p.evaluate(()=>JSON.stringify(__tzz.state.td)),savedTD);assert.equal(await capture(),before);await p.goto(base+'/');await p.waitForFunction(()=>window.__tzz);assert.equal(await p.evaluate(()=>JSON.stringify(__tzz.state.td)),savedTD);assert.equal(await p.evaluate(()=>localStorage.getItem('tangzhe-preview-save')),'CROSS-PREVIEW-SENTINEL');assert.deepEqual(errors,[]);rows.push({width,failedPurchaseRollback:true,errorHeldThroughTDExit:true,successfulUpgrade:true,storyReplay:true,ceoBedPose:true,rootPetRootPreserved:true,errors});await c.close();
}}finally{await browser.close();}
fs.writeFileSync(process.env.INTEGRATION_OUT||'/tmp/integration-cross.json',JSON.stringify(rows,null,2));console.log(JSON.stringify(rows));
