# 躺着也能赚 — 手机端端到端测试（WebKit = iPhone Safari 内核）
# 用法：先在本目录起静态服务（python3 -m http.server 49710），再 .pwvenv/bin/python test_playtest.py [URL]
import sys, json, os
from playwright.sync_api import sync_playwright
URL = sys.argv[1] if len(sys.argv) > 1 else 'http://127.0.0.1:49710/index.html'
KEY = 'tangzhe-save'
SHOTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), '_shots')
os.makedirs(SHOTS, exist_ok=True)
results = []
def check(cond, msg):
    results.append((bool(cond), msg)); print(('  ✓ ' if cond else '  ✗ ') + msg)
def S(pg, expr): return pg.evaluate(expr)
def st(pg): return pg.evaluate("JSON.parse(JSON.stringify(__tzz.state))")
def modal_visible(pg): return pg.evaluate("!document.querySelector('#modal').classList.contains('hidden')")
def close_modals(pg, n=6):
    for _ in range(n):
        if not modal_visible(pg): return
        for sel in ['#mOk', '#pvNo', '#mNo', '#claim']:
            if pg.locator(sel).count():
                pg.locator(sel).first.click(); pg.wait_for_timeout(250); break
        else: return

with sync_playwright() as p:
    b = p.webkit.launch()
    dev = p.devices['iPhone 15']
    ctx = b.new_context(**dev)
    pg = ctx.new_page(); errs = []
    def hook(page, tag):
        page.on('console', lambda m: m.type == 'error' and errs.append(f'{tag} {m.type}: {m.text}'))
        page.on('pageerror', lambda e: errs.append(f'{tag} pageerror: {e}'))
        page.on('response', lambda r: r.status >= 400 and errs.append(f'{tag} {r.status} {r.url}'))
    hook(pg, 'p1')
    print('== 1. 新开局 ==')
    pg.goto(URL); pg.evaluate("localStorage.clear()"); pg.reload(); pg.wait_for_timeout(900)
    check(modal_visible(pg) and '欢迎' in pg.inner_text('#mpanel'), '新玩家看到开场说明')
    pg.screenshot(path=f'{SHOTS}/01_intro.png')
    pg.click('#mOk'); pg.wait_for_timeout(200)
    s0 = st(pg)
    check(s0['v'] == 2 and s0['ceos']['c77']['at'] == 0 and s0['shops'][0]['emp'] == 0, '存档 v2：77 坐镇烧烤摊、员工未雇')
    check(S(pg, "__tzz.E.baseRate(__tzz.state)") == 0, '没员工不自动赚')
    box = pg.locator('#scene').bounding_box()
    for _ in range(25): pg.mouse.click(box['x'] + box['width'] * 0.4, box['y'] + box['height'] * 0.55); pg.wait_for_timeout(25)
    s1 = st(pg); check(s1['taps'] == 25 and s1['coins'] >= 25, f"手点 25 下 → {round(s1['coins'],1)} 金")
    pg.evaluate("__tzz.state.coins = Math.max(__tzz.state.coins, 60)"); pg.wait_for_timeout(300)
    pg.locator('[data-act="hire"]').click(); pg.wait_for_timeout(300)
    check(st(pg)['shops'][0]['emp'] == 1 and S(pg, "__tzz.E.baseRate(__tzz.state)") > 0, '雇小串后开始自动赚')
    c_a = S(pg, '__tzz.state.coins'); pg.wait_for_timeout(2100); c_b = S(pg, '__tzz.state.coins')
    check(c_b > c_a, f'在线自动产出 {round(c_a,2)} → {round(c_b,2)}')
    # 店铺 / 员工 / CEO 分开升级
    pg.evaluate("__tzz.state.coins = 1e6"); pg.wait_for_timeout(300)
    pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="emp"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="ceoUp"]').click(); pg.wait_for_timeout(150)
    s2 = st(pg); check(s2['shops'][0]['lv'] == 2 and s2['shops'][0]['emp'] == 2 and s2['ceos']['c77']['lv'] == 2, '店铺 Lv2 / 员工 Lv2 / CEO Lv2 分开升级')
    pg.evaluate("__tzz.state.shops[0].lv = 9; __tzz.renderTab()"); pg.wait_for_timeout(200)
    pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(500)
    check(st(pg)['shops'][0]['lv'] == 10, '冲 Lv10 里程碑')
    pg.screenshot(path=f'{SHOTS}/02_milestone.png')
    print('== 2. 开店 + CEO 解锁 ==')
    pg.locator('#shopTabs [data-shop="1"]').click(); pg.wait_for_timeout(200)
    pg.locator('[data-act="open"]').click(); pg.wait_for_timeout(500)
    check(modal_visible(pg) and '珍珠姐' in pg.inner_text('#mpanel'), '开奶茶店 → 珍珠姐加入弹窗')
    close_modals(pg)
    check(st(pg)['ceos']['pearl']['at'] == 1, '珍珠姐坐镇奶茶店')
    pg.evaluate("""(()=>{const s=__tzz.state, E=__tzz.E; s.coins=1e13; E.hireEmp(s,1); E.openShop(s,2); E.hireEmp(s,2); E.openShop(s,3); s.shops[3].lv=24; __tzz.persist(); __tzz.switchShop(3); __tzz.renderTab();})()""")
    pg.wait_for_timeout(300); close_modals(pg)
    check(not S(pg, "__tzz.E.gachaUnlocked(__tzz.state)"), '科技公司没雇员工前盲盒不开放')
    pg.locator('[data-act="hire"]').click(); pg.wait_for_timeout(400)
    check(modal_visible(pg) and '盲盒' in pg.inner_text('#mpanel'), '雇到科技公司员工 → 盲盒开放弹窗')
    close_modals(pg)
    pg.evaluate("__tzz.state.coins = 1e13"); pg.wait_for_timeout(200)
    pg.locator('[data-act="amt"][data-arg="1"]').click(); pg.wait_for_timeout(100)
    pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(500)
    check(modal_visible(pg) and '火箭老板' in pg.inner_text('#mpanel'), '科技公司 Lv25 → 火箭老板加入')
    close_modals(pg)
    check(st(pg)['ceos']['rocket']['at'] == 3, '火箭老板坐镇科技公司')
    pg.screenshot(path=f'{SHOTS}/03_tech.png')
    print('== 3. 调任预览 ==')
    pg.locator('#bottomNav [data-tab="ceo"]').click(); pg.wait_for_timeout(250)
    pg.screenshot(path=f'{SHOTS}/04_ceo_tab.png')
    before = st(pg)
    pg.locator('[data-act="assign"][data-arg="rocket"]').click(); pg.wait_for_timeout(300)
    check(pg.locator('#sheet .pick').count() == 5, '调任选择：4 家店 + 休息')
    pg.screenshot(path=f'{SHOTS}/05_pick.png')
    pg.locator('#sheet [data-pick="0"]').click(); pg.wait_for_timeout(400)
    txt = pg.inner_text('#mpanel')
    check('调任预览' in txt and '全街每秒' in txt and '火箭烤炉' in txt and '麻辣服务器' in txt, '预览：每店+全街 调前→调后，列出两个跨行事件')
    check(pg.locator('.pv-table .down').count() >= 2 and pg.locator('.pv-table tr.total .down').count() == 1, '预览：变少的标红（含全街合计）')
    check('8 小时 → 10 小时' in txt, '预览显示离线上限变化')
    pg.screenshot(path=f'{SHOTS}/06_preview.png')
    pg.click('#pvNo'); pg.wait_for_timeout(250)
    # 涨绿：让珍珠姐先休息，再预览她回奶茶店
    pg.evaluate("__tzz.state.ceos.pearl.at = -1; __tzz.showPreview('pearl', 1)"); pg.wait_for_timeout(300)
    upn = pg.locator('.pv-table .up').count()
    if upn < 2: print('DEBUG', pg.inner_text('#mpanel')[:400])
    check(upn >= 1, '预览：变多的标绿（空缺店派 CEO）')
    pg.click('#pvNo'); pg.wait_for_timeout(200); pg.evaluate("__tzz.state.ceos.pearl.at = 1")
    check(st(pg)['ceos'] == before['ceos'], '「再想想」不改任何安排')
    pg.locator('[data-act="assign"][data-arg="rocket"]').click(); pg.wait_for_timeout(300)
    pg.locator('#sheet [data-pick="0"]').click(); pg.wait_for_timeout(300)
    pg.click('#pvYes'); pg.wait_for_timeout(600)
    s3 = st(pg)
    check(s3['ceos']['rocket']['at'] == 0 and s3['ceos']['c77']['at'] == 3, '确认后火箭老板↔77 互换')
    check(S(pg, "__tzz.E.signOf(__tzz.state,0).name") == '老马烧烤', '招牌换成「老马烧烤」')
    check(modal_visible(pg) and '火箭烤炉' in pg.inner_text('#mpanel'), '跨行事件漫画：火箭烤炉')
    pg.wait_for_timeout(900); pg.screenshot(path=f'{SHOTS}/07_comic.png')
    pg.click('#mOk'); pg.wait_for_timeout(400)
    check(modal_visible(pg) and '麻辣服务器' in pg.inner_text('#mpanel'), '第二个跨行漫画：麻辣服务器')
    close_modals(pg)
    check(S(pg, "__tzz.E.offlineCap(__tzz.state)") == 36000, '77 在科技公司：离线上限 10 小时')
    pg.locator('#bottomNav [data-tab="shop"]').click(); pg.locator('#shopTabs [data-shop="0"]').click(); pg.wait_for_timeout(1300)
    pg.screenshot(path=f'{SHOTS}/08_laoma_bbq.png')
    print('== 3b. 大客户 / 漫画杯套 ==')
    pg.evaluate("__tzz.forceBig()"); pg.wait_for_timeout(1300)
    bg = S(pg, "__tzz.big && {x:__tzz.big.x, y:__tzz.big.y}")
    check(bg is not None, '大客户出现（在线）')
    pg.screenshot(path=f'{SHOTS}/08b_big_customer.png')
    if bg:
        pg.mouse.click(box['x'] + bg['x'], box['y'] + bg['y']); pg.wait_for_timeout(300)
    check(S(pg, "__tzz.state.boostEnd > Date.now() && __tzz.state.bigCustomers >= 1"), '点到大客户 → ×5 持续 30 秒')
    pg.evaluate("(()=>{const s=__tzz.state; __tzz.E.assignCeo(s,'otaku',1); s.shops[1].lv=24; s.coins=1e13; __tzz.switchShop(1); __tzz.setTab('shop');})()"); pg.wait_for_timeout(300)
    close_modals(pg)
    c_b = S(pg, '__tzz.state.coins'); cost = S(pg, '__tzz.E.upgradeCost(1, 24)')
    pg.locator('[data-act="amt"][data-arg="1"]').click(); pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(700)
    pg.screenshot(path=f'{SHOTS}/08c_manga_cup_milestone.png')
    check(S(pg, '__tzz.state.shops[1].lv') == 25 and S(pg, '__tzz.state.coins') > c_b - cost, '漫画杯套：阿宅在奶茶店冲 Lv25 → 分镜特效 + 小红包')
    pg.evaluate("__tzz.E.assignCeo(__tzz.state,'pearl',1); __tzz.persist()"); close_modals(pg)
    print('== 4. 盲盒（16 件不重复，原子保存） ==')
    pg.evaluate("__tzz.state.coins = 5e6"); pg.locator('#bottomNav [data-tab="gacha"]').click(); pg.wait_for_timeout(300)
    pg.screenshot(path=f'{SHOTS}/09_gacha.png')
    c0 = S(pg, '__tzz.state.coins')
    pg.locator('[data-act="draw"]').click(); pg.wait_for_timeout(200)
    s4 = st(pg)  # 动画还没播完，结果已经存好
    saved = json.loads(S(pg, f"localStorage.getItem('{KEY}')"))
    check(len(s4['gacha']['owned']) == 1 and saved['gacha']['owned'] == s4['gacha']['owned'] and abs(saved['coins'] - (c0 - 200000)) < 1e-6 or saved['coins'] < c0, '开盒：扣币+结果+入库已在动画前一起存档')
    pg.reload(); pg.wait_for_timeout(900)
    txt = pg.inner_text('#mpanel') if modal_visible(pg) else ''
    s5 = st(pg)
    check('上次开盒' in txt and s5['gacha']['owned'] == s4['gacha']['owned'], '刷新后只展示已确定的结果，不重抽')
    check(s5['gacha']['draws'] == 1 and s5['coins'] >= saved['coins'] - 1, '刷新后没有重复扣钱（只扣过 1 次）')
    close_modals(pg)
    pg.locator('#bottomNav [data-tab="gacha"]').click(); pg.wait_for_timeout(200)
    for k in range(15):
        pg.evaluate("__tzz.state.coins = Math.max(__tzz.state.coins, 1e6)")
        pg.locator('[data-act="draw"]').click(); pg.wait_for_timeout(950)
        if k == 14: pg.screenshot(path=f'{SHOTS}/10_reveal.png')
        close_modals(pg)
    s6 = st(pg)
    check(len(s6['gacha']['owned']) == 16 and len(set(s6['gacha']['owned'])) == 16, '16 抽集齐、无重复')
    check(pg.locator('button:has-text("已集齐")').count() == 1, '集齐后按钮变「已集齐」')
    r = S(pg, "(()=>{const s=__tzz.state,c=s.coins,r=__tzz.E.gachaDraw(s,.5);return {ok:r.ok,same:s.coins===c,n:s.gacha.owned.length};})()")
    check((not r['ok']) and r['same'] and r['n'] == 16, '集齐后不能再买、不扣金币')
    check(S(pg, "__tzz.E.cardsComplete(__tzz.state)"), '4 张故事卡 → 金牌摊主外观')
    pg.locator('#bottomNav [data-tab="col"]').click(); pg.wait_for_timeout(300)
    pg.locator('[data-act="equip"][data-arg="clothes:c_gold"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="equip"][data-arg="hat:h_gold"]').click(); pg.wait_for_timeout(150)
    check(st(pg)['equip'] == {'clothes':'c_gold','hat':'h_gold'}, '换上金马甲 + 金厨师帽')
    pg.screenshot(path=f'{SHOTS}/11_collection.png')
    rate_a = S(pg, "__tzz.E.baseRate(__tzz.state)"); pg.evaluate("__tzz.state.gacha.owned=[]"); rate_b = S(pg, "__tzz.E.baseRate(__tzz.state)")
    pg.evaluate(f"__tzz.state.gacha.owned={json.dumps(s6['gacha']['owned'])}")
    check(rate_a == rate_b, '收藏品不加产速')
    pg.evaluate("__tzz.switchShop(3); __tzz.setTab('shop')"); pg.wait_for_timeout(1300)
    pg.screenshot(path=f'{SHOTS}/12_tech_77_gold.png')
    print('== 5. 离线收益（50%、封顶、每日双倍、防重复） ==')
    pg.evaluate("__tzz.persist()")
    rate = S(pg, "__tzz.E.baseRate(__tzz.state)")
    pg.close()
    pg2 = ctx.new_page(); hook(pg2, 'p2')
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"""()=>{{const s=JSON.parse(localStorage.getItem('{KEY}'));s.lastSeen=Date.now()-2*3600e3;s.maxSeen=s.lastSeen;s.dailyDoubleDay=null;s.boostEnd=Date.now()+20000;localStorage.setItem('{KEY}',JSON.stringify(s));}}""")
    pg2.goto(URL); pg2.wait_for_timeout(900)
    pend = S(pg2, '__tzz.state.pending')
    check(modal_visible(pg2) and pend and abs(pend['amount'] - rate * 0.5 * 7200) / (rate * 0.5 * 7200) < 0.01, f"离开 2 小时 → 50% = {pend and round(pend['amount'])}（期望 {round(rate*0.5*7200)}，不含大客户×5）")
    check(pg2.locator('#claimDouble').count() == 1, '今日双倍按钮可用')
    pg2.screenshot(path=f'{SHOTS}/13_offline.png')
    c_b = S(pg2, '__tzz.state.coins'); pg2.click('#claimDouble'); pg2.wait_for_timeout(300); c_a = S(pg2, '__tzz.state.coins')
    check(abs((c_a - c_b) - pend['amount'] * 2) / (pend['amount'] * 2) < 0.01, '双倍领取 = ×2')
    saved = json.loads(S(pg2, f"localStorage.getItem('{KEY}')"))
    check(saved['pending'] is None and saved['claimLog'][-1]['id'] == pend['id'], '入账和领取记录同一次存档')
    pg2.reload(); pg2.wait_for_timeout(800)
    check(not modal_visible(pg2) and S(pg2, '__tzz.state.pending') is None, '刷新后不能重复领取')
    # 20 小时：77 在科技公司 → 10 小时封顶；双倍已用
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"""()=>{{const s=JSON.parse(localStorage.getItem('{KEY}'));s.lastSeen=Date.now()-20*3600e3;s.maxSeen=s.lastSeen;localStorage.setItem('{KEY}',JSON.stringify(s));}}""")
    pg2.goto(URL); pg2.wait_for_timeout(900)
    pend = S(pg2, '__tzz.state.pending')
    check(pend and abs(pend['sec'] - 36000) < 2, f"离开 20 小时 → 按 10 小时封顶（麻辣服务器）：{pend and round(pend['sec']/3600,2)}h")
    check(pg2.locator('#claimDouble').count() == 0 and '重置' in pg2.inner_text('#mpanel'), '今日双倍已用 → 只能普通领取，提示 5 点重置')
    pg2.screenshot(path=f'{SHOTS}/14_offline_cap.png')
    pg2.click('#claim'); pg2.wait_for_timeout(300)
    print('== 6. 时间回拨 / 每日重置 / 旧档迁移 ==')
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"""()=>{{const s=JSON.parse(localStorage.getItem('{KEY}'));s.maxSeen=Date.now()+3*3600e3;s.lastSeen=Date.now()-5*3600e3;localStorage.setItem('{KEY}',JSON.stringify(s));}}""")
    pg2.goto(URL); pg2.wait_for_timeout(800)
    check(S(pg2, '__tzz.state.pending') is None and not modal_visible(pg2), '手机时间往回调 → 不发离线收益')
    check(S(pg2, "__tzz.E.dayKey(Date.UTC(2026,9,5,20,59))") == '2026-10-05' and S(pg2, "__tzz.E.dayKey(Date.UTC(2026,9,5,21,0))") == '2026-10-06', '每日双倍 05:00 MYT 切日（不跟手机时区）')
    v1 = {'v':1,'coins':4321,'shops':[{'open':True,'lv':12,'hired':True},{'open':True,'lv':3,'hired':False},{'open':False,'lv':0,'hired':False},{'open':False,'lv':0,'hired':False}],
          'gacha':{'owned':[],'draws':0},'lastSeen':0,'maxSeen':0,'claimLog':[]}
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"(v)=>{{localStorage.clear(); v.lastSeen=Date.now()-10e3; v.maxSeen=v.lastSeen; localStorage.setItem('{KEY}', JSON.stringify(v));}}", v1)
    pg2.goto(URL); pg2.wait_for_timeout(800)
    s7 = st(pg2)
    check(s7['v'] == 2 and s7['shops'][0]['emp'] == 1 and s7['ceos']['pearl']['at'] == 1 and S(pg2, "!!localStorage.getItem('tangzhe-save-bak-v1')"), '旧档 v1 → v2 迁移（伙伴→员工、CEO 就位、留备份）')
    print('== 7. Safari 多标签：只有一个页面能玩 ==')
    pgA = pg2; pgB = ctx.new_page(); hook(pgB, 'pB')
    pgB.goto(URL); pgB.wait_for_timeout(1000)
    check(S(pgA, '__tzz.frozen') and pgA.is_visible('#lockOverlay'), '第二个标签打开 → 第一个标签冻结')
    check(not S(pgB, '__tzz.frozen'), '新标签正常')
    pgA.screenshot(path=f'{SHOTS}/15_multitab_lock.png')
    coinsB = S(pgB, '__tzz.state.coins'); r = S(pgA, "__tzz.persist()")
    check(r is False, '冻结的标签写不了存档')
    print('== 8. 切后台：声音暂停 ==')
    pgB.mouse.click(200, 300); pgB.wait_for_timeout(500)
    a1 = S(pgB, '__tzz.audioState()')
    pgB.evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))"); pgB.wait_for_timeout(400)
    a2 = S(pgB, '__tzz.audioState()')
    pgB.evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'))"); pgB.wait_for_timeout(400)
    a3 = S(pgB, '__tzz.audioState()')
    check(a2 in ('suspended', 'none') and (a1 != 'running' or a2 == 'suspended'), f'切后台声音暂停：{a1} → {a2} → 回来 {a3}')
    ctx.close()

    print('== 9. 各尺寸 iPhone 视口 ==')
    for name in ['iPhone SE', 'iPhone SE (3rd gen)', 'iPhone 13 Mini', 'iPhone 15', 'iPhone 15 Pro Max', 'iPhone 16 Pro Max']:
        c = b.new_context(**p.devices[name]); q = c.new_page(); hook(q, name)
        q.goto(URL); q.evaluate("localStorage.clear()"); q.reload(); q.wait_for_timeout(700); close_modals(q)
        q.evaluate("(()=>{const s=__tzz.state,E=__tzz.E; s.coins=1e8; E.hireEmp(s,0); s.shops[0].lv=12; E.openShop(s,1); E.hireEmp(s,1); __tzz.persist(); __tzz.renderTab();})()"); q.wait_for_timeout(600); close_modals(q)
        m = q.evaluate("""(()=>{const vw=innerWidth,vh=innerHeight,r=s=>document.querySelector(s).getBoundingClientRect();
          const btns=[...document.querySelectorAll('.buy,#bottomNav button,#shopTabs button,.icon-btn')].filter(x=>x.offsetParent);
          return {vw,vh,sw:document.documentElement.scrollWidth, nav:r('#bottomNav').bottom, stage:r('#stage').height, panel:r('#panel').height,
            minBtn:Math.min(...btns.map(x=>Math.min(x.getBoundingClientRect().height, x.getBoundingClientRect().width)))}})()""")
        ok = m['sw'] <= m['vw'] and m['nav'] <= m['vh'] + 1 and m['stage'] >= 140 and m['panel'] >= 110 and m['minBtn'] >= 32
        check(ok, f"{name} {m['vw']}×{m['vh']}: 无横向溢出 {m['sw']}≤{m['vw']}，底栏在屏内，画面 {round(m['stage'])}px，面板 {round(m['panel'])}px，最小按钮 {round(m['minBtn'])}px")
        q.screenshot(path=f"{SHOTS}/vp_{name.replace(' ','_').replace('(','').replace(')','')}.png")
        c.close()
    b.close()
print('\nERRORS:', errs)
bad = [m for ok, m in results if not ok]
print(f'\nRESULT: {len(results) - len(bad)}/{len(results)} passed' + (f'; FAILED: {bad}' if bad else ''))
sys.exit(1 if bad or errs else 0)
