# 躺着也能赚 — 手机端端到端测试（WebKit = iPhone Safari 内核）
# 用法：先在本目录起静态服务（python3 -m http.server 49710），再 .pwvenv/bin/python test_playtest.py [URL]
import sys, json, os
from playwright.sync_api import sync_playwright
URL = sys.argv[1] if len(sys.argv) > 1 else 'http://127.0.0.1:49710/index.html'
KEY = 'tangzhe-save'
SHOTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), '_shots')
os.makedirs(SHOTS, exist_ok=True)
results = []
def check(cond, msg):
    results.append((bool(cond), msg)); print(('  ✓ ' if cond else '  ✗ ') + msg)
def S(pg, expr): return pg.evaluate(expr)
def st(pg): return pg.evaluate("JSON.parse(JSON.stringify(__tzz.state))")
def modal_visible(pg): return pg.evaluate("!document.querySelector('#modal').classList.contains('hidden')")
def close_modals(pg, n=6):
    for _ in range(n):
        if not modal_visible(pg): return
        for sel in ['#mOk', '#pvNo', '#mNo', '#claim']:
            if pg.locator(sel).count():
                pg.locator(sel).first.click(); pg.wait_for_timeout(250); break
        else: return

with sync_playwright() as p:
    b = p.webkit.launch()
    dev = p.devices['iPhone 15']
    ctx = b.new_context(**dev)
    pg = ctx.new_page(); errs = []
    def hook(page, tag):
        page.on('console', lambda m: m.type == 'error' and errs.append(f'{tag} {m.type}: {m.text}'))
        page.on('pageerror', lambda e: errs.append(f'{tag} pageerror: {e}'))
        page.on('response', lambda r: r.status >= 400 and errs.append(f'{tag} {r.status} {r.url}'))
    hook(pg, 'p1')
    print('== 1. 新开局 ==')
    pg.goto(URL); pg.evaluate("localStorage.clear()"); pg.reload(); pg.wait_for_timeout(900)
    check(modal_visible(pg) and '欢迎' in pg.inner_text('#mpanel'), '新玩家看到开场说明')
    pg.screenshot(path=f'{SHOTS}/01_intro.png')
    pg.click('#mOk'); pg.wait_for_timeout(200)
    s0 = st(pg)
    check(s0['v'] == 3 and s0['ceos']['c77']['at'] == 0 and s0['shops'][0]['emp'] == 0, '存档 v3：77 坐镇烧烤摊、员工未雇')
    check(S(pg, "__tzz.E.baseRate(__tzz.state)") == 0, '没员工不自动赚')
    box = pg.locator('#scene').bounding_box()
    for _ in range(25): pg.mouse.click(box['x'] + box['width'] * 0.4, box['y'] + box['height'] * 0.55); pg.wait_for_timeout(25)
    s1 = st(pg); check(s1['taps'] == 25 and s1['coins'] >= 25, f"手点 25 下 → {round(s1['coins'],1)} 金")
    pg.evaluate("__tzz.state.coins = Math.max(__tzz.state.coins, 60)"); pg.wait_for_timeout(300)
    pg.locator('[data-act="hire"]').click(); pg.wait_for_timeout(300)
    check(st(pg)['shops'][0]['emp'] == 1 and S(pg, "__tzz.E.baseRate(__tzz.state)") > 0, '雇阿炭后开始自动赚')
    c_a = S(pg, '__tzz.state.coins'); pg.wait_for_timeout(2100); c_b = S(pg, '__tzz.state.coins')
    check(c_b > c_a, f'在线自动产出 {round(c_a,2)} → {round(c_b,2)}')
    # 店铺 / 员工 / CEO 分开升级
    pg.evaluate("__tzz.state.coins = 1e6"); pg.wait_for_timeout(300)
    pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="emp"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="ceoUp"]').click(); pg.wait_for_timeout(150)
    s2 = st(pg); check(s2['shops'][0]['lv'] == 2 and s2['shops'][0]['emp'] == 2 and s2['ceos']['c77']['lv'] == 2, '店铺 Lv2 / 员工 Lv2 / CEO Lv2 分开升级')
    pg.evaluate("__tzz.state.shops[0].lv = 9; __tzz.renderTab()"); pg.wait_for_timeout(200)
    pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(500)
    check(st(pg)['shops'][0]['lv'] == 10, '冲 Lv10 里程碑')
    pg.screenshot(path=f'{SHOTS}/02_milestone.png')
    print('== 2. 开店 + CEO 解锁 ==')
    pg.locator('#shopTabs [data-shop="1"]').click(); pg.wait_for_timeout(200)
    pg.locator('[data-act="open"]').click(); pg.wait_for_timeout(500)
    check(modal_visible(pg) and '珍珠姐' in pg.inner_text('#mpanel'), '开奶茶店 → 珍珠姐加入弹窗')
    close_modals(pg)
    check(st(pg)['ceos']['pearl']['at'] == 1, '珍珠姐坐镇奶茶店')
    pg.evaluate("""(()=>{const s=__tzz.state, E=__tzz.E; s.coins=1e13; E.hireEmp(s,1); E.openShop(s,2); E.hireEmp(s,2); E.openShop(s,3); s.shops[3].lv=24; __tzz.persist(); __tzz.switchShop(3); __tzz.renderTab();})()""")
    pg.wait_for_timeout(300); close_modals(pg)
    check(not S(pg, "__tzz.E.gachaUnlocked(__tzz.state)"), '科技公司没雇员工前盲盒不开放')
    pg.locator('[data-act="hire"]').click(); pg.wait_for_timeout(400)
    check(modal_visible(pg) and '盲盒' in pg.inner_text('#mpanel'), '雇到科技公司员工 → 盲盒开放弹窗')
    close_modals(pg)
    pg.evaluate("__tzz.state.coins = 1e13"); pg.wait_for_timeout(200)
    pg.locator('[data-act="amt"][data-arg="1"]').click(); pg.wait_for_timeout(100)
    pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(500)
    check(modal_visible(pg) and '火箭老板' in pg.inner_text('#mpanel'), '科技公司 Lv25 → 火箭老板加入')
    close_modals(pg)
    check(st(pg)['ceos']['rocket']['at'] == 3, '火箭老板坐镇科技公司')
    pg.screenshot(path=f'{SHOTS}/03_tech.png')
    print('== 3. 调任预览 ==')
    pg.locator('#bottomNav [data-tab="ceo"]').click(); pg.wait_for_timeout(250)
    stage_ceo = S(pg, "getComputedStyle(document.getElementById('stage')).display")
    compact_ceo = S(pg, "!document.getElementById('compactHead').classList.contains('hidden')")
    check(stage_ceo == 'none' and compact_ceo, 'CEO 页隐藏店景、显示紧凑页头（谁在管哪家店）')
    pg.screenshot(path=f'{SHOTS}/04_ceo_tab.png')
    before = st(pg)
    pg.locator('[data-act="assign"][data-arg="rocket"]').click(); pg.wait_for_timeout(300)
    check(pg.locator('#sheet .pick').count() == 5, '调任选择：4 家店 + 休息')
    pg.screenshot(path=f'{SHOTS}/05_pick.png')
    pg.locator('#sheet [data-pick="0"]').click(); pg.wait_for_timeout(400)
    txt = pg.inner_text('#mpanel')
    check('交换任职预览' in txt and '全街每秒' in txt and '火箭烤炉' in txt and '麻辣服务器' in txt, '预览：每店+全街 调前→调后，列出两个跨行事件')
    check(pg.locator('.pv-table .down').count() >= 2 and pg.locator('.pv-table tr.total .down').count() == 1, '预览：变少的标红（含全街合计）')
    check('8 小时 → 10 小时' in txt, '预览显示离线上限变化')
    check(pg.inner_text('#pvYes') == '交换任职' and pg.locator('.swap-box').count() == 1 and '烧烤摊' in pg.inner_text('.swap-box') and '科技公司' in pg.inner_text('.swap-box') and '/秒' in pg.inner_text('.swap-box'), '目标店有 CEO：按钮「交换任职」+ 两家店 $/s 变化')
    pg.screenshot(path=f'{SHOTS}/06_preview.png')
    pg.click('#pvNo'); pg.wait_for_timeout(250)
    # 涨绿：让珍珠姐先休息，再预览她回奶茶店
    pg.evaluate("__tzz.state.ceos.pearl.at = -1; __tzz.showPreview('pearl', 1)"); pg.wait_for_timeout(300)
    upn = pg.locator('.pv-table .up').count()
    if upn < 2: print('DEBUG', pg.inner_text('#mpanel')[:400])
    check(upn >= 1, '预览：变多的标绿（空缺店派 CEO）')
    pg.click('#pvNo'); pg.wait_for_timeout(200); pg.evaluate("__tzz.state.ceos.pearl.at = 1")
    check(st(pg)['ceos'] == before['ceos'], '「再想想」不改任何安排')
    pg.locator('[data-act="assign"][data-arg="rocket"]').click(); pg.wait_for_timeout(300)
    pg.locator('#sheet [data-pick="0"]').click(); pg.wait_for_timeout(300)
    shops_before = st(pg)['shops']
    pg.click('#pvYes'); pg.wait_for_timeout(600)
    s3 = st(pg)
    check(s3['shops'] == shops_before, '换招牌不重置店铺进度（等级/员工）')
    check(s3['ceos']['rocket']['at'] == 0 and s3['ceos']['c77']['at'] == 3, '确认后火箭老板↔77 互换')
    check(S(pg, "__tzz.E.signOf(__tzz.state,0).name") == '老马烧烤', '招牌换成「老马烧烤」')
    ch = pg.inner_text('#compactHead')
    check('老马烧烤' in ch and '77烧烤店' not in ch, '交换任职后顶部「谁在管哪家店」同步刷新')
    check(modal_visible(pg) and '火箭烤炉' in pg.inner_text('#mpanel') and pg.locator('#mpanel .comic.two .panel4').count() == 2 and '香味先起飞了' in pg.inner_text('#mpanel') and '占位' not in pg.inner_text('#mpanel'), '跨行事件漫画：火箭烤炉（两格定稿）')
    pg.wait_for_timeout(900); pg.screenshot(path=f'{SHOTS}/07_comic.png')
    pg.click('#mOk'); pg.wait_for_timeout(400)
    check(modal_visible(pg) and '麻辣服务器' in pg.inner_text('#mpanel'), '第二个跨行漫画：麻辣服务器')
    close_modals(pg)
    check(S(pg, "__tzz.E.offlineCap(__tzz.state)") == 36000, '77 在科技公司：离线上限 10 小时')
    # 让 77 休息：下方卡片和顶部「谁在管哪家店」要同时显示休息中
    pg.evaluate("__tzz.showPreview('c77', -1)"); pg.wait_for_timeout(300); pg.click('#pvYes'); pg.wait_for_timeout(500); close_modals(pg)
    card77 = pg.evaluate("[...document.querySelectorAll('#compactHead .ch-card')].map(e=>e.innerText).find(t=>t.includes('77'))") or ''
    check(st(pg)['ceos']['c77']['at'] == -1 and '休息中' in card77 and '休息中' in pg.inner_text('#tabBody'), '77 休息后顶部和下方卡片同步显示「休息中」')
    pg.screenshot(path=f'{SHOTS}/07b_rest_sync.png')
    pg.evaluate("__tzz.showPreview('c77', 3)"); pg.wait_for_timeout(300); pg.click('#pvYes'); pg.wait_for_timeout(500); close_modals(pg)
    card77 = pg.evaluate("[...document.querySelectorAll('#compactHead .ch-card')].map(e=>e.innerText).find(t=>t.includes('77'))") or ''
    check(st(pg)['ceos']['c77']['at'] == 3 and '休息中' not in card77, '77 调回科技公司，顶部同步更新')
    print('== 3a. CEO×店铺 任职形象 ==')
    close_modals(pg); pg.evaluate("__tzz.renderTab()"); pg.wait_for_timeout(200)
    g = '.job-gal[data-ceo="c77"]'
    check(pg.locator('.job-gal').count() == 4, 'CEO 页每位已加入 CEO 都有任职形象区')
    check(pg.locator(g + ' .job-chip').count() == 4 and pg.locator(g + ' .job-chip.lock').count() == 0 and '科技公司' in pg.inner_text(g + ' .job-chip.on') and '现任' in pg.inner_text(g + ' .job-chip.on'), '77 默认显示现任科技公司，4 家已开店都能点')
    src0 = pg.get_attribute(g + ' .job-pic img', 'src') or ''
    check('现任形象' in pg.inner_text(g + ' .job-cap') and 'job_c77_tech.webp' in src0 and pg.locator(g + ' .job-wip').count() == 0, '77 现任科技公司：显示 job_c77_tech 大图，不再标「画师赶稿中」')
    m16 = S(pg, "(()=>{const ids=['c77','pearl','otaku','rocket'], sh=['bbq','tea','book','tech'], bad=[]; ids.forEach((id,ci)=>sh.forEach((x,i)=>{const u=__tzz.jobURL(id,i), want = ci===i ? 'art/ceo_'+id+'.webp' : 'art/job_'+id+'_'+x+'.webp'; if(!u.startsWith(want)) bad.push(id+'_'+x+'→'+u);})); return bad;})()")
    check(m16 == [], '16 种任职形象 ID 对应正确（本行 4 张用 ceo_<id>，其余 12 张用 job_<CEO>_<店>）' + (' 错：' + str(m16) if m16 else ''))
    ld = S(pg, "Promise.all(['c77','pearl','otaku','rocket'].flatMap(id=>[0,1,2,3].map(i=>new Promise(r=>{const im=new Image(); im.onload=()=>r(im.naturalWidth>=400?null:id+i+' 太小'); im.onerror=()=>r(id+':'+i+' 加载失败'); im.src=__tzz.jobURL(id,i);})))).then(a=>a.filter(Boolean))")
    check(ld == [], '16 张任职大图都能加载（≥400px）' + (' 错：' + str(ld) if ld else ''))
    pg.screenshot(path=f'{SHOTS}/07c_job_gallery.png')
    pg.locator(g + ' [data-act="jobView"][data-arg="c77:0"]').click(); pg.wait_for_timeout(250)
    src = pg.get_attribute(g + ' .job-pic img', 'src') or ''
    check('烧烤摊' in pg.inner_text(g + ' .job-chip.on') and 'ceo_c77.webp' in src and pg.locator(g + ' .job-wip').count() == 0 and '换店预览' in pg.inner_text(g + ' .job-cap'), '点烧烤摊：切到 77 的本行形象（已有图，不标赶稿）')
    check(st(pg)['ceos']['c77']['at'] == 3, '看别家形象不改任职')
    pg.locator(g + ' .job-pic').click(); pg.wait_for_timeout(300)
    check(modal_visible(pg) and pg.locator('#mpanel .job-big img').count() == 1 and '77 × 烧烤摊' in pg.inner_text('#mpanel'), '点图放大看大图')
    close_modals(pg)
    check(S(pg, "(()=>{delete __tzz.JOB_ART.c77_tech; const u=__tzz.jobURL('c77',3); __tzz.JOB_ART.c77_tech=1; return u;})()").startswith('art/ceo_c77.webp') and S(pg, "__tzz.jobURL('c77',3)").startswith('art/job_c77_tech.webp'), '未登记的组合退回本行图，登记后按 job_<CEO>_<店>.webp 加载')
    for (cid, arg, want) in [('pearl', 'pearl:3', 'job_pearl_tech'), ('otaku', 'otaku:1', 'job_otaku_tea'), ('rocket', 'rocket:0', 'job_rocket_bbq')]:
        gg = f'.job-gal[data-ceo="{cid}"]'; before = st(pg)['ceos'][cid]['at']
        pg.locator(gg + f' [data-act="jobView"][data-arg="{arg}"]').click(); pg.wait_for_timeout(250)
        s2 = pg.get_attribute(gg + ' .job-pic img', 'src') or ''
        nw = S(pg, f"(()=>{{const im=document.querySelector('{gg} .job-pic img'); return im && im.complete ? im.naturalWidth : -1;}})()")
        check(want in s2 and st(pg)['ceos'][cid]['at'] == before, f'{cid} 点 {arg.split(":")[1]} 号店切到 {want}，任职不变')
    pg.screenshot(path=f'{SHOTS}/07d_job_gallery_full.png')
    check(S(pg, "(()=>{const s=__tzz.state.ceos.c77; s.at=2; const v=__tzz.jobShown('c77'); s.at=3; return v;})()") == 2, '调任后默认显示新任职形象')
    check(S(pg, "(()=>{__tzz.state.shops[2].open=false; __tzz.renderTab(); const n=document.querySelectorAll('.job-gal[data-ceo=\"c77\"] .job-chip.lock').length; __tzz.state.shops[2].open=true; __tzz.renderTab(); return n;})()") == 1, '没开的店锁着不能看')
    pg.locator('#bottomNav [data-tab="shop"]').click(); pg.locator('#shopTabs [data-shop="0"]').click(); pg.wait_for_timeout(1300)
    pg.screenshot(path=f'{SHOTS}/08_laoma_bbq.png')
    print('== 3b. 大客户团单 / 漫画杯套 ==')
    pg.evaluate("__tzz.forceBig()"); pg.wait_for_timeout(1400)
    bg = S(pg, "__tzz.order && {x:__tzz.order.x, y:__tzz.order.y, p:__tzz.order.progress, pay:__tzz.order.payout}")
    check(bg is not None and bg['p'] is not None and bg['p'] >= 0, '大客户团单出现（可见进度）')
    pg.screenshot(path=f'{SHOTS}/08b_big_customer.png')
    c_before = S(pg, '__tzz.state.coins'); pay = bg and bg.get('pay') or 0
    if bg:
        pg.mouse.click(box['x'] + bg['x'], box['y'] + bg['y']); pg.wait_for_timeout(200)
        for _ in range(8):
            pg.mouse.click(box['x'] + bg['x'], box['y'] + bg['y']); pg.wait_for_timeout(80)
        pg.wait_for_timeout(400)
    pg.evaluate("(()=>{const o=__tzz.order; if(o){o.progress=1;}})()"); pg.wait_for_timeout(500)
    s_big = st(pg)
    check(s_big['bigCustomers'] >= 1 and S(pg, '__tzz.order') is None, '团单完成后大客户计数 +1，订单清掉')
    check(S(pg, '__tzz.state.coins') >= c_before + pay * 0.95 - 1, '团单收入一次性入账（≈旧 ×5 多出来的部分）')
    check(S(pg, '!(__tzz.state.boostEnd > Date.now())'), '不再有持续 ×5 加成')
    pg.evaluate("(()=>{const s=__tzz.state; __tzz.E.assignCeo(s,'otaku',1); s.shops[1].lv=24; s.coins=1e13; __tzz.switchShop(1); __tzz.setTab('shop');})()"); pg.wait_for_timeout(300)
    close_modals(pg)
    c_b = S(pg, '__tzz.state.coins'); cost = S(pg, '__tzz.E.upgradeCost(1, 24)')
    pg.locator('[data-act="amt"][data-arg="1"]').click(); pg.locator('[data-act="up"]').click(); pg.wait_for_timeout(700)
    pg.screenshot(path=f'{SHOTS}/08c_manga_cup_milestone.png')
    check(S(pg, '__tzz.state.shops[1].lv') == 25 and S(pg, '__tzz.state.coins') > c_b - cost, '漫画杯套：阿宅在奶茶店冲 Lv25 → 分镜特效 + 小红包')
    pg.evaluate("__tzz.E.assignCeo(__tzz.state,'pearl',1); __tzz.persist()"); close_modals(pg)
    print('== 4. 盲盒（36 件不重复：32 普通 + 4 超级，原子保存） ==')
    pg.evaluate("__tzz.state.coins = 5e6"); pg.locator('#bottomNav [data-tab="gacha"]').click(); pg.wait_for_timeout(300)
    pg.screenshot(path=f'{SHOTS}/09_gacha.png')
    c0 = S(pg, '__tzz.state.coins')
    pg.locator('[data-act="draw"]').click(); pg.wait_for_timeout(200)
    s4 = st(pg)  # 动画还没播完，结果已经存好
    saved = json.loads(S(pg, f"localStorage.getItem('{KEY}')"))
    check(len(s4['gacha']['owned']) == 1 and saved['gacha']['owned'] == s4['gacha']['owned'] and abs(saved['coins'] - (c0 - 200000)) < 1e-6 or saved['coins'] < c0, '开盒：扣币+结果+入库已在动画前一起存档')
    pg.reload(); pg.wait_for_timeout(900)
    txt = pg.inner_text('#mpanel') if modal_visible(pg) else ''
    s5 = st(pg)
    check('上次开盒' in txt and s5['gacha']['owned'] == s4['gacha']['owned'], '刷新后只展示已确定的结果，不重抽')
    check(s5['gacha']['draws'] == 1 and s5['coins'] >= saved['coins'] - 1, '刷新后没有重复扣钱（只扣过 1 次）')
    close_modals(pg)
    pg.locator('#bottomNav [data-tab="gacha"]').click(); pg.wait_for_timeout(200)
    txt_g = pg.inner_text('#tabBody')
    check('超级装饰' in txt_g and '保底' in txt_g and '普通收藏' in txt_g, '盲盒页：超级 / 普通概率分开显示 + 保底提示')
    super_shot = False
    for k in range(35):
        pg.evaluate("__tzz.state.coins = Math.max(__tzz.state.coins, 1e6)")
        pg.locator('[data-act="draw"]').click(); pg.wait_for_timeout(950)
        if not super_shot and S(pg, "!!(__tzz.state.gacha.last && __tzz.state.gacha.last.super)"):
            pg.screenshot(path=f'{SHOTS}/10b_super_reveal.png'); super_shot = True
            check('超级装饰' in pg.inner_text('#mpanel'), '抽到超级装饰：专属弹窗')
        if k == 34: pg.screenshot(path=f'{SHOTS}/10_reveal.png')
        close_modals(pg)
    s6 = st(pg)
    check(len(s6['gacha']['owned']) == 36 and len(set(s6['gacha']['owned'])) == 36, '36 抽集齐、无重复')
    pg.screenshot(path=f'{SHOTS}/09b_gacha_full.png', full_page=True)
    check(pg.locator('button:has-text("已集齐")').count() == 1, '集齐后按钮变「已集齐」')
    r = S(pg, "(()=>{const s=__tzz.state,c=s.coins,r=__tzz.E.gachaDraw(s,.5);return {ok:r.ok,same:s.coins===c,n:s.gacha.owned.length};})()")
    check((not r['ok']) and r['same'] and r['n'] == 36, '集齐后不能再买、不扣金币')
    check(S(pg, "__tzz.E.cardsComplete(__tzz.state)"), '8 张故事卡 → 金牌摊主外观')
    pg.locator('#bottomNav [data-tab="col"]').click(); pg.wait_for_timeout(300)
    pg.locator('[data-act="equip"][data-arg="c77:clothes:c_gold"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="equip"][data-arg="c77:hat:h_gold"]').click(); pg.wait_for_timeout(150)
    check(st(pg)['wear']['c77'] == {'clothes':'c_gold','hat':'h_gold'}, '给 77 换上金马甲 + 金厨师帽')
    pg.locator('[data-act="wearWho"][data-arg="pearl"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="equip"][data-arg="pearl:clothes:c_qipao"]').click(); pg.wait_for_timeout(150)
    pg.locator('[data-act="equip"][data-arg="pearl:hat:h_boba"]').click(); pg.wait_for_timeout(150)
    w = st(pg)['wear']
    check(w['pearl'] == {'clothes':'c_qipao','hat':'h_boba'} and w['c77'] == {'clothes':'c_gold','hat':'h_gold'}, '每位 CEO 各穿各的（珍珠姐：旗袍 + 奶茶杯帽）')
    pg.screenshot(path=f'{SHOTS}/11_collection.png')
    ceo_at0 = S(pg, "JSON.stringify(Object.fromEntries(Object.entries(__tzz.state.ceos).map(([k,v])=>[k,v.at])))")
    pg.evaluate("__tzz.E.assignCeo(__tzz.state,'pearl',0); __tzz.persist(); __tzz.switchShop(0); __tzz.setTab('shop')"); pg.wait_for_timeout(600); close_modals(pg)
    check(st(pg)['wear']['pearl']['hat'] == 'h_boba', '换店后穿搭跟着人走')
    txt_s = pg.inner_text('#tabBody')
    check('暴击概率 30%' in txt_s and '暴击倍率 ×5' in txt_s and '熊猫食神' in txt_s, '烧烤摊：熊猫食神 → 暴击概率 30% / 倍率 ×5 分开显示')
    pg.screenshot(path=f'{SHOTS}/16_panda_pearl_bbq.png')
    pg.evaluate("(m)=>{const a=JSON.parse(m); for (const k in a) __tzz.state.ceos[k].at=a[k]; __tzz.persist();}", ceo_at0); close_modals(pg)
    rate_a = S(pg, "__tzz.E.baseRate(__tzz.state)")
    pg.evaluate("__tzz.state.gacha.owned=__tzz.E.SUPER_ITEMS.map(i=>i.id)"); rate_b = S(pg, "__tzz.E.baseRate(__tzz.state)")
    pg.evaluate(f"__tzz.state.gacha.owned={json.dumps(s6['gacha']['owned'])}")
    check(abs(rate_a - rate_b) < 1e-6 * max(1, rate_a), '普通收藏不加产速（只有超级装饰加）')
    # 超级装饰在线效果：直接触发
    pg.evaluate("__tzz.switchShop(1); __tzz.setTab('shop'); __tzz.forceSupers()"); pg.wait_for_timeout(400)
    t1 = pg.inner_text('#tabBody')
    check(S(pg, "__tzz.E.rushActive(__tzz.state,'tea',Date.now())") and '暴击概率 100%' in t1, '珍珠喷泉：连续爆单中，奶茶店手点必暴击')
    pg.screenshot(path=f'{SHOTS}/17_fountain_rush.png')
    pg.evaluate("__tzz.switchShop(3)"); pg.wait_for_timeout(400)
    check(S(pg, "__tzz.E.rushActive(__tzz.state,'tech',Date.now())") and '暴击倍率 ×10' in pg.inner_text('#tabBody'), '人造太阳：超频中，暴击倍率 ×10')
    pg.screenshot(path=f'{SHOTS}/18_sun_overclock.png')
    pg.evaluate("__tzz.switchShop(2)"); pg.wait_for_timeout(400); pg.screenshot(path=f'{SHOTS}/19_portal.png')
    pg.evaluate("__tzz.switchShop(3); __tzz.setTab('shop')"); pg.wait_for_timeout(1300)
    pg.screenshot(path=f'{SHOTS}/12_tech_77_gold.png')
    print('== 5. 离线收益（50%、封顶、每日双倍、防重复） ==')
    pg.evaluate("__tzz.persist()")
    rate = S(pg, "__tzz.E.baseRate(__tzz.state)")
    pg.close()
    pg2 = ctx.new_page(); hook(pg2, 'p2')
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"""()=>{{const s=JSON.parse(localStorage.getItem('{KEY}'));s.lastSeen=Date.now()-2*3600e3;s.maxSeen=s.lastSeen;s.dailyDoubleDay=null;s.boostEnd=Date.now()+20000;localStorage.setItem('{KEY}',JSON.stringify(s));}}""")
    pg2.goto(URL); pg2.wait_for_timeout(900)
    pend = S(pg2, '__tzz.state.pending')
    check(modal_visible(pg2) and pend and abs(pend['amount'] - rate * 0.5 * 7200) / (rate * 0.5 * 7200) < 0.01, f"离开 2 小时 → 50% = {pend and round(pend['amount'])}（期望 {round(rate*0.5*7200)}，不含团单/×5）")
    check(pg2.locator('#claimDouble').count() == 1, '今日双倍按钮可用')
    pg2.screenshot(path=f'{SHOTS}/13_offline.png')
    c_b = S(pg2, '__tzz.state.coins'); pg2.click('#claimDouble'); pg2.wait_for_timeout(300); c_a = S(pg2, '__tzz.state.coins')
    check(abs((c_a - c_b) - pend['amount'] * 2) / (pend['amount'] * 2) < 0.01, '双倍领取 = ×2')
    saved = json.loads(S(pg2, f"localStorage.getItem('{KEY}')"))
    check(saved['pending'] is None and saved['claimLog'][-1]['id'] == pend['id'], '入账和领取记录同一次存档')
    pg2.reload(); pg2.wait_for_timeout(800)
    check(not modal_visible(pg2) and S(pg2, '__tzz.state.pending') is None, '刷新后不能重复领取')
    # 20 小时：77 在科技公司 → 10 小时封顶；双倍已用
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"""()=>{{const s=JSON.parse(localStorage.getItem('{KEY}'));s.lastSeen=Date.now()-20*3600e3;s.maxSeen=s.lastSeen;localStorage.setItem('{KEY}',JSON.stringify(s));}}""")
    pg2.goto(URL); pg2.wait_for_timeout(900)
    pend = S(pg2, '__tzz.state.pending')
    check(pend and abs(pend['sec'] - 36000) < 2, f"离开 20 小时 → 按 10 小时封顶（麻辣服务器）：{pend and round(pend['sec']/3600,2)}h")
    check(pg2.locator('#claimDouble').count() == 0 and '重置' in pg2.inner_text('#mpanel'), '今日双倍已用 → 只能普通领取，提示 5 点重置')
    pg2.screenshot(path=f'{SHOTS}/14_offline_cap.png')
    pg2.click('#claim'); pg2.wait_for_timeout(300)
    print('== 6. 时间回拨 / 每日重置 / 旧档迁移 ==')
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"""()=>{{const s=JSON.parse(localStorage.getItem('{KEY}'));s.maxSeen=Date.now()+3*3600e3;s.lastSeen=Date.now()-5*3600e3;localStorage.setItem('{KEY}',JSON.stringify(s));}}""")
    pg2.goto(URL); pg2.wait_for_timeout(800)
    check(S(pg2, '__tzz.state.pending') is None and not modal_visible(pg2), '手机时间往回调 → 不发离线收益')
    check(S(pg2, "__tzz.E.dayKey(Date.UTC(2026,9,5,20,59))") == '2026-10-05' and S(pg2, "__tzz.E.dayKey(Date.UTC(2026,9,5,21,0))") == '2026-10-06', '每日双倍 05:00 MYT 切日（不跟手机时区）')
    v1 = {'v':1,'coins':4321,'shops':[{'open':True,'lv':12,'hired':True},{'open':True,'lv':3,'hired':False},{'open':False,'lv':0,'hired':False},{'open':False,'lv':0,'hired':False}],
          'gacha':{'owned':[],'draws':0},'lastSeen':0,'maxSeen':0,'claimLog':[]}
    pg2.goto(URL.replace('index.html', 'icon.svg'))
    pg2.evaluate(f"(v)=>{{localStorage.clear(); v.lastSeen=Date.now()-10e3; v.maxSeen=v.lastSeen; localStorage.setItem('{KEY}', JSON.stringify(v));}}", v1)
    pg2.goto(URL); pg2.wait_for_timeout(800)
    s7 = st(pg2)
    check(s7['v'] == 3 and s7['shops'][0]['emp'] == 1 and s7['ceos']['pearl']['at'] == 1 and S(pg2, "!!localStorage.getItem('tangzhe-save-bak-v1')"), '旧档 v1 → v3 迁移（伙伴→员工、CEO 就位、留备份）')
    print('== 7. Safari 多标签：只有一个页面能玩 ==')
    pgA = pg2; pgB = ctx.new_page(); hook(pgB, 'pB')
    pgB.goto(URL); pgB.wait_for_timeout(1000)
    check(S(pgA, '__tzz.frozen') and pgA.is_visible('#lockOverlay'), '第二个标签打开 → 第一个标签冻结')
    check(not S(pgB, '__tzz.frozen'), '新标签正常')
    pgA.screenshot(path=f'{SHOTS}/15_multitab_lock.png')
    coinsB = S(pgB, '__tzz.state.coins'); r = S(pgA, "__tzz.persist()")
    check(r is False, '冻结的标签写不了存档')
    print('== 8. 切后台：声音暂停 ==')
    pgB.mouse.click(200, 300); pgB.wait_for_timeout(500)
    a1 = S(pgB, '__tzz.audioState()')
    pgB.evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))"); pgB.wait_for_timeout(400)
    a2 = S(pgB, '__tzz.audioState()')
    pgB.evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'))"); pgB.wait_for_timeout(400)
    a3 = S(pgB, '__tzz.audioState()')
    check(a2 in ('suspended', 'none') and (a1 != 'running' or a2 == 'suspended'), f'切后台声音暂停：{a1} → {a2} → 回来 {a3}')
    ctx.close()

    print('== 8b. CEO 生活篇：经营 → 家宅 → 商城（翻页 / 买 / 拖 / 转 / 收回 / 撤销） ==')
    hc = b.new_context(**dev); hp = hc.new_page(); hook(hp, 'home')
    hp.goto(URL); hp.evaluate("localStorage.clear()"); hp.reload(); hp.wait_for_timeout(900); close_modals(hp)
    vv = S(hp, "fetch('version.json?t='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(j=>[j.v, document.querySelector('script[src^=\"app.js\"]').getAttribute('src'), document.querySelector('script[src^=\"economy.js\"]').getAttribute('src'), document.querySelector('link[href^=\"style.css\"]').getAttribute('href')])")
    check(vv == ['10', 'app.js?v=10', 'economy.js?v=10', 'style.css?v=10'], f'缓存号统一 v10：{vv}')
    hp.evaluate("__tzz.state.coins = 1e6; __tzz.persist()")
    check(S(hp, "__tzz.E.onlineRate(__tzz.state, Date.now())") == 0, '（测试前提）没雇员工 → 每秒 0，金币只会被买东西改变')
    hp.locator('#bottomNav [data-tab="home"]').click(); hp.wait_for_timeout(450)
    check(S(hp, "document.getElementById('app').dataset.tab") == 'home' and S(hp, "getComputedStyle(document.getElementById('stage')).display") == 'none' and hp.locator('#room').count() == 1, '底栏「家宅」→ 翻到家宅页（店景隐藏、出现房间）')
    check(hp.locator('.book-tabs button').count() == 3 and '经营' in hp.inner_text('.book-tabs') and '商城' in hp.inner_text('.book-tabs'), '家宅页顶部翻页签：经营 / 家宅 / 商城')
    check(hp.locator('.home-who .who').count() == 4 and hp.locator('.home-who .who.locked').count() == 3 and S(hp, "__tzz.homeWho") == 'c77', 'CEO 切换：77 能进，其余 3 位锁着')
    check('小屋' in hp.inner_text('.home-card') and '6×4' in hp.inner_text('.home-card') and S(hp, "getComputedStyle(document.getElementById('room')).getPropertyValue('--cols').trim()") == '6', '77 的小屋：6×4 格')
    hp.locator('.home-who [data-arg="pearl"]').click(); hp.wait_for_timeout(250)
    check('还没开放' in hp.inner_text('#tabBody') and hp.locator('#room').count() == 0, '点锁着的珍珠姐：显示「家还没开放」')
    hp.locator('.home-who [data-arg="c77"]').click(); hp.wait_for_timeout(200)
    # 商城
    hp.locator('.book-tabs [data-arg="mall"]').click(); hp.wait_for_timeout(450)
    names = S(hp, "[...document.querySelectorAll('.mall-card .name')].map(e=>e.firstChild.textContent.trim())")
    check(hp.locator('.mall-card').count() == 12 and all(n in names for n in ['床','沙发','桌子','台灯','地毯','绿植','书架','电视','冰箱','衣柜','挂画','猫窝']), f'商城 12 件家具：{"/".join(names)}')
    check(S(hp, "[...document.querySelectorAll('.mall-card')].every(c=>c.querySelector('[data-act=homeBuy] small') && /豪华 \\+\\d+/.test(c.innerText) && /占地 \\d×\\d/.test(c.innerText))"), '每件都标价格 / 豪华度 / 占地')
    check('余额' in hp.inner_text('.mall-head') and '100.0万' in hp.inner_text('.mall-head'), '商城顶部显示余额')
    c0 = S(hp, '__tzz.state.coins')
    hp.locator('[data-act="homeBuy"][data-arg="furn_bed"]').click(); hp.wait_for_timeout(300)
    mt = hp.inner_text('#mpanel')
    check(modal_visible(hp) and '价格' in mt and '12,000' in mt and '当前余额' in mt and '100.0万' in mt and '买后余额' in mt, '买之前先看价格 + 当前余额 + 买后余额')
    hp.click('#mNo'); hp.wait_for_timeout(200)
    check(S(hp, '__tzz.state.coins') == c0 and not S(hp, "__tzz.state.furnInv.furn_bed"), '「再想想」不扣钱、不进仓库')
    hp.locator('[data-act="homeBuy"][data-arg="furn_bed"]').click(); hp.wait_for_timeout(250); hp.click('#hbYes'); hp.wait_for_timeout(300)
    saved = json.loads(S(hp, f"localStorage.getItem('{KEY}')"))
    check(S(hp, '__tzz.state.coins') == c0 - 12000 and S(hp, "__tzz.state.furnInv.furn_bed") == 1 and saved['furnInv'].get('furn_bed') == 1 and saved['coins'] == c0 - 12000, '买床：扣 12,000 进仓库，并且已存档')
    hp.evaluate("__tzz.state.coins = 100"); hp.locator('[data-act="homeBuy"][data-arg="furn_tv"]').click(); hp.wait_for_timeout(250)
    check(S(hp, "document.getElementById('hbYes').disabled") and '还差' in hp.inner_text('#mpanel'), '钱不够：确认按钮灰掉、显示还差多少')
    hp.click('#mNo'); hp.wait_for_timeout(150)
    check(S(hp, '__tzz.state.coins') == 100 and not S(hp, "__tzz.state.furnInv.furn_tv"), '钱不够买不了，不扣钱')
    hp.evaluate(f"__tzz.state.coins = {c0 - 12000}; __tzz.persist()")
    for fid in ['furn_sofa', 'furn_rug', 'furn_plant', 'furn_lamp', 'furn_painting']:
        hp.locator(f'[data-act="homeBuy"][data-arg="{fid}"]').click(); hp.wait_for_timeout(200); hp.click('#hbYes'); hp.wait_for_timeout(200)
    hp.wait_for_timeout(2200); hp.evaluate("document.getElementById('panel').scrollTop = 0"); hp.wait_for_timeout(200)
    hp.screenshot(path=f'{SHOTS}/mall_v10.png')
    coins_room = S(hp, '__tzz.state.coins')
    # 回家宅：拖进房间
    hp.locator('.book-tabs [data-arg="room"]').click(); hp.wait_for_timeout(500)
    check(hp.locator('.inv-item').count() == 6, '家宅仓库里有 6 种刚买的家具')
    def fbox(): return hp.locator('#roomFloor').bounding_box()
    def view():  # 仓库条贴到面板底部：房间地板 + 仓库同屏（真机上拖到面板边缘也会自动滚）
        hp.evaluate("(document.querySelector('.inv-strip')||document.getElementById('room')).scrollIntoView({block:'end'})"); hp.wait_for_timeout(60)
        f = fbox(); return f, f['width'] / 6, f['height'] / 4
    def drag(sel, gx, gy, mid=None):  # gx/gy：目标指针位置（格子单位，相对地板左上角）
        f, w, h = view(); a = hp.locator(sel).bounding_box(); hp.mouse.move(a['x'] + a['width'] / 2, a['y'] + a['height'] / 2); hp.mouse.down()
        hp.mouse.move(f['x'] + gx * w, f['y'] + gy * h, steps=10); hp.wait_for_timeout(80)
        if mid: mid()
        hp.mouse.up(); hp.wait_for_timeout(300)
    def home(): return S(hp, "JSON.parse(JSON.stringify(__tzz.state.homes.c77))")
    def item(fid): return next((p for p in home()['placed'] if p['fid'] == fid), None)
    fb, cw, ch = view()
    seen = {}
    def mid_ok():
        seen['hl'] = S(hp, "document.getElementById('roomHl').className"); seen['scroll'] = S(hp, "document.getElementById('panel').scrollTop"); seen['ghost'] = hp.locator('.drag-ghost').count()
    sc0 = S(hp, "document.getElementById('panel').scrollTop")
    drag('.inv-item[data-fid="furn_bed"]', 1, 2.5, mid_ok)
    bed = item('furn_bed')
    check(seen.get('ghost') == 1 and 'ok' in (seen.get('hl') or ''), f"拖动中：跟手的家具 + 绿色可放高亮（{seen.get('hl')}）")
    check(bed is not None and (bed['x'], bed['y'], bed['rot']) == (0, 1, 0) and not S(hp, "__tzz.state.furnInv.furn_bed"), f'从仓库拖床进房间，吸附到格子 (0,1)：{bed}')
    ta = S(hp, "[getComputedStyle(document.querySelector('.inv-item')).touchAction, getComputedStyle(document.getElementById('roomFloor')).touchAction, getComputedStyle(document.querySelector('#roomFloor .furn')).touchAction]")
    check(seen.get('scroll') == sc0 and ta == ['pan-x', 'none', 'none'], f'拖动时页面不跟着上下滚（仓库条只许横滑 / 房间和家具 touch-action:none）：{ta}，滚动 {sc0}→{seen.get("scroll")}')
    view(); st0 = S(hp, "document.getElementById('panel').scrollTop"); pr = hp.locator('#panel').bounding_box(); n0 = len(home()['placed'])
    a = hp.locator('.inv-item').first.bounding_box(); hp.mouse.move(a['x'] + a['width'] / 2, a['y'] + a['height'] / 2); hp.mouse.down()
    hp.mouse.move(pr['x'] + pr['width'] / 2, pr['y'] + 6, steps=12); hp.wait_for_timeout(700)
    st1 = S(hp, "document.getElementById('panel').scrollTop"); hp.mouse.up(); hp.wait_for_timeout(300)
    check(st0 > 0 and st1 < st0 and len(home()['placed']) == n0, f'拖到面板上沿：面板自动往上滚（{st0} → {st1}），松在房间外不摆')
    seen.clear()
    drag('.inv-item[data-fid="furn_sofa"]', 1.5, 1.5, mid_ok)
    check('bad' in (seen.get('hl') or '') and item('furn_sofa') is None and S(hp, "__tzz.state.furnInv.furn_sofa") == 1, f"拖到床上：红色高亮，松手不放、留在仓库（{seen.get('hl')}）")
    drag('.inv-item[data-fid="furn_sofa"]', 3, 5.6)
    check(item('furn_sofa') is None, '拖出房间外：不放')
    drag('.inv-item[data-fid="furn_sofa"]', 4.5, 3.5)
    sofa = item('furn_sofa'); check(sofa and (sofa['x'], sofa['y']) == (3, 3), f'沙发放到 (3,3)：{sofa}')
    # 拖已摆的家具换位置
    drag(f'#roomFloor .furn[data-uid="{sofa["uid"]}"]', 4.5, 2.5)
    s2 = item('furn_sofa'); check(s2['x'] == 3 and s2['y'] == 2, f'拖动已摆好的沙发 → 吸附到 (3,2)：{s2}')
    drag(f'#roomFloor .furn[data-uid="{sofa["uid"]}"]', 2, 2.5)
    check(item('furn_sofa')['x'] == 3, '拖去和床重叠：弹回原位')
    # 点选 → 旋转 / 收回 / 撤销
    hp.locator(f'#roomFloor .furn[data-uid="{bed["uid"]}"]').click(); hp.wait_for_timeout(250)
    check(S(hp, "__tzz.homeSel") == bed['uid'] and hp.locator('[data-act="homeRot"]').count() == 1 and hp.locator('[data-act="homeStore"]').count() == 1, '点一下床：选中，出现「旋转 / 收回」')
    hp.locator('[data-act="homeRot"]').click(); hp.wait_for_timeout(250)
    b1 = item('furn_bed')
    check(b1['rot'] == 1 and S(hp, f"__tzz.E.canPlace(__tzz.state,'c77','furn_bed',{b1['x']},{b1['y']},1,'{bed['uid']}').ok") and S(hp, "(()=>{const e=document.querySelector('#roomFloor .furn[data-fid=furn_bed]');return Math.round(e.offsetWidth/e.offsetHeight*10)/10})()") == round(3 * cw / (2 * ch), 1), f'旋转 90°：2×3 → 3×2，仍放得下（{b1}）')
    lux_txt = hp.inner_text('#homeLux'); lux = S(hp, "__tzz.E.homeLuxury(__tzz.state,'c77')")
    check(lux_txt == str(lux) and lux == 15 + 12, f'家宅页显示豪华度 {lux_txt}（床 15 + 沙发 12 + 小屋 0）')
    hp.locator('[data-act="homeStore"]').click(); hp.wait_for_timeout(250)
    check(item('furn_bed') is None and S(hp, "__tzz.state.furnInv.furn_bed") == 1 and S(hp, "__tzz.homeSel") is None, '收回：床回到仓库')
    hp.locator('[data-act="homeUndo"]').click(); hp.wait_for_timeout(250)
    b2 = item('furn_bed'); check(b2 and b2['rot'] == 1 and (b2['x'], b2['y']) == (b1['x'], b1['y']) and not S(hp, "__tzz.state.furnInv.furn_bed"), '撤销收回：床回到原位（还是转过的方向）')
    hp.locator('[data-act="homeUndo"]').click(); hp.wait_for_timeout(250)
    check(item('furn_bed')['rot'] == 0, '再撤销：旋转也撤回')
    hp.locator('[data-act="homeUndo"]').click(); hp.wait_for_timeout(250)
    check(item('furn_sofa')['y'] == 3, '再撤销：沙发移动撤回 (3,3)')
    check(S(hp, '__tzz.state.coins') == coins_room, f'摆放 / 移动 / 旋转 / 收回 / 撤销：金币一分没动（{coins_room}）')
    # 轻点仓库 = 自动找空位；地毯能垫在床下；挂画只能靠后墙
    hp.locator('.inv-item[data-fid="furn_plant"]').click(); hp.wait_for_timeout(250)
    check(item('furn_plant') is not None, '轻点仓库里的绿植：自动找空位摆上')
    drag('.inv-item[data-fid="furn_rug"]', 1.5, 2)
    check(item('furn_rug') is not None, '地毯可以垫在床下面')
    drag('.inv-item[data-fid="furn_painting"]', 4, 2.5)
    check(item('furn_painting') is None, '挂画拖到房间中间：不行（要靠后墙）')
    drag('.inv-item[data-fid="furn_painting"]', 4, 0.5)
    check(item('furn_painting') is not None and item('furn_painting')['y'] == 0, '挂画靠后墙：可以')
    hp.locator('.inv-item[data-fid="furn_lamp"]').click(); hp.wait_for_timeout(250)
    check(S(hp, '__tzz.state.coins') == coins_room, '摆完一屋子家具，金币还是没变')
    view(); hp.locator('#roomFloor .furn[data-fid="furn_sofa"]').click(); hp.wait_for_timeout(2200)
    view(); hp.wait_for_timeout(200)
    hp.screenshot(path=f'{SHOTS}/home_v10.png')
    # 四位 CEO 的 Lv1 底图都登记了，且原图是 1200×1200
    hl = S(hp, "Promise.all(['c77','pearl','otaku','rocket'].map(id=>new Promise(r=>{ if(!__tzz.HOME_ART[id+'_1']) return r(id+' 没登记'); const im=new Image(); im.onload=()=>r(im.naturalWidth===1200&&im.naturalHeight===1200?null:id+' 尺寸 '+im.naturalWidth+'×'+im.naturalHeight); im.onerror=()=>r(id+' 加载失败'); im.src='art/home_'+id+'_1.webp';}))).then(a=>a.filter(Boolean))")
    check(hl == [], f'四位 CEO 的 Lv1 家宅底图都登记且是 1200×1200 {hl}')
    # 存档往返
    h_before = home(); inv_before = S(hp, "JSON.parse(JSON.stringify(__tzz.state.furnInv))")
    hp.reload(); hp.wait_for_timeout(900); close_modals(hp)
    check(S(hp, "JSON.parse(JSON.stringify(__tzz.state.homes.c77))") == h_before and S(hp, "JSON.parse(JSON.stringify(__tzz.state.furnInv))") == inv_before, '刷新后家具位置 / 仓库原样读回')
    # 升级房子
    hp.locator('#bottomNav [data-tab="home"]').click(); hp.wait_for_timeout(450)
    hp.locator('[data-act="homeUp"]').click(); hp.wait_for_timeout(250)
    mt = hp.inner_text('#mpanel')
    check('小屋 → 公寓' in mt and '8×5' in mt and '80,000' in mt and '当前余额' in mt, '升级前看价格 80,000 + 余额 + 新格子 8×5')
    cu = S(hp, '__tzz.state.coins'); hp.click('#huYes'); hp.wait_for_timeout(400)
    check(S(hp, "__tzz.state.homes.c77.lv") == 2 and S(hp, '__tzz.state.coins') == cu - 80000 and S(hp, "getComputedStyle(document.getElementById('room')).getPropertyValue('--cols').trim()") == '8' and S(hp, "document.getElementById('room').dataset.tier") == 'apt', '升级公寓：扣 80,000，房间变 8×5、换公寓样式')
    check(home()['placed'] == h_before['placed'], '升级后家具原位保留')
    hp.wait_for_timeout(700); hp.screenshot(path=f'{SHOTS}/home_v10_apt.png')
    # 翻回经营：店景回来、画布尺寸正常、还能点
    hp.locator('.book-tabs [data-arg="shop"]').click(); hp.wait_for_timeout(600)
    sz = S(hp, "(()=>{const r=document.getElementById('scene').getBoundingClientRect(), c=__tzz.canvasSize; return {tab:document.getElementById('app').dataset.tab, disp:getComputedStyle(document.getElementById('stage')).display, rw:r.width, rh:r.height, W:c.W, H:c.H, tabs:getComputedStyle(document.getElementById('shopTabs')).display}})()")
    check(sz['tab'] == 'shop' and sz['disp'] != 'none' and sz['tabs'] != 'none' and sz['rh'] > 100 and abs(sz['W'] - sz['rw']) < 2 and abs(sz['H'] - sz['rh']) < 2, f'翻回经营：店景 / 店铺签回来，画布重新量尺寸 {round(sz["W"])}×{round(sz["H"])}')
    t0 = S(hp, '__tzz.state.taps'); bx = hp.locator('#scene').bounding_box(); hp.mouse.click(bx['x'] + bx['width'] * 0.4, bx['y'] + bx['height'] * 0.55); hp.wait_for_timeout(200)
    check(S(hp, '__tzz.state.taps') == t0 + 1, '回到经营后点店铺照常赚钱')
    hp.locator('#bottomNav [data-tab="home"]').click(); hp.wait_for_timeout(300); hp.locator('#bottomNav [data-tab="ceo"]').click(); hp.wait_for_timeout(300); hp.locator('#bottomNav [data-tab="shop"]').click(); hp.wait_for_timeout(500)
    check(S(hp, "getComputedStyle(document.getElementById('stage')).display") != 'none' and S(hp, "__tzz.canvasSize.H") > 100, '家宅 → CEO → 经营：店景正常')
    # 调任不影响家宅
    hp.evaluate("(()=>{const s=__tzz.state,E=__tzz.E; s.coins=1e7; E.openShop(s,1); __tzz.persist();})()"); hp.wait_for_timeout(300); close_modals(hp)
    hb = home(); hp.evaluate("__tzz.E.assignCeo(__tzz.state,'c77',1); __tzz.persist()")
    check(home() == hb and S(hp, "__tzz.E.homeOpen(__tzz.state,'pearl')"), '开奶茶店 → 珍珠姐的家解锁；77 调任不影响 77 的家')
    hc.close()
    # 旧档（v3，还没有家宅）→ 自动补每人一间空小屋
    hc = b.new_context(**dev); hp = hc.new_page(); hook(hp, 'home-old')
    hp.goto(URL.replace('index.html', 'icon.svg'))
    hp.evaluate(f"()=>{{localStorage.clear(); const s={{v:3,rev:5,coins:777,totalEarned:777,shops:[{{open:true,lv:4,emp:1}},{{open:false,lv:0,emp:0}},{{open:false,lv:0,emp:0}},{{open:false,lv:0,emp:0}}],ceos:{{c77:{{unlocked:true,lv:2,at:0}}}},gacha:{{owned:[],draws:0,pity:0,last:null}},claimLog:[],lastSeen:Date.now()-5000,maxSeen:Date.now()-5000,created:Date.now()-1e6}}; localStorage.setItem('{KEY}', JSON.stringify(s));}}")
    hp.goto(URL); hp.wait_for_timeout(900); close_modals(hp)
    so = st(hp)
    check(all(so['homes'][c]['lv'] == 1 and so['homes'][c]['placed'] == [] for c in ['c77', 'pearl', 'otaku', 'rocket']) and so['furnInv'] == {} and so['shops'][0]['lv'] == 4 and so['coins'] >= 777, '旧档（无家宅）读入：每人补一间空小屋，原进度不变')
    hp.locator('#bottomNav [data-tab="home"]').click(); hp.wait_for_timeout(400)
    check(hp.locator('#room').count() == 1, '旧档玩家也能直接进家宅')
    hc.close()

    print('== 8c. 高家具：书架 / 衣柜（占地 2×1，图往上伸到墙上，底脚对齐，按底脚排前后） ==')
    hc = b.new_context(**dev); hp = hc.new_page(); hook(hp, 'tall')
    hp.goto(URL); hp.evaluate("localStorage.clear()"); hp.reload(); hp.wait_for_timeout(900); close_modals(hp)
    ld = S(hp, "Promise.all(['bookshelf','wardrobe'].map(n=>new Promise(r=>{ if(!__tzz.FURN_ART[n]||!__tzz.FURN_UP[n]) return r(n+' 没登记'); const im=new Image(); im.onload=()=>r(im.naturalWidth===400&&im.naturalHeight===600?null:n+' '+im.naturalWidth+'×'+im.naturalHeight); im.onerror=()=>r(n+' 加载失败'); im.src='art/furn_'+n+'.webp';}))).then(a=>a.filter(Boolean))")
    check(ld == [], f'书架 / 衣柜图登记了，都是 400×600 {ld}')
    hp.evaluate("(()=>{const s=__tzz.state,E=__tzz.E; s.coins=1e6; ['furn_bookshelf','furn_wardrobe','furn_lamp','furn_plant'].forEach(f=>E.buyFurniture(s,f)); E.placeItem(s,'c77','furn_lamp',4,0,0); E.placeItem(s,'c77','furn_bookshelf',3,1,0); __tzz.persist();})()")
    hp.locator('#bottomNav [data-tab="home"]').click(); hp.wait_for_timeout(500); close_modals(hp)
    def tview():
        hp.evaluate("(document.querySelector('.inv-strip')||document.getElementById('room')).scrollIntoView({block:'end'})"); hp.wait_for_timeout(60)
        f = hp.locator('#roomFloor').bounding_box(); return f, f['width'] / 6, f['height'] / 4
    def tdrag(sel, gx, gy):
        f, w, h = tview(); a = hp.locator(sel).bounding_box(); hp.mouse.move(a['x'] + a['width'] / 2, a['y'] + a['height'] / 2); hp.mouse.down()
        hp.mouse.move(f['x'] + gx * w, f['y'] + gy * h, steps=10); hp.wait_for_timeout(80); hp.mouse.up(); hp.wait_for_timeout(300)
    def titem(fid): return next((p for p in S(hp, "JSON.parse(JSON.stringify(__tzz.state.homes.c77.placed))") if p['fid'] == fid), None)
    def geo(fid): return S(hp, f"(()=>{{const e=document.querySelector('#roomFloor .furn[data-fid={fid}]'), i=e&&e.querySelector('img'); if(!e||!i) return null; const a=e.getBoundingClientRect(), b=i.getBoundingClientRect(), r=document.getElementById('room').getBoundingClientRect(); return {{eT:a.top,eB:a.bottom,eL:a.left,eR:a.right,eH:a.height,iT:b.top,iB:b.bottom,iL:b.left,iR:b.right,iH:b.height,iW:b.width,rT:r.top,ov:getComputedStyle(e).overflow,tall:e.classList.contains('tall'),tf:getComputedStyle(i.parentNode).transform}}}})()")
    tdrag('.inv-item[data-fid="furn_wardrobe"]', 1, 0.5)
    w0 = titem('furn_wardrobe'); f, cw, ch = tview(); g = geo('furn_wardrobe')
    check(w0 and (w0['x'], w0['y'], w0['rot']) == (0, 0, 0), f'从仓库拖衣柜靠后墙：吸附到 (0,0) {w0}')
    check(g and g['tall'] and g['ov'] == 'visible' and abs(g['eH'] - ch) < 1.5, f'衣柜占地只有 1 排格子（{round(g["eH"],1)} ≈ 格高 {round(ch,1)}），图可以伸出占地框')
    check(g and abs(g['iB'] - g['eB']) < 1.5 and abs(g['iH'] - 3 * ch) < 2 and abs(g['iW'] - 2 * cw) < 2, f'衣柜图 2 格宽 × 3 格高，底边贴着占地底边（图底 {round(g["iB"],1)} / 占地底 {round(g["eB"],1)}）')
    check(g and g['iT'] >= g['rT'] - 0.5 and abs(g['iT'] - (f['y'] - 2 * ch)) < 6, f'靠墙那排：图往上正好盖满两格高的后墙，没被房间顶边裁掉（图顶 {round(g["iT"],1)}，房间顶 {round(g["rT"],1)}）')
    order = S(hp, "[...document.querySelectorAll('#roomFloor .furn')].map(e=>e.dataset.fid)")
    check(order.index('furn_lamp') < order.index('furn_bookshelf') and order.index('furn_wardrobe') < order.index('furn_bookshelf'), f'前后遮挡按底脚排：第 2 排的书架画在第 1 排的台灯 / 衣柜前面 {order}')
    sel = S(hp, "(()=>{const e=document.querySelector('#roomFloor .furn.sel'); return e&&[e.dataset.fid, getComputedStyle(e).outlineStyle, getComputedStyle(e.querySelector('.fn')).display]})()")
    check(sel and sel[0] == 'furn_wardrobe' and sel[1] != 'none' and sel[2] != 'none', f'摆下的衣柜自动选中：红框只框出脚下的占地范围、显示名字 {sel}')
    tdrag('#roomFloor .furn[data-fid="furn_wardrobe"]', 1, 3.5)
    w1 = titem('furn_wardrobe'); g = geo('furn_wardrobe')
    check(w1 and (w1['x'], w1['y']) == (0, 3) and g and abs(g['iB'] - g['eB']) < 1.5 and abs(g['iH'] - 3 * ch) < 2, f'拖动衣柜到最前排 (0,3)：图跟着走，底脚还是贴着占地底边 {w1}')
    tdrag('#roomFloor .furn[data-fid="furn_wardrobe"]', 4, 1.5)
    check(titem('furn_wardrobe')['y'] == 3, '衣柜拖去和书架重叠：弹回原位')
    hp.locator('#roomFloor .furn[data-fid="furn_bookshelf"]').click(); hp.wait_for_timeout(250); hp.locator('[data-act="homeRot"]').click(); hp.wait_for_timeout(300)
    bk = titem('furn_bookshelf'); g = geo('furn_bookshelf')
    check(bk and bk['rot'] == 1 and g and 'matrix' not in g['tf'] and abs(g['iB'] - g['eB']) < 1.5 and abs(g['iW'] - cw) < 2 and abs(g['iH'] - 1.5 * cw) < 2 and g['iT'] >= g['eT'] - 0.5, f'书架转 90°（占地 1×2）：图保持竖直不躺倒，缩成 1 格宽、底脚对齐、不超出占地 {bk}')
    hp.locator('.book-tabs [data-arg="mall"]').click(); hp.wait_for_timeout(400)
    mi = S(hp, "['furn_bookshelf','furn_wardrobe'].map(f=>{const c=document.querySelector('.mall-card[data-fid='+f+'] .furn-ico'), i=c&&c.querySelector('img'); if(!i) return false; const a=c.getBoundingClientRect(), b=i.getBoundingClientRect(); return b.top>=a.top-1&&b.bottom<=a.bottom+1&&b.height>0})")
    check(mi == [True, True], f'商城里书架 / 衣柜的小图在方框内完整显示 {mi}')
    hp.locator('.book-tabs [data-arg="room"]').click(); hp.wait_for_timeout(400)
    hp.locator('#roomFloor .furn[data-fid="furn_bookshelf"]').click(); hp.wait_for_timeout(250); hp.locator('[data-act="homeRot"]').click(); hp.wait_for_timeout(300)
    hp.evaluate("(()=>{const s=__tzz.state,E=__tzz.E; E.placeItem(s,'c77','furn_plant',2,0,0); __tzz.persist(); __tzz.renderTab();})()"); hp.wait_for_timeout(300)
    tview(); hp.wait_for_timeout(1200); hp.locator('#room').screenshot(path=f'{SHOTS}/home_tall.png')
    hc.close()

    print('== 9. 各尺寸 iPhone 视口 ==')
    for name in ['iPhone SE', 'iPhone SE (3rd gen)', 'iPhone 13 Mini', 'iPhone 15', 'iPhone 15 Pro Max', 'iPhone 16 Pro Max']:
        c = b.new_context(**p.devices[name]); q = c.new_page(); hook(q, name)
        q.goto(URL); q.evaluate("localStorage.clear()"); q.reload(); q.wait_for_timeout(700); close_modals(q)
        q.evaluate("(()=>{const s=__tzz.state,E=__tzz.E; s.coins=1e8; E.hireEmp(s,0); s.shops[0].lv=12; E.openShop(s,1); E.hireEmp(s,1); __tzz.persist(); __tzz.renderTab();})()"); q.wait_for_timeout(600); close_modals(q)
        m = q.evaluate("""(()=>{const vw=innerWidth,vh=innerHeight,r=s=>document.querySelector(s).getBoundingClientRect();
          const btns=[...document.querySelectorAll('.buy,#bottomNav button,#shopTabs button,.icon-btn')].filter(x=>x.offsetParent);
          return {vw,vh,sw:document.documentElement.scrollWidth, nav:r('#bottomNav').bottom, stage:r('#stage').height, panel:r('#panel').height,
            minBtn:Math.min(...btns.map(x=>Math.min(x.getBoundingClientRect().height, x.getBoundingClientRect().width)))}})()""")
        ok = m['sw'] <= m['vw'] and m['nav'] <= m['vh'] + 1 and m['stage'] >= 140 and m['panel'] >= 110 and m['minBtn'] >= 32
        check(ok, f"{name} {m['vw']}×{m['vh']}: 无横向溢出 {m['sw']}≤{m['vw']}，底栏在屏内，画面 {round(m['stage'])}px，面板 {round(m['panel'])}px，最小按钮 {round(m['minBtn'])}px")
        q.screenshot(path=f"{SHOTS}/vp_{name.replace(' ','_').replace('(','').replace(')','')}.png")
        c.close()
    b.close()
print('\nERRORS:', errs)
bad = [m for ok, m in results if not ok]
print(f'\nRESULT: {len(results) - len(bad)}/{len(results)} passed' + (f'; FAILED: {bad}' if bad else ''))
sys.exit(1 if bad or errs else 0)
