const base=process.env.TD_TEST_BASE||'http://127.0.0.1:8883';
import fs from 'node:fs';import assert from 'node:assert/strict';
const{chromium}=await import(process.env.TD_PLAYWRIGHT);const browser=await chromium.launch({headless:true,executablePath:process.env.TD_CHROMIUM});
const out=(process.env.TD_TEST_OUTPUT||new URL('./evidence/speed/',import.meta.url).pathname)+'/';fs.mkdirSync(out,{recursive:true});const results=[];
try{for(const width of [320,375,393]){const ctx=await browser.newContext({viewport:{width,height:852},hasTouch:true,recordVideo:{dir:out}});await ctx.addInitScript(()=>window.requestAnimationFrame=()=>0);const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((base+'/td/'));await p.locator('[data-cmd="pearl"]').click();await p.locator('#startBtn').click();await p.locator('#speedBtn').click();await p.evaluate(()=>advanceTime(19900));assert.equal(await p.evaluate(()=>__td.G.wave),0);await p.screenshot({path:out+`prepare-${width}.png`});await p.evaluate(()=>advanceTime(100));assert.equal(await p.evaluate(()=>__td.G.wave),1);
 const boxes=await p.evaluate(()=>['#speedBtn','#pauseBtn','#cashTxt','#skillBtn'].map(s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return{id:s,x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,scroll:e.scrollWidth,client:e.clientWidth};}));assert(boxes.every(b=>b.x>=0&&b.right<=innerWidthSafe(width)));assert(boxes[0].h>=44&&boxes[0].w>=44);
 for(const x of [3,4]){await p.locator('[data-tw="bbq"]').click();const geo=await p.evaluate(()=>__td.geo);await p.locator('#cv').click({position:{x:geo.OX+(x+.5)*geo.S,y:geo.OY+2.5*geo.S}});await p.locator('#buildConfirm').click();}assert.equal(await p.evaluate(()=>__td.G.tw.size),2);assert.equal(await p.evaluate(()=>__td.G.cash),0);const track=await p.evaluate(()=>ZBSfx.state.track);await p.locator('#pauseBtn').click();const t=await p.evaluate(()=>__td.G.t);await p.evaluate(()=>advanceTime(9000));assert.equal(await p.evaluate(()=>__td.G.t),t);await p.locator('#pauseSpeedBtn').click();await p.locator('#resumeBtn').click();assert.equal(await p.evaluate(()=>ZBSfx.state.track),track);await p.evaluate(()=>advanceTime(8000));await p.screenshot({path:out+`combat-${width}.png`});assert.deepEqual(errors,[]);results.push({width,boxes,track,errors});const video=p.video();await ctx.close();await video.saveAs(out+`speed-${width}.webm`);}
 fs.writeFileSync(out+'browser.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await browser.close();}
function innerWidthSafe(width){return width;}
