'use strict';
// Executes the actual child script in Node VM with minimal DOM/timer fakes.
// This tests protocol/state logic, not browser rendering or WebKit behavior.
const vm=require('node:vm'), fs=require('node:fs'), assert=require('node:assert/strict'), T=require('./tdcore.js');
let checks=0;
const tasks=[];function check(fn){tasks.push(fn);}
function child(embed=true){
  const arcs=[],drawLabels=[]; const nodes=new Map(), timers=new Map(), listeners={}, sent=[], writes=[];const store=new Map();let serial=0, frame=null;
  const noop=()=>{};
  function node(id){if(!nodes.has(id)){const cls=new Set();nodes.set(id,{style:{},setAttribute:noop,innerHTML:'',textContent:'',disabled:false,classList:{toggle:(x,on)=>on?cls.add(x):cls.delete(x),add:x=>cls.add(x),remove:x=>cls.delete(x),contains:x=>cls.has(x)},events:{},addEventListener(k,fn){this.events[k]=fn;},getContext:()=>new Proxy({},{get:(_,k)=>k==='arc'?((...args)=>arcs.push(args)):k==='fillText'?((...args)=>drawLabels.push(args)):noop})});}return nodes.get(id);}
  const w={TDCore:T,TDProto:require('./tdproto.js'),navigator:{locks:{request:async(name,opts,fn)=>fn()}},ZBSfx:new Proxy({},{get:()=>noop}),addEventListener:(k,fn)=>listeners[k]=fn};w.parent=embed?{}:w;
  const ctx={window:w,location:{search:embed?'?embed=1':'',origin:'https://local.test'},document:{hidden:false,documentElement:{},querySelector:node,querySelectorAll:()=>[],addEventListener:noop},Image:function(){},innerWidth:390,innerHeight:844,getComputedStyle:()=>({getPropertyValue:()=>0}),addEventListener:noop,performance:{now:()=>0},requestAnimationFrame:fn=>{frame=fn;return 1;},cancelAnimationFrame:noop,setTimeout:(fn,ms)=>{timers.set(++serial,{fn,ms});return serial;},clearTimeout:id=>timers.delete(id),localStorage:{getItem:k=>{writes.push(['read',k]);return store.get(k)??null;},setItem:(k,v)=>{writes.push(['write',k,v]);store.set(k,v);}}};
  vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/td.js','utf8'),ctx);
  const f={frame:now=>frame(now),arcs,drawLabels,api:w.__td, node, timers, sent, writes, ctx, listeners};
  f.connect=(source=w.parent,origin=ctx.location.origin)=>listeners.message({source,origin,data:{td:'port'},ports:[{postMessage:d=>sent.push(d)}]});
  f.state=(extra={})=>f.api.onState(Object.assign({td:'state',coins:5e10,z:T.norm(),blocked:false,muted:true},extra));
  f.expire=ms=>{for(const [id,t]of [...timers])if(t.ms===ms){timers.delete(id);t.fn();}};
  return f;
}

const fresh=()=>{const f=child(false);f.api.start(1);return f;};
const pick=(f,id)=>f.node('#twGrid').events.click({target:{closest:()=>({dataset:{tw:id}})}});
const cell=(f,x,y)=>{const a=f.api.geo;f.node('#cv').events.pointerdown({clientX:a.OX+(x+.5)*a.S,clientY:a.OY+(y+.5)*a.S});};

const enemy=()=>({type:'tank',hp:10000,max:10000,sp:0,d:0,x:.5,y:1.5,slowT:0,slowK:1,stunT:0,burnT:0,burnD:0});
function game(cmd){const f=child(false);f.api.cmdSel=cmd;f.api.start(1);return f;}
check(()=>{for(const cmd of ['c77','pearl','otaku','rocket']){const f=game(cmd);assert.equal(f.api.G.cash,cmd==='c77'?180:120);f.api.step(4);assert.equal(f.api.G.cash,cmd==='c77'?180:120);}});
check(()=>{for(const cmd of ['c77','rocket']){const f=game(cmd),g=f.api.G;g.wave=1;g.breakT=0;g.es=[enemy()];const before=g.cash;f.api.step(20);f.api.step(20);assert.equal(g.cash,before+(cmd==='rocket'?30:15));assert.equal(g.interestSeconds,30);f.api.step(20);assert.equal(g.cash,before+(cmd==='rocket'?30:15));g.cash=399;f.api.gainEnergy(50);assert.equal(g.cash,400);}});
check(()=>{const f=game('otaku'),g=f.api.G;g.wave=1;g.breakT=0;g.es=[enemy()];assert(f.api.activateSkill());const before=[g.cash,g.skillLeft,g.skillCooldown,g.interestSeconds];f.api.setPause(true);f.api.step(20);assert.deepEqual([g.cash,g.skillLeft,g.skillCooldown,g.interestSeconds],before);f.api.setPause(false);f.ctx.document.hidden=true;f.api.step(20);assert.deepEqual([g.cash,g.skillLeft,g.skillCooldown,g.interestSeconds],before);f.ctx.document.hidden=false;f.api.step(5);assert.equal(g.skillLeft,5);assert.equal(g.skillCooldown,10);assert(!f.api.activateSkill());f.api.step(10);assert.equal(g.skillCooldown,0);assert(f.api.activateSkill());});
check(()=>{const f=game('c77'),g=f.api.G;const cells=[];for(let y=0;y<f.api.geo.ROWS;y++)for(let x=0;x<f.api.geo.COLS;x++)if(!f.api.isPath(x,y))cells.push([x,y]);for(const [x,y]of cells.slice(0,8)){g.cash=400;assert(f.api.build('bbq',x,y));}g.cash=400;assert(!f.api.build('bbq',6,10));assert.equal(g.cash,400);assert.equal(g.tw.size,8);assert(f.api.sell(...cells[0])!==false);assert.equal(g.cash,400);assert(f.api.build('bbq',...cells[0]));assert.equal(g.cash,340);});
check(()=>{const f=game('otaku'),g=f.api.G;g.wave=1;g.breakT=0;g.es=[enemy()];g.cash=400;assert(f.api.activateSkill());const e=g.es[0];f.api.hit(e,100,{burn:10,burnT:3},'t77');assert.equal(e.hp,9870);assert.equal(e.burnD,10);g.cash=0;f.api.hit(e,e.burnD,{dot:true},'t77');assert.equal(e.hp,9860);g.cash=200;f.api.hit(e,100,null,'book');assert.equal(e.hp,9745);});
check(()=>{const f=game('pearl'),g=f.api.G;g.wave=1;g.breakT=0;const e=enemy();e.sp=1;e.slowK=.4;e.slowT=100;g.es=[e];g.cash=400;assert(f.api.activateSkill());f.api.step(1);assert.equal(e.d,.25);g.cash=0;g.interestSeconds=30;f.api.step(1);assert.equal(e.d,.65);assert.equal(g.skillCooldown,28);});
check(()=>{const f=game('rocket'),g=f.api.G;g.cash=398;const e=enemy();e.hp=1;f.api.hit(e,2,null,'book');f.api.hit(e,2,null,'book');assert.equal(g.cash,400);assert.equal(g.kills,1);});
check(()=>{for(const cmd of ['c77','pearl','otaku','rocket']){const f=game(cmd),g=f.api.G;g.wave=1;g.breakT=0;const e=enemy();g.es=[e];f.api.activateSkill();f.api.step(3);assert.equal(e.hp,10000);assert.equal(g.kills,0);}});
check(()=>{const f=game('pearl'),g=f.api.G;g.wave=1;g.breakT=0;const e=enemy();e.type='boss';e.sp=1;e.slowK=.25;e.slowT=100;g.es=[e];g.cash=400;assert(f.api.activateSkill());f.api.step(1);assert.equal(e.d,.5);g.es=[];g.q=[];const left=g.skillLeft,cd=g.skillCooldown;f.api.step(2);assert.equal(g.skillLeft,left);assert.equal(g.skillCooldown,cd);});
check(()=>{const f=game('otaku'),g=f.api.G;g.wave=1;g.es=[enemy()];g.cash=0;assert(!f.api.activateSkill());g.cash=400;f.api.build('bbq',0,0);assert(f.api.activateSkill());const before=f.api.burstMultiplier();f.api.sell(0,0);assert(f.api.burstMultiplier()>before);assert.equal(g.cash,376);f.api.build('bbq',0,0);f.api.sell(0,0);assert.equal(g.cash,352);});
check(async()=>{const f=game('rocket'),g=f.api.G;assert(!f.api.continueEndless());g.wave=10;g.kills=100;g.cash=222;g.lives=7;g.skillCooldown=12;f.api.end(true);await g.savePromise;const normal=g.normalResult;assert(Object.isFrozen(normal));assert(f.api.continueEndless());assert.equal(g.cash,222);assert.equal(g.lives,7);assert.equal(g.skillCooldown,12);assert.equal(g.breakT,5);assert.equal(g.normalResult,normal);f.api.step(5);assert.equal(g.wave,11);assert.equal(g.skillCooldown,12);assert(f.api.waveList(100000).length<=49);g.wave=100000;f.api.spawn('boss');assert(g.es.at(-1).hp<=1e12&&Number.isFinite(g.es.at(-1).hp));});
check(async()=>{const f=child(true);f.connect();f.state();f.api.start(1);const g=f.api.G;f.state({ack:'start',runId:g.runId,ok:true});g.wave=10;g.kills=181;f.api.end(true);await g.savePromise;const message=g.resMsg,oldId=g.runId;assert(Object.isFrozen(message));assert(!f.api.continueEndless());f.state({ack:'result',runId:oldId,ok:false});assert(!f.api.continueEndless());assert.equal(g.resMsg,message);f.state({ack:'result',runId:oldId,ok:true});assert(f.api.continueEndless());assert(!g.endless);const id=g.pendingEndless;f.state({ack:'endlessStart',runId:'wrong',ok:true});assert(!g.endless);f.state({ack:'endlessStart',runId:id,ok:true});assert(g.endless);assert.equal(g.normalResult,message);f.state({ack:'result',runId:oldId,ok:false});assert(g.endless&&!g.over);});
check(async()=>{const f=game('otaku'),g=f.api.G,originalSet=f.ctx.localStorage.setItem;f.ctx.localStorage.setItem=()=>{throw Error('full');};g.wave=10;f.api.end(true);await g.savePromise;assert(!g.saveOk);assert(!f.api.continueEndless());assert(f.node('#resNote').textContent.includes('存储失败'));const snapshot=g.resMsg;f.ctx.localStorage.setItem=originalSet;f.node('#retryBtn').onclick();await g.savePromise;assert(g.saveOk);assert.equal(g.resMsg,snapshot);assert(f.api.continueEndless());});
check(()=>{for(const [cmd,duration,cooldown]of [['otaku',10,15],['pearl',5,30]]){const f=game(cmd),g=f.api.G;g.wave=1;g.breakT=0;g.es=[enemy()];assert(f.api.activateSkill());for(let i=0;i<duration*100-1;i++)f.api.step(.01);assert(g.skillLeft>0&&g.skillLeft<.011);f.api.step(.02);assert.equal(g.skillLeft,0);assert(g.skillCooldown>0);for(let i=0;i<(cooldown-duration)*100-2;i++)f.api.step(.01);assert(g.skillCooldown>0&&g.skillCooldown<.011);f.api.step(.02);assert.equal(g.skillCooldown,0);assert(f.api.activateSkill());}});
check(async()=>{for(const stage of ['entry','clear1','during2','fatal']){const f=game('rocket'),g=f.api.G;g.wave=10;g.kills=181;g.q=[];g.es=[];f.api.end(true);await g.savePromise;assert(f.api.continueEndless());if(stage==='clear1'){g.wave=11;g.breakT=4;g.kills=190;}if(stage==='during2'||stage==='fatal'){g.wave=12;g.breakT=0;g.es=[enemy()];g.kills=200;if(stage==='fatal'){g.lives=1;g.es[0].type='walk';g.es[0].d=f.api.PLEN-.001;g.es[0].sp=1;f.api.step(.01);}}if(!g.over)f.api.end(false);await g.savePromise;assert.equal(g.resMsg.waves,stage==='entry'?0:1);assert.equal(g.resMsg.kills,stage==='entry'?0:stage==='clear1'?9:19);}});
check(()=>{const f=game('pearl');pick(f,'tea');f.node('#detailsBtn').onclick();const text=f.node('#fullTowerInfo').innerHTML;assert(text.includes('普通怪总减速最多75%'));assert(text.includes('小Boss/Boss最多50%'));});
(async()=>{for(const fn of tasks){await fn();checks++;}assert.equal(checks,16);console.log('TD energy/skills:',checks,'checks passed');})().catch(e=>{console.error(e);process.exitCode=1;});
