'use strict';
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
let time=1000, tones=0, resumes=0;const events={};
const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}});
const node=()=>({connect(){},gain:param(),frequency:param(),start(){tones++},stop(){}});
class Audio {constructor(){this.state='suspended';this.currentTime=0;this.sampleRate=100;this.destination={};}createGain(){return node()}createDynamicsCompressor(){return {connect(){},threshold:param(),knee:param(),ratio:param(),attack:param(),release:param()}}createBuffer(){return {getChannelData:()=>new Float32Array(100)}}createOscillator(){return node()}createBufferSource(){return node()}createBiquadFilter(){return node()}resume(){resumes++;this.state='running';return Promise.resolve()}suspend(){this.state='suspended';return Promise.resolve()}}
const ctx={window:{AudioContext:Audio},document:{hidden:false,addEventListener:(n,f)=>(events[n]??=[]).push(f)},performance:{now:()=>time},setInterval:()=>1,clearInterval(){}};
ctx.URL=URL;ctx.document.baseURI='https://fixture.invalid/td/';ctx.AudioContext=Audio;ctx.window=ctx;ctx.addEventListener=()=>{};ctx.fetch=async()=>{throw Error('intentional offline unit fixture')};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/../audio/loop-music.js','utf8'),ctx);vm.runInContext(fs.readFileSync(__dirname+'/tdsfx.js','utf8'),ctx);const s=ctx.window.ZBSfx;
s.hit();assert.equal(tones,0);s.unlock();assert.equal(resumes,1);s.shot('tech');const initial=tones;for(let i=0;i<50;i++)s.shot('tech');assert.equal(tones,initial);time+=100;s.shot('pearl');assert(tones>initial);s.setMuted(true);const silent=tones;s.hit();s.cue('wave');assert.equal(tones,silent);assert.equal(s.state.master.gain.value,0);s.setMuted(false);s.setPaused(true);s.shot('rocket');assert.equal(tones,silent);ctx.document.hidden=true;events.visibilitychange.forEach(f=>f());assert.equal(s.state.ctx.state,'suspended');ctx.document.hidden=false;events.visibilitychange.forEach(f=>f());s.setPaused(false);time+=1000;s.cue('build');assert(tones>silent);assert.equal(s.state.master.gain.value,.7);assert.equal(s.state.sfx.gain.value,.32);
console.log('TD audio: gesture unlock, rate gate, mute, pause, visibility and gain checks passed (mock AudioContext; no audible playback claim)');

s.startBgm(5);assert.equal(s.state.recorded.status.wanted,true);assert.equal(s.state.timer,0);s.startBgm(5);assert.equal(s.state.recorded.status.attempts,1);s.setPaused(true);assert.equal(s.state.recorded.status.gain,0);assert.equal(s.state.recorded.status.wanted,false);s.setPaused(false);s.startBgm(5);s.stopBgm();assert.equal(s.state.recorded.status.created,0);assert.equal(s.state.voices.size,0);
setImmediate(()=>{assert.match(s.state.recorded.status.error,/intentional offline/);assert.equal(s.state.recorded.status.created,0);console.log('Recorded BGM intent/mute/single fetch and explicit offline error passed; audible playback is covered by native browser tests');});
