// Isolated browser storage/lock fixtures, never a user profile or real save.
import assert from 'node:assert/strict';import fs from 'node:fs';
const{chromium}=await import(process.env.TD_PLAYWRIGHT);const browser=await chromium.launch({headless:true,executablePath:process.env.TD_CHROMIUM});const origin='http://127.0.0.1:8882',url=origin+'/td/?embed=1',KEY='tangzhe-formal-td-proto-v1',OLD='tangzhe-td-proto',LOCK=KEY+'-write';const out=new URL('./evidence/proto/',import.meta.url).pathname;fs.mkdirSync(out,{recursive:true});const report={};
try{
 const ctx=await browser.newContext({viewport:{width:393,height:852},recordVideo:{dir:out,size:{width:393,height:852}}});const errors=[];ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));const a=await ctx.newPage();await a.goto(url);assert.equal(await a.evaluate(()=>__td.EMBED),false);
 const legacy=await a.evaluate(OLD=>{const z={...TDCore.norm(),coins:5e10};TDCore.applyEndless(z,{runId:'real-legacy-fixture',waves:2,kills:7});const text=JSON.stringify(z);localStorage.setItem(OLD,text);return text;},OLD);await a.reload();const b=await ctx.newPage();await b.goto(url);assert(await a.evaluate(()=>__td.selectProto('c77')));assert.equal(await a.evaluate(k=>localStorage.getItem(k),OLD),legacy);assert.equal(await a.evaluate(k=>JSON.parse(localStorage.getItem(k)).endless.top[0].score,KEY),2007);
 const formal=await ctx.newPage();await formal.goto(origin+'/preview/td/');await formal.locator('[data-cmd="rocket"]').click();assert.equal(await formal.evaluate(k=>JSON.parse(localStorage.getItem(k)).endless,OLD),undefined);assert.equal(await a.evaluate(k=>JSON.parse(localStorage.getItem(k)).endless.top[0].score,KEY),2007);await formal.close();report.roundtrip=true;
 const c=await ctx.newPage();await c.goto(url);
 async function hold(){await c.evaluate(name=>{window.__held=false;window.__lockDone=navigator.locks.request(name,{mode:'exclusive'},async()=>{window.__held=true;await new Promise(resolve=>window.__release=resolve);});},LOCK);await c.waitForFunction(()=>__held);}
 async function queued(n){await c.waitForFunction(async({name,n})=>(await navigator.locks.query()).pending.filter(l=>l.name===name).length>=n,{name:LOCK,n});}
 await hold();await Promise.all([a.evaluate(()=>__td.buyUp('bbq')),b.evaluate(()=>__td.buyUp('tea'))]);await queued(2);assert(await a.evaluate(()=>__td.protoPending));assert(await b.evaluate(()=>__td.protoPending));await c.evaluate(()=>__release());await Promise.all([a.waitForFunction(()=>!__td.protoPending),b.waitForFunction(()=>!__td.protoPending)]);let disk=await c.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.equal(disk.lv.bbq,1);assert.equal(disk.lv.tea,1);assert.equal(disk.coins,5e10-2e6);report.concurrentBuys=true;
 for(const p of [a,b])await p.evaluate(async()=>{__td.start(1);__td.G.wave=10;__td.G.kills=181;__td.G.es=[];__td.G.q=[];__td.end(true);await __td.G.savePromise;if(!__td.G.saveOk)throw Error(__td.G.why);__td.continueEndless();});
 const ids=await Promise.all([a.evaluate(()=>__td.G.runId),b.evaluate(()=>__td.G.runId)]);await hold();await Promise.all([a.evaluate(()=>{__td.G.wave=14;__td.G.kills+=100;__td.G.es=[];__td.G.q=[];__td.end(false);}),b.evaluate(()=>{__td.G.wave=15;__td.G.kills+=120;__td.G.es=[];__td.G.q=[];__td.end(false);})]);await queued(2);assert(await a.evaluate(()=>__td.G.wait&&!__td.G.saveOk));assert(await b.evaluate(()=>__td.G.wait&&!__td.G.saveOk));await c.evaluate(()=>__release());await a.waitForFunction(()=>__td.G.saveOk);await a.close();await b.waitForFunction(()=>__td.G.saveOk);disk=await c.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert(ids.every(id=>disk.endless.top.some(e=>e.runId===id)));assert.equal(disk.lv.bbq,1);assert.equal(disk.lv.tea,1);assert.equal(disk.coins,5e10-2e6);assert.equal(disk.best,10);report.concurrentScoresAndImmediateClose={ids,top:disk.endless.top};await b.reload();assert(await b.evaluate(ids=>ids.every(id=>__td.proto.endless.top.some(e=>e.runId===id)),ids));
 await b.evaluate(key=>{window.__originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw Error('quota fixture');return __originalSet.call(this,k,v);};},KEY);const before=await b.evaluate(()=>({coins:__td.proto.coins,lv:__td.proto.lv.book,cmd:__td.cmdSel}));assert.equal(await b.evaluate(()=>__td.selectProto('pearl')),false);assert.equal(await b.evaluate(()=>__td.cmdSel),before.cmd);await b.locator('[data-up="book"]').click();await b.waitForFunction(()=>!__td.protoPending);assert.deepEqual(await b.evaluate(()=>({coins:__td.proto.coins,lv:__td.proto.lv.book,cmd:__td.cmdSel})),before);assert((await b.locator('#protoStatus').innerText()).includes('存储失败'));await b.screenshot({path:out+'purchase-failure.png'});await b.evaluate(()=>Storage.prototype.setItem=__originalSet);await b.locator('#buyRetryBtn').click();await b.waitForFunction(()=>!__td.protoPending&&__td.proto.lv.book===1);assert.equal(await b.evaluate(()=>__td.proto.coins),before.coins-1e6);report.failureRollbackRetry=true;
 // Already committed but verification read fails: retry receipt must not charge again.
 await b.evaluate(key=>{window.__get=Storage.prototype.getItem;window.__set=Storage.prototype.setItem;let fail=false;Storage.prototype.setItem=function(k,v){__set.call(this,k,v);if(k===key)fail=true;};Storage.prototype.getItem=function(k){if(k===key&&fail){fail=false;throw Error('readback fixture');}return __get.call(this,k);};},KEY);const beforeTea=await b.evaluate(()=>__td.proto.coins);await b.locator('[data-up="tea"]').click();await b.waitForFunction(()=>!__td.protoPending);assert((await b.locator('#protoStatus').innerText()).includes('未确认'));await b.evaluate(()=>{Storage.prototype.getItem=__get;Storage.prototype.setItem=__set;});await b.locator('#buyRetryBtn').click();await b.waitForFunction(()=>!__td.protoPending&&__td.proto.lv.tea===2);assert.equal(await b.evaluate(()=>__td.proto.coins),beforeTea-1900000);report.readbackFailureDedup=true;
 await b.evaluate(async()=>{__td.start(1);__td.G.wave=10;__td.G.kills=181;__td.G.q=[];__td.G.es=[];__td.end(true);await __td.G.savePromise;__td.continueEndless();});await b.evaluate(key=>{window.__setBeforeScore=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw Error('score quota fixture');return __setBeforeScore.call(this,k,v);};__td.G.wave=16;__td.G.kills+=150;__td.G.q=[];__td.G.es=[];__td.end(false);},KEY);await b.waitForFunction(()=>!__td.G.wait);const locked=await b.evaluate(()=>JSON.stringify(__td.G.resMsg));assert.equal(await b.evaluate(()=>__td.G.saveOk),false);assert((await b.locator('#endlessBoard').innerText()).includes('尚未保存'));await b.screenshot({path:out+'score-failure.png'});await b.evaluate(()=>Storage.prototype.setItem=__setBeforeScore);await b.locator('#retryBtn').click();await b.waitForFunction(()=>__td.G.saveOk);assert.equal(await b.evaluate(()=>JSON.stringify(__td.G.resMsg)),locked);assert.equal(await b.evaluate(()=>__td.proto.endless.top.filter(x=>x.runId===__td.G.runId).length),1);report.scoreFailureRetry=true;

 assert.deepEqual(errors,[]);const video=b.video();await ctx.close();await video.saveAs(out+'concurrent-and-retry.webm');
 const no=await browser.newContext({viewport:{width:320,height:568}});await no.addInitScript(()=>{window.__nativeLocks=navigator.locks;Object.defineProperty(navigator,'locks',{configurable:true,value:undefined});});const p=await no.newPage();await p.goto(url);await p.locator('#startBtn').click();await p.evaluate(async()=>{__td.G.wave=10;__td.G.kills=181;__td.end(true);await __td.G.savePromise;});assert.equal(await p.evaluate(()=>__td.G.saveOk),false);assert.equal(await p.evaluate(k=>localStorage.getItem(k),KEY),null);assert.equal(await p.evaluate(async()=> (await __td.protoStore.settle({td:'endlessResult',runId:'no-lock-score',waves:5,kills:90})).ok),false);assert.equal(await p.evaluate(k=>localStorage.getItem(k),KEY),null);assert((await p.locator('#resNote').innerText()).includes('安全存档锁'));await p.screenshot({path:out+'no-lock-result.png'});assert.equal(await p.evaluate(()=>__td.continueEndless()),false);await p.evaluate(()=>Object.defineProperty(navigator,'locks',{configurable:true,value:__nativeLocks}));await p.locator('#retryBtn').click();await p.waitForFunction(()=>__td.G.saveOk);assert.equal(await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).best,KEY),10);report.noLockNoWriteThenRetry=true;await no.close();
 fs.writeFileSync(out+'results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}
