import {test} from 'node:test';import assert from 'node:assert/strict';import {createCardBgm} from '../../cards/ui/bgm.mjs';
function pcm(n=1000,rate=8000,channels=2){const data=Array.from({length:channels},()=>new Float32Array(n));return {length:n,sampleRate:rate,numberOfChannels:channels,duration:n/rate,getChannelData:i=>data[i]};}
const settle=()=>new Promise(r=>setTimeout(r,0));
function fixture(fail='network'){let time=0,fetches=0,decodes=0,sources=0;class C{createBuffer(ch,n,rate){return pcm(n,rate,ch)}state='suspended';destination={};resume(){this.state='running';return Promise.resolve()}suspend(){this.state='suspended';return Promise.resolve()}close(){this.state='closed';return Promise.resolve()}decodeAudioData(){decodes++;return fail==='decode'&&decodes===1?Promise.reject(Error('decode')):Promise.resolve(pcm())}createBufferSource(){sources++;return {connect(){},start(){},stop(){}}}createGain(){return {gain:{},connect(){}}}}
 const bgm=createCardBgm({url:'fixture',AudioContext:C,now:()=>time,fetch:async()=>{fetches++;if(fail==='network'&&fetches===1)throw Error('offline');return {ok:true,arrayBuffer:async()=>new ArrayBuffer(1)}}});bgm.update({muted:false,paused:false,hidden:false});return {bgm,next:()=>time+=1000,get counts(){return {fetches,decodes,sources}}};}
for(const fail of ['network','decode'])test(`${fail} failure only retries on gesture after backoff, clears error`,async()=>{const f=fixture(fail);f.bgm.unlock();await settle();assert(f.bgm.status.error);assert.equal(f.bgm.status.loading,false);for(let i=0;i<500;i++)f.bgm.update({paused:false});await settle();assert.equal(f.counts.fetches,1);for(let i=0;i<20;i++)f.bgm.unlock();await settle();assert.equal(f.counts.fetches,1);f.next();f.bgm.update({paused:false});await settle();assert.equal(f.counts.fetches,1);for(let i=0;i<20;i++)f.bgm.unlock();await settle();assert.equal(f.counts.fetches,2);assert.equal(f.counts.sources,1);assert.equal(f.bgm.status.error,null);assert(f.bgm.status.decoded);f.bgm.update({paused:true});await settle();f.bgm.unlock();f.bgm.update({paused:false});await settle();assert.equal(f.counts.sources,1);});
test('late decode after dispose creates no source',async()=>{let resolve;class C{createBuffer(ch,n,rate){return pcm(n,rate,ch)}state='suspended';resume(){return Promise.resolve()}suspend(){return Promise.resolve()}close(){return Promise.resolve()}decodeAudioData(){return new Promise(r=>resolve=r)}createBufferSource(){throw Error('must not create')}}const b=createCardBgm({url:'x',AudioContext:C,fetch:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)})});b.update({muted:false,paused:false});b.unlock();await settle();b.dispose();resolve(pcm());await settle();assert.equal(b.status.created,0);});

function asynchronousFixture(){
 let ctx,sourceCount=0,stopped=0,resumes=0,suspends=0;const pending=[];
 class C{createBuffer(ch,n,rate){return pcm(n,rate,ch)}state='suspended';destination={};gain={value:0};constructor(){ctx=this}
  resume(){resumes++;return new Promise(resolve=>pending.push(()=>{if(this.state!=='closed')this.state='running';resolve()}))}
  suspend(){suspends++;this.state='suspended';return Promise.resolve()}
  close(){this.state='closed';return Promise.resolve()}
  decodeAudioData(){return Promise.resolve(pcm())}
  createBufferSource(){sourceCount++;return {connect(){},start(){},stop(){stopped++}}}
  createGain(){return {gain:this.gain,connect(){}}}
 }
 const b=createCardBgm({url:'fixture',AudioContext:C,fetch:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)})});
 return {b,finishResume:()=>{assert(pending.length);pending.shift()()},get value(){return {state:ctx?.state,gain:ctx?.gain.value,sourceCount,stopped,resumes,suspends,pending:pending.length}}};
}
async function playing(){const f=asynchronousFixture();f.b.update({muted:false,paused:false});f.b.unlock();assert.equal(f.value.pending,1);f.finishResume();await settle();assert.equal(f.value.sourceCount,1);assert.equal(f.value.gain,.22);return f;}
for(const flag of ['muted','paused','hidden'])test(`${flag} clicks do not resume existing loop`,async()=>{const f=await playing();f.b.update({[flag]:true});assert.equal(f.value.gain,0);await settle();const calls=f.value.resumes;for(let i=0;i<30;i++)f.b.unlock();await settle();assert.equal(f.value.resumes,calls);assert.equal(f.value.state,'suspended');assert.equal(f.value.gain,0);assert.equal(f.value.sourceCount,1);});
for(const flag of ['muted','paused','hidden','dispose'])test(`pending asynchronous resume then ${flag} never enables loop gain`,async()=>{const f=await playing();f.b.update({paused:true});await settle();f.b.update({paused:false});assert.equal(f.value.pending,1);assert.equal(f.value.gain,0);if(flag==='dispose')f.b.dispose();else f.b.update({[flag]:true});for(let i=0;i<30;i++)f.b.unlock();assert.equal(f.value.pending,1);f.finishResume();assert.equal(f.value.gain,0);await settle();assert.equal(f.value.state,flag==='dispose'?'closed':'suspended');assert.equal(f.value.gain,0);assert.equal(f.value.sourceCount,1);if(flag==='dispose')assert.equal(f.value.stopped,1);else{f.b.update({muted:false,paused:false,hidden:false});f.finishResume();await settle();assert.equal(f.value.gain,.22);assert.equal(f.value.sourceCount,1);}});
test('first pending resume then mute creates no source and concurrent updates coalesce',async()=>{const f=asynchronousFixture();f.b.update({muted:false,paused:false});f.b.unlock();for(let i=0;i<50;i++){f.b.unlock();f.b.update({paused:false});}assert.equal(f.value.resumes,1);f.b.update({muted:true});f.finishResume();await settle();assert.equal(f.value.sourceCount,0);assert.equal(f.value.state,'suspended');assert.equal(f.value.gain,0);});
