import {test} from 'node:test';import assert from 'node:assert/strict';import {createApprovedTrialModel} from '../../collection/domain/model.mjs';import {TRIAL_CONFIG as C} from '../../collection/domain/trial-config.mjs';import {canonical} from '../../collection/domain/json.mjs';import {createApprovedTrialModel as legacyCreate} from '../../collection/domain/legacy-v1/model.mjs';import {TRIAL_CONFIG as L} from '../../collection/domain/legacy-v1/trial-config.mjs';
const approval=c=>({schemaVersion:1,approvedConfigCanonical:canonical(c),evidenceRefs:['user-approved-fc2'],walletBridgeApproved:false}),m=createApprovedTrialModel(C,approval(C));
const create=(holdings={},dust=0)=>m.createState({holdings,dust,preferences:{suppressOverflowWarning:false}});
let serial=0;function run(st,request,tickets,{decision='continue',suppress=false,overflow=true}={}){const txId='unit:'+ ++serial;const step=(type,extra={})=>st=m.reduce(st,{type,txId,eventId:txId+':'+type,expectedRevision:st.revision,...extra});step('BEGIN',{request});step('DECIDE',{decision,allowDustOverflow:overflow,suppressFutureOverflowWarnings:suppress});if(decision==='cancel')return st;if(request.kind==='draw'){step('SELECT',{tickets});step('RECORD_DEBIT',{walletReceipt:{schemaVersion:1,debitId:txId+':debit',intent:m.walletIntent(st,txId),walletRevision:1}});}step('COMMIT');return st;}
let offset=0;
for(const r of C.rarities){const ticket=offset;offset+=r.weight;const card=C.pool.find(c=>c.rarity===r.id).cardId;
 test(r.id+' gold/normal threshold and uniform card selection',()=>{const pools=C.pool.filter(c=>c.rarity===r.id);for(let i=0;i<pools.length;i++){for(const [golden,finish]of [[r.goldenWeight-1,'golden'],[r.goldenWeight,'normal']]){const s=run(create(),{kind:'draw'},{rarity:ticket,card:i,golden});assert.equal(s.holdings[pools[i].cardId][finish],1);}}});
 test(r.id+' full normal upgraded + normal dust; full golden + gold dust',()=>{let s=run(create({[card]:{normal:r.ownershipCap,golden:0}}),{kind:'draw'},{rarity:ticket,card:0,golden:0});assert.equal(s.holdings[card].normal,r.ownershipCap-1);assert.equal(s.dust,r.duplicateDust);s=run(create({[card]:{normal:0,golden:r.ownershipCap}}),{kind:'draw'},{rarity:ticket,card:0,golden:0});assert.equal(s.dust,r.goldenDuplicateDust);s=run(create({[card]:{normal:0,golden:r.ownershipCap}}),{kind:'draw'},{rarity:ticket,card:0,golden:9999});assert.equal(s.dust,r.duplicateDust);});
 test(r.id+' normal craft cost/cap/no golden',()=>{const s=run(create({},50000),{kind:'craft',cardId:card});assert.equal(s.dust,50000-r.craftDustCost);assert.deepEqual(s.holdings[card],{normal:1,golden:0});assert.throws(()=>m.quote(create({[card]:{normal:0,golden:r.ownershipCap}},50000),{kind:'craft',cardId:card}),/OWNERSHIP_COPY_LIMIT/);});
}
test('50000 exact cap no overflow, max golden compensation before RNG',()=>{const card=C.pool.find(c=>c.rarity==='legendary').cardId,holding={[card]:{normal:0,golden:1}};assert.equal(m.quote(create(holding,48400),{kind:'draw'}).requiresOverflowConfirmation,false);assert.equal(m.quote(create(holding,48401),{kind:'draw'}).requiresOverflowConfirmation,true);const s=run(create(holding,49999),{kind:'draw'},{rarity:9700,card:0,golden:0},{suppress:true});assert.equal(s.dust,50000);assert.equal(s.preferences.suppressOverflowWarning,true);const tx=Object.values(s.transactions)[0];assert.equal(tx.outcome.dustDiscarded,1599);});
test('cancel leaves holdings/dust/preferences unchanged and no tickets',()=>{const s=run(create({},50000),{kind:'draw'},null,{decision:'cancel',overflow:false});assert.equal(s.dust,50000);assert.deepEqual(s.holdings,{});assert.equal(s.preferences.suppressOverflowWarning,false);assert.equal(Object.values(s.transactions)[0].tickets,null);});
test('gild removed; replay restores new rules',()=>{assert.throws(()=>m.quote(create(),{kind:'gild',cardId:C.pool[0].cardId}),/INVALID_REQUEST_KIND/);const s=run(create({},1000),{kind:'craft',cardId:C.pool[0].cardId});assert.deepEqual(m.restore(JSON.parse(JSON.stringify(s))),s);});
test('legacy completed state preserved, pending explicitly protected',()=>{const old=legacyCreate(L,approval(L)),card=L.pool[0].cardId;const state=old.createState({holdings:{[card]:{normal:1,golden:1}},dust:3000,preferences:{suppressOverflowWarning:true}}),next=m.upgradeLegacy(state);assert.equal(next.dust,3000);assert.deepEqual(next.holdings,state.holdings);assert.deepEqual(next.genesis.legacy,state);assert.deepEqual(m.restore(JSON.parse(JSON.stringify(next))),next);const pending=old.reduce(state,{type:'BEGIN',eventId:'old:e',txId:'old:t',expectedRevision:0,request:{kind:'draw'}});assert.throws(()=>m.upgradeLegacy(pending),/LEGACY_PENDING_REQUIRES_REVIEW/);});
