import assert from 'node:assert/strict';import {test} from 'node:test';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {sha256,validateV15} from '../../collection/domain/sha256.mjs';import {createSaveCoordinator,KEYS} from '../../collection/host-save.mjs';import {TRIAL_CONFIG} from '../../collection/domain/trial-config.mjs';import {createApprovedTrialModel} from '../../collection/domain/model.mjs';import {canonical} from '../../collection/domain/json.mjs';
const require=createRequire(import.meta.url),model=createApprovedTrialModel(TRIAL_CONFIG,{schemaVersion:1,approvedConfigCanonical:canonical(TRIAL_CONFIG),evidenceRefs:['test'],walletBridgeApproved:false});
function setup(data=new Map(),hook=()=>{}){delete require.cache[require.resolve('../../economy.js')];const E=require('../../economy.js');const c=createSaveCoordinator({storage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>{data.set(k,v);hook(k,v,data)}},economy:E,model,ownsLock:()=>true});E.installFormalCollectionProtocol(c);return {data,E,c,init(){const i=c.inspect();return c.initialize({approvedSourceRaw:i.sourceRaw,approvedSourceEvidence:i.sourceEvidence,approvedEmpty:!i.sourceState,now:1})}};}
test('SHA256 UTF8 and multi-block match node crypto',()=>{for(const t of ['', 'abc','中文😀','a'.repeat(100000)])assert.equal(sha256(t),createHash('sha256').update(t).digest('hex'));});
test('archive corruption across fresh coordinator cannot adopt or commit',()=>{const f=setup();f.data.set(KEYS.source,JSON.stringify(f.E.newState(1)));const init=f.init();assert(init.ok);const a=JSON.parse(f.data.get(KEYS.original)),p=JSON.parse(a.payload);p.source[KEYS.source]='not JSON';a.payload=JSON.stringify(p);f.data.set(KEYS.original,JSON.stringify(a));const g=setup(f.data);assert.equal(g.c.adopt().ok,false);assert.equal(g.c.commit(init.state).ok,false);});
for(const key of [KEYS.main,KEYS.backup,KEYS.tab,KEYS.original])test(`foreign ${key} during original write retained`,()=>{const f=setup(new Map(),(k,v,data)=>{if(k===KEYS.original)data.set(key,'foreign')});assert.equal(f.init().ok,false);assert.equal(f.data.get(key),'foreign');});
for(const payload of [{format:1,release:'15'},{format:1,release:'15',main:{},backup:7},{format:1,release:'15',main:null}])test('valid digest with invalid v15 shape protected '+JSON.stringify(payload),()=>{const text=JSON.stringify(payload),raw=JSON.stringify({payload:text,sha256:sha256(text)});assert.equal(validateV15(raw),false);const f=setup();f.data.set(KEYS.source,JSON.stringify(f.E.newState(1)));f.data.set(KEYS.v15,raw);assert.equal(f.c.inspect().code,'V15_SNAPSHOT_INVALID');assert.equal(f.data.has(KEYS.original),false);});
import {createApprovedTrialModel as legacyCreate} from '../../collection/domain/legacy-v1/model.mjs';import {TRIAL_CONFIG as legacyConfig} from '../../collection/domain/legacy-v1/trial-config.mjs';
const legacy=legacyCreate(legacyConfig,{schemaVersion:1,approvedConfigCanonical:canonical(legacyConfig),evidenceRefs:['test'],walletBridgeApproved:false});
function oldFixture(pending=false){const f=setup();f.init();const s=JSON.parse(f.data.get(KEYS.main));s.collection=legacy.createState({holdings:{[legacyConfig.pool[0].cardId]:{normal:1,golden:1}},dust:3000,preferences:{suppressOverflowWarning:true}});if(pending)s.collection=legacy.reduce(s.collection,{type:'BEGIN',txId:'old:pending',eventId:'old:begin',expectedRevision:0,request:{kind:'draw'}});f.data.set(KEYS.main,JSON.stringify(s));return {...setup(f.data),before:JSON.stringify(s)};}
test('legacy rules explicit upgrade retains holdings, gold, dust and parent; cancel/inspect writes zero',()=>{const f=oldFixture();const i=f.c.inspect();assert(i.needsConfigConsent);assert.equal(f.data.get(KEYS.main),f.before);const result=f.c.upgradeConfig(i.approvedRaw);assert(result.ok);const before=JSON.parse(f.before);for(const k of Object.keys(before).filter(k=>!['collection','rev'].includes(k)))assert.deepEqual(result.state[k],before[k]);assert.deepEqual(result.state.collection.holdings,before.collection.holdings);assert.equal(result.state.collection.dust,3000);assert.equal(f.data.get(KEYS.backup),f.before);assert(setup(f.data).c.adopt().ok);});
test('changed legacy source must reconfirm, no overwrite',()=>{const f=oldFixture(),i=f.c.inspect();const changed=JSON.parse(f.before);changed.coins++;f.data.set(KEYS.main,JSON.stringify(changed));assert.equal(f.c.upgradeConfig(i.approvedRaw).code,'CONFIG_SOURCE_CHANGED_RECONFIRM');assert.equal(f.data.get(KEYS.main),JSON.stringify(changed));});
test('legacy active transaction protected with original bytes unchanged',()=>{const f=oldFixture(true);assert.equal(f.c.inspect().code,'LEGACY_PENDING_REQUIRES_REVIEW');assert.equal(f.data.get(KEYS.main),f.before);});
