import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
const engine=process.env.TEST_ENGINE||'chromium',pw=await import(process.env.PLAYWRIGHT_MODULE),browser=await pw[engine].launch(),E=createRequire(import.meta.url)('../../economy.js');
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8788';
const audit={engine,rows:[],csp:[],pageErrors:[],consoleErrors:[],httpErrors:[],requestFailures:[],audio:[],frames:[],styleNodes:[]};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function poll(fn,pred){for(let i=0;i<240;i++){const d=await fn();if(pred(d))return d;await sleep(25)}throw Error('poll timeout '+JSON.stringify(await fn()))}
try{const c=await browser.newContext({viewport:{width:844,height:390},reducedMotion:'reduce'});await c.exposeBinding('auditEvent',({frame},data)=>{audit[data.kind].push({frame:frame.url(),stage:audit.rows.length,...data})});c.on('weberror',e=>audit.pageErrors.push(e.error().message));c.on('response',r=>{if(r.status()>=400)audit.httpErrors.push({url:r.url(),status:r.status()})});c.on('requestfailed',r=>audit.requestFailures.push({url:r.url(),error:r.failure()?.errorText}));c.on('page',p=>{p.on('console',m=>{if(m.type()==='error')audit.consoleErrors.push(m.text())});p.on('framenavigated',f=>audit.frames.push(f.url()))});
await c.addInitScript(()=>{Date.now=()=>1791648000000;window.__audioAudit=[];new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.tagName==='STYLE')auditEvent({kind:'styleNodes',text:n.textContent})}).observe(document,{subtree:true,childList:true});addEventListener('securitypolicyviolation',e=>auditEvent({kind:'csp',directive:e.effectiveDirective,blocked:e.blockedURI,source:e.sourceFile,line:e.lineNumber,sample:e.sample}));const Native=window.AudioContext||window.webkitAudioContext;if(Native){function Wrapped(...args){const ctx=new Native(...args);window.__audioAudit.push(ctx);ctx.addEventListener('statechange',()=>auditEvent({kind:'audio',state:ctx.state,index:window.__audioAudit.indexOf(ctx)}));return ctx}Wrapped.prototype=Native.prototype;window.AudioContext=Wrapped;if(window.webkitAudioContext)window.webkitAudioContext=Wrapped;}});
const p=await c.newPage();await p.goto(base+'/version.json');const seed=E.newState(1791648000000);seed.coins=20000000;seed.coinFrac=.123;for(const shop of seed.shops){shop.open=true;shop.lv=1}await p.evaluate(s=>localStorage.setItem('tangzhe-save',JSON.stringify(s)),seed);await p.goto(base+'/');await p.getByRole('button',{name:'同意并继续',exact:true}).click();await p.waitForFunction(()=>window.__tzz);if(await p.locator('#mOk').isVisible())await p.locator('#mOk').click();await p.locator('#shopTabs [data-shop="2"]').click();await poll(()=>p.evaluate(()=>__tzz.audioState()),d=>d==='running');
await p.locator('[data-act="cards"]').click();const f=await(await p.$('#cardsFrame')).contentFrame();await f.waitForURL('**/cards/ui/index.html?**');const diag=()=>f.evaluate(async()=>(await import(document.querySelector('script[type=module]').src)).getDiagnostics());await poll(diag,d=>d.ported&&!!d.lastSaved);assert.equal(await p.evaluate(()=>__tzz.audioState()),'suspended');await f.locator('#pause').click();await f.locator('#pause').click();await poll(diag,d=>d.bgm.state==='running');assert.equal(await p.evaluate(()=>__tzz.audioState()),'suspended');audit.rows.push('real shop button → cards port/save; parent suspended while card AudioContext runs');
await f.locator('#hand-count').click();const card=f.locator('.browse-card').first();await card.scrollIntoViewIfNeeded();const before=(await diag()).revision;await card.click();assert.equal((await diag()).revision,before);assert.equal((await diag()).handExpanded,false);await f.locator('#cancel').click();audit.rows.push('real expanded hand selection is UI-only; cancel returns without commit');
await f.locator('#menu-open').click();await f.locator('#collection-open').click();await f.locator('#cc-draw').click();await f.locator('#cc-confirm-cancel').click();await f.locator('#cc-confirm').waitFor({state:'hidden'});const coins=await p.evaluate(()=>__tzz.state.coins);
await p.evaluate(()=>{const original=Storage.prototype.setItem;window.__restoreStorage=()=>Storage.prototype.setItem=original;let failed=false;Storage.prototype.setItem=function(k,v){if(k==='tangzhe-formal-collection-v1-save'&&!failed&&Object.values(JSON.parse(v).collection?.transactions||{}).some(t=>t.stage==='committed')){failed=true;throw new DOMException('test commit failure','QuotaExceededError')}return original.call(this,k,v)}});await f.locator('#cc-draw').click();await f.locator('#cc-confirm-continue').click();await f.locator('#cc-confirm').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>__tzz.state.coins),coins);await p.evaluate(()=>__restoreStorage());await f.locator('#cc-refresh').click();await f.locator('#cc-resume').click();await f.locator('#cc-reveal-finish').click();assert.equal(await p.evaluate(()=>__tzz.state.coins),coins-5000000);const committed=await p.evaluate(()=>structuredClone(__tzz.state.collection));await f.locator('#cc-refresh').click();assert.deepEqual(await p.evaluate(()=>__tzz.state.collection),committed);audit.rows.push('real draw cancellation, injected COMMITTED write failure, fixed-result recovery and no second debit');
await f.locator('#cc-close').click();await f.locator('#exit-embed').click();await p.waitForFunction(()=>!__tzz.cardsOpen);await poll(()=>p.evaluate(()=>__tzz.audioState()),d=>d==='running');audit.rows.push('card exit unloads frame before business audio resumes');await p.locator('#mute').click();await p.reload();await p.waitForFunction(()=>window.__tzz);assert.equal(await p.evaluate(()=>__tzz.state.muted),true);await p.locator('#mOk').click();await p.locator('#shopTabs [data-shop="2"]').click();await p.locator('[data-act="cards"]').click();const restored=await(await p.$('#cardsFrame')).contentFrame();await restored.waitForURL('**/cards/ui/index.html?**');await restored.locator('#resume-continue').click();const rd=()=>restored.evaluate(async()=>(await import(document.querySelector('script[type=module]').src)).getDiagnostics());await poll(rd,d=>d.ported&&d.muted);await restored.locator('#pause').click();await restored.locator('#pause').click();assert.equal((await rd()).bgm.created,0);assert.equal((await rd()).bgm.muted,true);assert.notEqual(await p.evaluate(()=>__tzz.audioState()),'running');audit.rows.push('full parent reload preserves mute; trusted card clicks cannot start BGM');await restored.locator('#exit-embed').click();await p.waitForFunction(()=>!__tzz.cardsOpen);
await p.locator('#shopTabs [data-shop="3"]').click();await p.locator('[data-act="td"]').click();const td=await(await p.$('#tdFrame')).contentFrame();await td.locator('#startBtn').waitFor();await poll(()=>td.locator('#walletLbl').innerText(),s=>!s.includes('模拟'));await td.locator('#startBtn').click();await td.locator('#hud').waitFor({state:'visible'});assert.equal(await p.evaluate(()=>__tzz.tdOpen),true);await td.locator('#pauseBtn').click();audit.rows.push('real technology-shop → protocol3 tower-defense iframe → start → pause');
await sleep(200);assert.deepEqual(audit.csp,[]);assert.deepEqual(audit.pageErrors,[]);assert.deepEqual(audit.httpErrors,[]);assert.deepEqual(audit.consoleErrors,[]);const cancelled=audit.requestFailures;assert(cancelled.every(r=>/ERR_ABORTED|cancelled|canceled/i.test(r.error)));audit.cancelledResourceChecks=[];for(const url of new Set(cancelled.map(r=>r.url))){const r=await c.request.get(url);audit.cancelledResourceChecks.push({url,status:r.status()});assert.equal(r.status(),200)}await c.close();}finally{await browser.close();fs.writeFileSync(`evidence/fc6-${engine}-final-audit.json`,JSON.stringify(audit,null,2));}console.log(audit.rows);
