const engine=process.env.TEST_ENGINE||'chromium';const pw=await import(process.env.PLAYWRIGHT_MODULE);import fs from'node:fs';import assert from'node:assert/strict';import * as core from'../../cards/cardcore.mjs';
fs.mkdirSync(`evidence/hand-${engine}`,{recursive:true});
const browser=await pw[engine].launch({headless:true}),result={browser:await browser.version(),cases:[]};
async function diag(p){return p.evaluate(async()=>{const m=await import(document.querySelector('script[type="module"][src*="app.mjs"]').src);return m.getDiagnostics();});}
async function state(p){return p.evaluate(async()=>{const c=await import('/cards/cardcore.mjs');return c.deserialize(JSON.parse(localStorage.getItem('tangzhe-formal-card-save')).game);});}
async function load(p,name){await p.goto('http://127.0.0.1:8788/version.json');await p.evaluate(async text=>{localStorage.clear();const c=await import('/cards/cardcore.mjs'),{createCardSave}=await import('/cards/ui/save.mjs');const s=createCardSave({storage:localStorage,locks:navigator.locks,core:c});await s.load();const r=await s.save(c.deserialize(text));if(!r.ok)throw Error(JSON.stringify(r));},fs.readFileSync(`tests/formal/hand-fixtures/${name}.json`,'utf8'));await p.goto('http://127.0.0.1:8788/cards/ui/?v=formal-cards-candidate-7');await p.locator('#resume-continue').click();}
async function shot(p,width,name){await p.screenshot({path:`evidence/hand-${engine}/${width}-${name}.png`});}
async function choose(p,uid){const before=await state(p);await p.locator('#hand-count').click();await p.locator(`[data-card="${uid}"]`).scrollIntoViewIfNeeded();await p.locator(`[data-card="${uid}"]`).click();assert.equal((await diag(p)).handExpanded,false);assert.equal((await diag(p)).revision,before.revision,'select must not commit');assert.equal((await state(p)).players[0].mana,before.players[0].mana);}
async function committed(p,rev){await p.waitForFunction(rev=>JSON.parse(localStorage.getItem('tangzhe-formal-card-save')).meta.revision>rev,rev);assert.equal((await diag(p)).revision,rev+1);}
for(const[width,height]of[[844,390],[667,375]]){
 const ctx=await browser.newContext({viewport:{width,height},hasTouch:true}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 for(let n=1;n<=10;n++){
  await load(p,'hand-'+n);await p.locator('#hand-count').click();assert.equal(await p.locator('.browse-card').count(),n);
  for(let i=0;i<n;i++){
   const card=p.locator('.browse-card').nth(i);await card.scrollIntoViewIfNeeded();await p.waitForTimeout(150);const rect=await card.boundingBox();assert.ok(rect.x>=9&&rect.x+rect.width<=width-9&&rect.y>0&&rect.y+rect.height<=height,JSON.stringify({n,i,rect,width,height}));
   assert.ok(await card.evaluate(el=>[...el.querySelectorAll('.browse-heading,.browse-body,.browse-copy,.browse-stats')].every(n=>{const r=n.getBoundingClientRect(),c=el.getBoundingClientRect();return r.top>=c.top&&r.bottom<=c.bottom&&n.scrollHeight<=n.clientHeight+1;})),'no clipped card content');
  }
  await shot(p,width,'hand-'+n);result.cases.push({width,handCount:n,fullCards:n});
 }
 await load(p,'mage-ready');let s=await state(p),a=core.legalActions(s).find(a=>a.type==='play'&&core.CARDS[s.players[0].hand.find(h=>h.uid===a.source)?.cardId]?.type==='minion');assert.ok(a);await choose(p,a.source);await shot(p,width,'minion-selected');assert.equal(await p.locator('#confirm').isVisible(),false);await p.locator('#friendly-board').click({position:{x:20,y:35}});await committed(p,s.revision);await shot(p,width,'minion-played');
 // Enemy and friendly target spells: exact legalActions source of truth.
 for(const target of['h1','h0']){await load(p,'mage-ready');s=await state(p);a=core.legalActions(s).find(a=>a.type==='play'&&a.target===target);assert.ok(a);await choose(p,a.source);await shot(p,width,'spell-target-'+target);assert.ok(await p.locator(`[data-entity="${target}"]`).evaluate(n=>n.classList.contains('valid-target')));await p.locator(`[data-entity="${target}"]`).click();await committed(p,s.revision);await p.waitForTimeout(1500);await shot(p,width,'spell-applied-'+target);}
 await load(p,'friendly-target');s=await state(p);const shield=s.players[0].hand.find(h=>h.cardId==='bkVanEx1371');assert.ok(shield);await choose(p,shield.uid);await p.locator('[data-entity="h1"]').click();assert.equal((await diag(p)).revision,s.revision);assert.equal((await diag(p)).selected.source,shield.uid);await shot(p,width,'invalid-target');const friend=s.players[0].board[0];await p.locator(`[data-entity="${friend.uid}"]`).click();await committed(p,s.revision);
 await load(p,'mage-ready');s=await state(p);const draw=s.players[0].hand.find(h=>h.cardId==='bkVanCs2023');await choose(p,draw.uid);await p.locator('#friendly-board').click({position:{x:20,y:35}});assert.equal((await diag(p)).revision,s.revision,'no-target spell cannot use placement');await shot(p,width,'no-target-confirm');await p.locator('#confirm').dblclick();await committed(p,s.revision);assert.equal((await state(p)).players[0].mana,s.players[0].mana-3);await shot(p,width,'no-target-applied');
 await load(p,'mage-ready');s=await state(p);await choose(p,s.players[0].hand[0].uid);await p.locator('#cancel').click();assert.equal((await diag(p)).selected,null);assert.equal((await diag(p)).revision,s.revision);await shot(p,width,'cancelled');await choose(p,s.players[0].hand[0].uid);await p.locator('#hand-count').click();assert.equal((await diag(p)).handExpanded,true);assert.equal((await diag(p)).selected,null);await shot(p,width,'change-card');await p.locator('.browse-card').first().click();await p.locator('#pause').click();assert.equal((await diag(p)).selected,null);assert.equal(await p.locator('#aim-arrows path').count(),0);await shot(p,width,'paused');
 await load(p,'mage-low');s=await state(p);await choose(p,s.players[0].hand.find(h=>core.CARDS[h.cardId].cost>s.players[0].mana).uid);assert.match(await p.locator('#aim-guide').innerText(),/缺法力/);assert.equal(await p.locator('#confirm').isVisible(),false);await shot(p,width,'low-mana');
 await load(p,'full');s=await state(p);const blocked=s.players[0].hand.find(h=>core.CARDS[h.cardId].type==='minion'&&core.CARDS[h.cardId].cost<=s.players[0].mana);assert.ok(blocked);await choose(p,blocked.uid);assert.match(await p.locator('#aim-guide').innerText(),/场已满/);await p.locator('#friendly-board').click({position:{x:3,y:3}});assert.equal((await diag(p)).revision,s.revision);await shot(p,width,'full-board');
 await load(p,'mage-ready');s=await state(p);await choose(p,s.players[0].hand.find(h=>h.cardId==='bkVanCs2023').uid);await p.evaluate(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('tangzhe-formal-card-save'))throw new DOMException('test quota','QuotaExceededError');return set.call(this,k,v);};});await p.locator('#confirm').click();await p.locator('#save-dialog').waitFor();assert.equal((await diag(p)).selected,null);assert.ok((await diag(p)).paused);assert.ok((await diag(p)).saveFailure);assert.equal((await state(p)).revision,s.revision);await shot(p,width,'save-failed');assert.equal(await p.locator('#aim-arrows path').count(),0);
 assert.deepEqual(errors,[]);result.cases.push({width,interactions:['minion','enemy-target','friendly-target','illegal-target','no-target-second-confirm','double-click-once','cancel','change-card','pause-clear','low-mana','full-board','save-failure-clear'],pageErrors:errors});await ctx.close();
}
fs.writeFileSync(`evidence/hand-${engine}/browser-results.json`,JSON.stringify(result,null,2));console.log('PASS',result.cases.length,'groups');await browser.close();
