import {test} from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createSaveCoordinator,KEYS} from '../../collection/host-save.mjs';import {createApprovedTrialModel} from '../../collection/domain/model.mjs';import {TRIAL_CONFIG} from '../../collection/domain/trial-config.mjs';import {canonical} from '../../collection/domain/json.mjs';
const require=createRequire(import.meta.url),R=require('../../td/tdupgrade-receipts.js'),T=require('../../td/tdcore.js'),H=require('../../td/tdhost.js'),P=require('../../td/tdcampaign-progress.js'),model=createApprovedTrialModel(TRIAL_CONFIG,{schemaVersion:1,approvedConfigCanonical:canonical(TRIAL_CONFIG),evidenceRefs:['test'],walletBridgeApproved:false});
function setup(){delete require.cache[require.resolve('../../economy.js')];const E=require('../../economy.js'),data=new Map();let fail=null,pendingRead=false,state,reply;const storage={getItem(k){if(k===KEYS.main&&pendingRead){pendingRead=false;throw Error('readback')}return data.get(k)??null},setItem(k,v){if(k===KEYS.main&&fail==='write')throw Error('write');data.set(k,v);if(k===KEYS.main&&fail==='read'){fail=null;pendingRead=true}}};const c=createSaveCoordinator({storage,economy:E,model,ownsLock:()=>true});E.installFormalCollectionProtocol(c);const seed=E.newState(1);seed.coins=50000000;seed.coinFrac=.123;seed.shops[3].open=true;seed.shops[3].lv=1;data.set(KEYS.source,JSON.stringify(seed));const i=c.inspect();state=c.initialize({approvedSourceRaw:i.sourceRaw,approvedSourceEvidence:i.sourceEvidence,now:1}).state;const make=()=>H.create({state:()=>state,blocked:()=>false,balance:()=>state.coins,send:r=>reply=r,changed(){},close(){},reconcile:()=>{if(c.failed==='COMMIT_UNCERTAIN'){const r=c.reconcile();if(r.ok)state=r.state;return r}return {ok:!c.failed}},transact:(apply,price)=>E.transact(state,{apply,price,save:s=>c.commit(s)})});let host=make();host.msg({td:'hello',protocol:3,ruleset:P.RULESET_ID});return {E,c,data,get state(){return state},fail:x=>fail=x,send(d){host.msg({td:'buy',ruleset:P.RULESET_ID,...d});return reply},reload(){state=c.adopt().state;host=make();host.msg({td:'hello',protocol:3,ruleset:P.RULESET_ID})}}}
test('missing receipt extension remains valid and does not invent historical receipts',()=>{const f=setup();assert.equal(f.state.tdUpgradeReceipts,undefined);assert.deepEqual(f.E.checkSave(f.state),[]);assert.deepEqual(R.check(undefined,f.state.td),[])});
test('one atomic debit+level+receipt; full host reload replay and original result',()=>{const f=setup(),r=f.send({requestId:'first',id:'bbq'});assert(r.ok);assert.equal(f.state.coins,49000000);assert.equal(f.state.coinFrac,.123);assert.equal(f.state.tdUpgradeReceipts.receipts.length,1);f.reload();assert(f.send({requestId:'first',id:'bbq'}).dup);assert(f.send({requestId:'second',id:'bbq'}).ok);const replay=f.send({requestId:'first',id:'bbq'});assert(replay.dup);assert.equal(replay.purchase.toLevel,1);assert.equal(f.state.td.lv.bbq,2);assert.equal(f.state.coins,47100000)});
test('same id different payload, ruleset or extra fields rejected without debit',()=>{const f=setup();f.send({requestId:'one',id:'bbq'});const before=JSON.stringify(f.state);for(const d of [{requestId:'one',id:'tea'},{requestId:'one',id:'bbq',ruleset:'future'},{requestId:'one',id:'bbq',price:0}])assert.equal(f.send(d).ok,false);assert.equal(JSON.stringify(f.state),before)});
for(const type of ['write','read'])test(type+' failure retry preserves one receipt and one debit',()=>{const f=setup();f.fail(type);assert.equal(f.send({requestId:'recover',id:'bbq'}).ok,false);assert.equal(f.state.coins,50000000);f.fail(null);assert(f.send({requestId:'recover',id:'bbq'}).ok);f.reload();assert(f.send({requestId:'recover',id:'bbq'}).dup);assert.equal(f.state.coins,49000000);assert.equal(f.state.tdUpgradeReceipts.receipts.length,1)});
test('ordinary save cannot drop, alter or reorder persisted receipts',()=>{const f=setup();f.send({requestId:'one',id:'bbq'});f.send({requestId:'two',id:'bbq'});for(const edit of [s=>delete s.tdUpgradeReceipts,s=>s.tdUpgradeReceipts.receipts.reverse(),s=>s.tdUpgradeReceipts.receipts[0].requestId='changed']){const s=structuredClone(f.state);edit(s);assert.equal(f.c.commit(s).code,'TD_UPGRADE_RECEIPTS_IMMUTABLE')}});
for(const mutation of [v=>v.schemaVersion=999,v=>v.receipts.push({...v.receipts[0]}),v=>v.receipts[0].cost=1,v=>v.receipts[0].toLevel=99,v=>v.scope='preview'])test('invalid/future receipt ledger protects original main',()=>{const f=setup();f.send({requestId:'one',id:'bbq'});const s=structuredClone(f.state);mutation(s.tdUpgradeReceipts);assert(f.E.checkSave(s).includes('tdUpgradeReceipts.invalid'));assert.equal(f.c.parse(JSON.stringify(s)).ok,false);assert.equal(f.c.commit(s).ok,false)});

test('present null is invalid; old missing field remains valid',()=>{const f=setup(),s=structuredClone(f.state);s.tdUpgradeReceipts=null;assert(f.E.checkSave(s).includes('tdUpgradeReceipts.invalid'));assert.equal(f.c.parse(JSON.stringify(s)).ok,false)});

test("invalid or future receipt extension never falls back to valid old backup",()=>{for(const value of [null,{schemaVersion:999}]){const f=setup(),s=structuredClone(f.state);s.tdUpgradeReceipts=value;const loaded=f.E.loadSave(JSON.stringify(s),JSON.stringify(f.state),1);assert(loaded.blocked);assert.notEqual(loaded.source,"bak");assert.deepEqual(loaded.raw,s)}});
