/** Sanitized display data from frozen v10a. Runtime policy comes exclusively from the parent. */
export const DISPLAY_CARDS = Object.freeze([
  {
    "cardId": "bkVanEx1400",
    "name": "后厨大扫场",
    "classId": "warrior",
    "type": "spell",
    "cost": 1,
    "text": "对所有随从造成1点伤害。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_EX1_400_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2106",
    "name": "红柄炭火夹",
    "classId": "warrior",
    "type": "weapon",
    "cost": 2,
    "text": "无特殊效果。",
    "attack": 3,
    "health": null,
    "durability": 2,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_106_original_v1.webp"
  },
  {
    "cardId": "bkVanNew1011",
    "name": "街口快送员",
    "classId": "warrior",
    "type": "minion",
    "cost": 4,
    "text": "冲锋",
    "attack": 4,
    "health": 3,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_NEW1_011_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2112",
    "name": "加长铁板铲",
    "classId": "warrior",
    "type": "weapon",
    "cost": 5,
    "text": "无特殊效果。",
    "attack": 5,
    "health": null,
    "durability": 2,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_112_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2025",
    "name": "书架震页",
    "classId": "mage",
    "type": "spell",
    "cost": 2,
    "text": "对所有敌方随从造成1点伤害。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_CS2_025_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2023",
    "name": "夜读笔记",
    "classId": "mage",
    "type": "spell",
    "cost": 3,
    "text": "抽2张牌。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_023_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2029",
    "name": "落款热印",
    "classId": "mage",
    "type": "spell",
    "cost": 4,
    "text": "造成6点伤害。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_029_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2032",
    "name": "闭馆热浪",
    "classId": "mage",
    "type": "spell",
    "cost": 7,
    "text": "对所有敌方随从造成4点伤害。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "epic",
    "art": "./assets/original/VAN_CS2_032_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2091",
    "name": "黄铜搅拌匙",
    "classId": "paladin",
    "type": "weapon",
    "cost": 1,
    "text": "无特殊效果。",
    "attack": 1,
    "health": null,
    "durability": 4,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_091_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2089",
    "name": "温杯小憩",
    "classId": "paladin",
    "type": "spell",
    "cost": 2,
    "text": "恢复6点生命值。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_089_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2093",
    "name": "满场送茶",
    "classId": "paladin",
    "type": "spell",
    "cost": 4,
    "text": "对所有敌人造成2点伤害。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_CS2_093_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2065",
    "name": "墨契门卫",
    "classId": "warlock",
    "type": "minion",
    "cost": 1,
    "text": "嘲讽",
    "attack": 1,
    "health": 3,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_065_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2062",
    "name": "整店熏墨",
    "classId": "warlock",
    "type": "spell",
    "cost": 4,
    "text": "对所有角色造成3点伤害。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "epic",
    "art": "./assets/original/VAN_CS2_062_original_v1.webp"
  },
  {
    "cardId": "bkVanCs1042",
    "name": "门口挡风板",
    "classId": "neutral",
    "type": "minion",
    "cost": 1,
    "text": "嘲讽",
    "attack": 1,
    "health": 2,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS1_042_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2168",
    "name": "折页搬箱客",
    "classId": "neutral",
    "type": "minion",
    "cost": 1,
    "text": "无特殊效果。",
    "attack": 2,
    "health": 1,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_168_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2171",
    "name": "巷口卷尾犬",
    "classId": "neutral",
    "type": "minion",
    "cost": 1,
    "text": "冲锋",
    "attack": 1,
    "health": 1,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_171_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2172",
    "name": "长腿杏斑猫",
    "classId": "neutral",
    "type": "minion",
    "cost": 2,
    "text": "无特殊效果。",
    "attack": 3,
    "health": 2,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_172_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2173",
    "name": "折页急送客",
    "classId": "neutral",
    "type": "minion",
    "cost": 2,
    "text": "冲锋",
    "attack": 2,
    "health": 1,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_173_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2121",
    "name": "雨棚看守",
    "classId": "neutral",
    "type": "minion",
    "cost": 2,
    "text": "嘲讽",
    "attack": 2,
    "health": 2,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_121_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2142",
    "name": "增幅唱针匠",
    "classId": "neutral",
    "type": "minion",
    "cost": 2,
    "text": "法术伤害+1",
    "attack": 2,
    "health": 2,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_CS2_142_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2120",
    "name": "河岸圆鼻獾",
    "classId": "neutral",
    "type": "minion",
    "cost": 2,
    "text": "无特殊效果。",
    "attack": 2,
    "health": 3,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_120_original_v1.webp"
  },
  {
    "cardId": "bkVanEx1582",
    "name": "夜校描线师",
    "classId": "neutral",
    "type": "minion",
    "cost": 3,
    "text": "法术伤害+1",
    "attack": 1,
    "health": 4,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_EX1_582_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2125",
    "name": "书巷厚掌熊",
    "classId": "neutral",
    "type": "minion",
    "cost": 3,
    "text": "嘲讽",
    "attack": 3,
    "health": 3,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_125_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2118",
    "name": "薄脆炭雕",
    "classId": "neutral",
    "type": "minion",
    "cost": 3,
    "text": "无特殊效果。",
    "attack": 5,
    "health": 1,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_118_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2127",
    "name": "门廊蓬尾狸",
    "classId": "neutral",
    "type": "minion",
    "cost": 3,
    "text": "嘲讽",
    "attack": 1,
    "health": 4,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_127_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2124",
    "name": "单轮赶集人",
    "classId": "neutral",
    "type": "minion",
    "cost": 3,
    "text": "冲锋",
    "attack": 3,
    "health": 1,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_124_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2182",
    "name": "棉被巡游偶",
    "classId": "neutral",
    "type": "minion",
    "cost": 4,
    "text": "无特殊效果。",
    "attack": 4,
    "health": 5,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_182_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2119",
    "name": "窄巷厚壳蜗",
    "classId": "neutral",
    "type": "minion",
    "cost": 4,
    "text": "无特殊效果。",
    "attack": 2,
    "health": 7,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_119_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2197",
    "name": "墨线调音客",
    "classId": "neutral",
    "type": "minion",
    "cost": 4,
    "text": "法术伤害+1",
    "attack": 4,
    "health": 4,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_CS2_197_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2179",
    "name": "折桌守门人",
    "classId": "neutral",
    "type": "minion",
    "cost": 4,
    "text": "嘲讽",
    "attack": 3,
    "health": 5,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_179_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2131",
    "name": "邮袋滑行员",
    "classId": "neutral",
    "type": "minion",
    "cost": 4,
    "text": "冲锋",
    "attack": 2,
    "health": 5,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_CS2_131_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2187",
    "name": "摊街拦车员",
    "classId": "neutral",
    "type": "minion",
    "cost": 5,
    "text": "嘲讽",
    "attack": 5,
    "health": 4,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_187_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2155",
    "name": "街区声纹导师",
    "classId": "neutral",
    "type": "minion",
    "cost": 6,
    "text": "法术伤害+1",
    "attack": 4,
    "health": 7,
    "durability": null,
    "displayRarity": "epic",
    "art": "./assets/original/VAN_CS2_155_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2200",
    "name": "旧木搬运偶",
    "classId": "neutral",
    "type": "minion",
    "cost": 6,
    "text": "无特殊效果。",
    "attack": 6,
    "health": 7,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_200_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2162",
    "name": "展场压阵人",
    "classId": "neutral",
    "type": "minion",
    "cost": 6,
    "text": "嘲讽",
    "attack": 6,
    "health": 5,
    "durability": null,
    "displayRarity": "common",
    "art": "./assets/original/VAN_CS2_162_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2213",
    "name": "坡道弹板手",
    "classId": "neutral",
    "type": "minion",
    "cost": 6,
    "text": "冲锋",
    "attack": 5,
    "health": 2,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_CS2_213_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2201",
    "name": "夜巷巨角鹿",
    "classId": "neutral",
    "type": "minion",
    "cost": 7,
    "text": "无特殊效果。",
    "attack": 9,
    "health": 5,
    "durability": null,
    "displayRarity": "legendary",
    "art": "./assets/original/VAN_CS2_201_original_v1.webp"
  },
  {
    "cardId": "bkVanCs2186",
    "name": "压纸石像",
    "classId": "neutral",
    "type": "minion",
    "cost": 7,
    "text": "无特殊效果。",
    "attack": 7,
    "health": 7,
    "durability": null,
    "displayRarity": "legendary",
    "art": "./assets/original/VAN_CS2_186_original_v1.webp"
  },
  {
    "cardId": "bkVanEx1371",
    "name": "珍珠护套",
    "classId": "paladin",
    "type": "spell",
    "cost": 1,
    "text": "使一个随从获得圣盾。",
    "attack": null,
    "health": null,
    "durability": null,
    "displayRarity": "rare",
    "art": "./assets/original/VAN_EX1_371_original_v1.png"
  }
]);
