// Actual canvas/browser recordings. Each context has a disposable local save.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import fs from 'node:fs';import assert from 'node:assert/strict';
const out=new URL(process.env.PET_TEST_OUTPUT||'./spatial-output/',import.meta.url);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),results=[];
const cases=[...['cat','alpaca','red_panda','robot','panda_cub','rabbit','dog'].map(species=>({species,path:'/preview/',record:true})),...['cat','alpaca'].map(species=>({species,path:'/preview/pet/game/',record:false}))];
for(const test of cases.filter(t=>!process.env.PET_TEST_SPECIES||process.env.PET_TEST_SPECIES.split(',').includes(t.species))){const tag=test.species+(test.record?'':'-standalone'),c=await browser.newContext({viewport:{width:Number(process.env.PET_TEST_WIDTH)||393,height:852},deviceScaleFactor:1,isMobile:true,hasTouch:true,...(test.record?{recordVideo:{dir:out.pathname,size:{width:393,height:852}}}:{})});await c.addInitScript(()=>{let t;Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}})});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 async function boot(){await p.waitForFunction(()=>window.__tzz&&Object.keys(PetGame.SPECIES).every(s=>PetGame.speciesReady(s)));await p.evaluate(async()=>{for(let i=0;i<4;i++){if(__tzz.modalOpen())__tzz.closeModal();await new Promise(r=>setTimeout(r,50))}__tzz.setTab('home');__tzz.homeAct('homeWho','c77');__tzz.homeAct('homeSub','room');__tzz.renderTab();__tzz.pets.draw()})}
 await p.goto('http://127.0.0.1:8765'+test.path);await boot();await p.evaluate(species=>{const E=__tzz.E,s=E.newState(Date.now()),manifestOf=id=>id==='dog'?__tzz.pet.M:PetGame.assetOf(id).manifest;for(const ceo of E.CEOS){s.ceos[ceo.id].unlocked=true;E.homeOf(s,ceo.id).lv=2;E.homeOf(s,ceo.id).placed=[]}s.coins=100000;s.muted=true;for(const id of ['dog',species==='dog'?'cat':species]){const r=PetGame.buy(s,E,'c77',Date.now(),manifestOf(id),()=>true,false,{species:id,manifestOf});if(!r.ok)throw Error(r.why)}E.buyFurniture(s,'furn_plant');E.placeItem(s,'c77','furn_plant',3,2,0,'floor');localStorage.setItem(__tzz.SAVE_KEY,JSON.stringify(s));localStorage.setItem(__tzz.BAK_KEY,JSON.stringify(s));localStorage.setItem('tangzhe-save','FORMAL-SENTINEL')},test.species);await p.reload();await boot();
 const ids=await p.evaluate(species=>{const all=__tzz.pets.view().pets;return {selected:Object.values(all).find(x=>x.species===species).uid,other:Object.values(all).find(x=>x.species!==species).uid}},test.species);await p.locator(`[data-act="petTarget"][data-arg="${ids.selected}"]`).click();await p.locator('#homeHost').evaluate(el=>el.scrollIntoView({block:'start'}));assert.equal(await p.locator('#homeActor .ha-ava').isVisible(),false);await p.waitForFunction(()=>__tzz.pet.view?.artMode==='atlas');
 const before=await p.evaluate(({selected,other})=>({other:JSON.stringify(__tzz.pets.view().pets[other].eng),coins:__tzz.state.coins,origin:{x:__tzz.pets.world(selected).dog.x,y:__tzz.pets.world(selected).dog.y},affinity:__tzz.pets.world(selected).dog.affinity}),ids);
 assert.equal(await p.locator('#petInteraction .pet-bar button').count(),3);await p.locator('#petInteraction [data-act="homePetBall"]').click();let final=null,samples=[],savedPhase=new Set();
 for(let n=0;n<2250;n++){
  const sample=await p.evaluate(({selected,other})=>{const w=__tzz.pets.step(selected,.04);__tzz.pets.draw();return {t:w.t,x:w.dog.x,y:w.dog.y,z:w.dog.z,clip:w.dog.anim.name,phase:w.game?.phase||null,index:w.game?.index,done:w.species?w.spatialStats.completed>=1:w.stats.fetches>=1,water:w.spatialStats?.waterBursts||0,fx:w.spatialFx?.length||0,stats:w.spatialStats||w.stats,collision:!PetEngine.bodyFree(w,w.dog.x,w.dog.y,w.dog.dir,1e-6),other:JSON.stringify(__tzz.pets.view().pets[other].eng)}},ids);
  assert(!sample.collision,tag+' collision');if(n%5===0)assert(await p.evaluate(()=>{const a=document.querySelector('#homeHost').getBoundingClientRect();return [...document.querySelectorAll('.pet-spatial-caption:not([hidden]),.pet-dog')].every(el=>{const b=el.getBoundingClientRect();return b.top>=a.bottom||b.bottom<=a.top||b.left>=a.right||b.right<=a.left})}),tag+' pet or caption overlaps portrait dock');assert.equal(sample.other,before.other,tag+' changed untargeted companion');delete sample.other;if(n%5===0)samples.push(sample);
  const capture=sample.water>0&&sample.fx?'water':sample.phase==='action'?'action-'+sample.index:sample.phase==='return'?'return':null;if(capture&&!savedPhase.has(capture)){await p.screenshot({path:new URL(tag+'-'+capture+'.png',out).pathname});savedPhase.add(capture)}
  if(sample.done){final=sample;break}if(test.record&&process.env.PET_TEST_REALTIME!=='0')await p.waitForTimeout(40);
 }
 assert(final,tag+' did not complete');if(test.species!=='dog')assert(Math.hypot(final.x-before.origin.x,final.y-before.origin.y)<.03);if(test.species==='alpaca')assert(final.water>=3);if(test.species==='rabbit')assert(samples.some(s=>s.z>.1));assert(new Set(samples.map(s=>s.x.toFixed(1)+','+s.y.toFixed(1))).size>12);assert.equal(await p.evaluate(()=>__tzz.state.coins),before.coins);await p.screenshot({path:new URL(tag+'-complete.png',out).pathname});
 // Repeated play requests return once; call and pet can interrupt without stale props.
 if(test.species!=='dog'){await p.locator('#petInteraction [data-act="homePetBall"]').click();await p.evaluate(id=>__tzz.pets.step(id,.4),ids.selected);for(let n=0;n<3;n++)await p.locator('#petInteraction [data-act="homePetBall"]').click();assert.equal(await p.evaluate(id=>__tzz.pets.world(id).game.phase,ids.selected),'return');await p.locator('#petInteraction [data-act="homePetCall"]').click();assert.equal(await p.evaluate(id=>__tzz.pets.world(id).game,ids.selected),null);const callFrom=await p.evaluate(id=>{const d=__tzz.pets.world(id).dog;return {x:d.x,y:d.y}},ids.selected);for(let n=0;n<900;n++){const moving=await p.evaluate(id=>{const w=__tzz.pets.step(id,.04);__tzz.pets.draw();return !!w.intent},ids.selected);if(!moving)break;if(test.record&&process.env.PET_TEST_REALTIME!=='0')await p.waitForTimeout(40);}const called=await p.evaluate(({id,from})=>{const w=__tzz.pets.world(id);return {travel:Math.hypot(w.dog.x-from.x,w.dog.y-from.y),remaining:Math.hypot(w.dog.x-w.front.x,w.dog.y-(w.front.y-.65))}},{id:ids.selected,from:callFrom});assert(called.travel>.3);assert(called.remaining<.03);await p.locator('#petInteraction [data-act="homePetPat"]').click();assert.equal(await p.evaluate(id=>__tzz.pets.world(id).dog.anim.name,ids.selected),'petted');await p.evaluate(id=>{__tzz.pets.step(id,.3);__tzz.pets.draw()},ids.selected);await p.screenshot({path:new URL(tag+'-petted.png',out).pathname});if(test.record)await p.waitForTimeout(600);}
 await p.evaluate(()=>__tzz.pets.persist());const growth=await p.evaluate(id=>__tzz.pets.world(id).dog.affinity,ids.selected);await p.reload();await boot();assert.equal(await p.evaluate(id=>__tzz.pets.world(id).dog.affinity,ids.selected),growth);
 // Portrait docking must preserve the host's floor walk and decor-mode avatar.
 const floorBox=await p.locator('#roomFloor').boundingBox();await p.locator('#roomFloor').click({position:{x:floorBox.width*.88,y:floorBox.height*.12}});assert(await p.evaluate(()=>__tzz.homeActor.c77.tx!==null));const goal=await p.evaluate(()=>({x:__tzz.homeActor.c77.tx,y:__tzz.homeActor.c77.ty}));await p.evaluate(()=>__tzz.pets.manual(false));await p.waitForFunction(()=>__tzz.homeActor.c77.tx===null);const host=await p.evaluate(()=>({x:__tzz.homeActor.c77.x,y:__tzz.homeActor.c77.y}));assert(Math.hypot(host.x-goal.x,host.y-goal.y)<.05);await p.evaluate(()=>__tzz.pets.manual(true));await p.locator('[data-act="homeMode"][data-arg="decor"]').click();await p.waitForFunction(()=>!document.querySelector('#homeHost'));assert(await p.locator('#homeActor .ha-ava').isVisible());await p.locator('[data-act="homeMode"][data-arg="live"]').click();await p.locator('#homeHost').waitFor();assert.equal(await p.locator('#homeActor .ha-ava').isVisible(),false);
assert.equal(await p.evaluate(()=>localStorage.getItem('tangzhe-save')),'FORMAL-SENTINEL');assert.deepEqual(errors,[]);
 const video=p.video();await c.close();if(video)await video.saveAs(new URL(tag+'.webm',out).pathname);
 const row={...test,status:'pass',stats:final.stats,elapsed:final.t,samples:samples.length,otherPetUnchanged:true,coinsUnchanged:true,saveReload:true,errors,video:test.record?tag+'.webm':null};results.push(row);fs.writeFileSync(new URL('results.json',out),JSON.stringify(results,null,2));fs.writeFileSync(new URL(tag+'-samples.json',out),JSON.stringify(samples,null,2));console.log(JSON.stringify(row));
}await browser.close();
