// Two targeted normal-host capacity UI flows; not a repeat of the accepted UI matrix.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import fs from 'node:fs';import assert from 'node:assert/strict';
const out=new URL(process.env.PET_TEST_OUTPUT||'./capacity-output/',import.meta.url);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),results=[];
for(const entry of ['/preview/','/preview/pet/game/']){
 const c=await browser.newContext({viewport:{width:375,height:667},deviceScaleFactor:2,isMobile:true,hasTouch:true});
 await c.route('http://preview-candidate.invalid/**',async route=>{const root=new URL('../../../',import.meta.url),u=new URL(route.request().url()),file=new URL('.'+(u.pathname.endsWith('/')?u.pathname+'index.html':u.pathname),root);assert(file.pathname.startsWith(root.pathname));await route.fulfill(fs.existsSync(file)?{path:file.pathname}:{status:404,body:'Not found'});});
 await c.addInitScript(()=>{let t;Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}})});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 async function boot(){await p.waitForFunction(()=>window.__tzz&&Object.keys(PetGame.SPECIES).every(s=>PetGame.speciesReady(s)));await p.evaluate(async()=>{for(let i=0;i<4;i++){if(__tzz.modalOpen())__tzz.closeModal();await new Promise(r=>setTimeout(r,60));}__tzz.setTab('home');__tzz.homeAct('homeWho','c77');__tzz.homeAct('homeSub','room');__tzz.renderTab();__tzz.pets.draw()})}
 const draw=()=>p.evaluate(()=>{__tzz.renderTab();__tzz.pets.draw()});const choose=id=>p.locator(`[data-act="petSelect"][data-arg="${id}"]`).click();
 await p.goto('http://preview-candidate.invalid'+entry);await boot();
 await p.evaluate(()=>{const E=__tzz.E,s=E.newState(Date.now());for(const ceo of E.CEOS){s.ceos[ceo.id].unlocked=true;E.homeOf(s,ceo.id).placed=[]}s.coins=1000000;s.muted=true;
 const manifestOf=id=>id==='dog'?__tzz.pet.M:PetGame.assetOf(id).manifest;
 for(const [species,home] of [['dog','c77'],['cat','pearl'],['rabbit',null]]){const r=PetGame.buy(s,E,home,Date.now(),manifestOf(species),()=>true,false,{species,manifestOf});if(!r.ok)throw Error(r.why)}
 const t=E.homeTier(E.homeOf(s,'c77').lv);for(let y=0;y<t.rows;y++)for(let x=0;x<t.cols;x++){E.buyFurniture(s,'furn_plant');E.placeItem(s,'c77','furn_plant',x,y,0,'floor')}
 localStorage.setItem(__tzz.SAVE_KEY,JSON.stringify(s));localStorage.setItem(__tzz.BAK_KEY,JSON.stringify(s));localStorage.setItem('tangzhe-save','FORMAL-SENTINEL');});
 await p.reload();await boot();await p.locator('#petEntry').click();await choose('cat');assert(await p.locator('[data-act="petPlace"]').isDisabled());
 const before=await p.evaluate(()=>JSON.stringify(__tzz.state));await choose('red_panda');await p.locator('[data-act="homePetBuy"]').click();assert.equal(await p.locator('#petBuyNoRoom').count(),1);assert.equal(await p.locator('#petBuyReplace').count(),0);assert.equal(await p.locator('#petBuyStandby').count(),1);await p.screenshot({path:new URL(entry.includes('/game/')?'blocked-standalone.png':'blocked-main.png',out).pathname});await p.locator('#mNo').click();assert.equal(await p.evaluate(()=>JSON.stringify(__tzz.state)),before);
 await p.evaluate(()=>{const E=__tzz.E;for(const x of [...E.homeOf(__tzz.state,'c77').placed])if(x.y===0)E.storeItem(__tzz.state,'c77',x.uid)});await draw();await choose('cat');assert(await p.locator('[data-act="petPlace"]').isEnabled());const coins=await p.evaluate(()=>__tzz.state.coins);await p.locator('[data-act="petPlace"]').click();await draw();assert.equal(await p.evaluate(()=>__tzz.pets.view().rooms.c77.length),2);
 await choose('rabbit');assert(await p.locator('[data-act="petPlace"]').isEnabled());await p.locator('[data-act="petPlace"]').click();const cat=await p.evaluate(()=>__tzz.state.pets.list.find(p=>p.species==='cat').uid);await p.locator(`[data-replace-uid="${cat}"]`).click();await draw();assert.equal(await p.evaluate(()=>__tzz.state.pets.list.find(p=>p.species==='cat').room),null);assert.equal(await p.evaluate(()=>__tzz.state.pets.list.find(p=>p.species==='rabbit').room),'c77');assert.equal(await p.evaluate(()=>__tzz.state.coins),coins);assert.equal(await p.evaluate(()=>localStorage.getItem('tangzhe-save')),'FORMAL-SENTINEL');assert.deepEqual(errors,[]);
 results.push({entry,width:375,status:'pass',fullFloorBlocksMove:true,blockedPurchaseOffersStandby:true,cancelUnchanged:true,furnitureRemovalEnablesSecondResident:true,fullRoomReplacementWorks:true,coinsAndFormalSavePreserved:true,errors});fs.writeFileSync(new URL('results.json',out),JSON.stringify(results,null,2));console.log(JSON.stringify(results.at(-1)));await c.unrouteAll({behavior:'wait'});await c.close();
}await browser.close();
