'use strict';
const assert=require('node:assert/strict'),E=require('../../economy.js'),PC=require('../companions.js'),Geo=require('../engine.js');
const species=Object.keys(PC.CONFIG),stamp=1790000000000,make=(id,items=[])=>PC.createWorld({manifest:require('../art/'+id+'/manifest.json'),catalog:E.FURNITURE,room:{cols:8,rows:7,front:{x:4,y:6.7},bed:null,bowl:null,items},start:{x:6,y:5.3},seed:1337});
const walk=(w,until,max=90)=>{let n=0,positions=new Set(),maxHop=0;while(!until()&&n++<max*60){PC.update(w,1/60);assert(Geo.bodyFree(w,w.dog.x,w.dog.y,w.dog.dir,1e-6),w.species+' body collision');positions.add(w.dog.x.toFixed(2)+','+w.dog.y.toFixed(2));maxHop=Math.max(maxHop,w.dog.z||0);}assert(until(),w.species+' timeout '+JSON.stringify(PC.snapshot(w)));return {positions:positions.size,maxHop};};
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name)}
for(const id of species)for(const obstacles of [false,true])test(id+' complete spatial game'+(obstacles?' with furniture':''),()=>{
 const w=make(id,obstacles?[{uid:'plant',fid:'furn_plant',x:3,y:2},{uid:'table',fid:'furn_table',x:3,y:4}]:[]),before=w.dog.affinity,origin={x:w.dog.x,y:w.dog.y};assert(PC.throwBall(w).ok);assert.equal(w.game.stops.length,PC.GAMES[id].legs);const motion=walk(w,()=>w.spatialStats.completed===1);assert(motion.positions>60);assert(w.spatialStats.returnDistance<.01);assert(Math.hypot(w.dog.x-origin.x,w.dog.y-origin.y)<.01);assert.equal(w.dog.affinity,before+1);assert(!w.toy&&!w.game);if(id==='alpaca')assert(w.spatialStats.waterBursts>=3);if(id==='robot')assert.equal(w.spatialStats.scans,3);if(id==='rabbit')assert(motion.maxHop>.1);
});
for(const id of species)test(id+' repeated clicks return once, then ordered restart; call/pet/layout/pause/restore clean transient state',()=>{
 const w=make(id);assert(PC.throwBall(w).ok);PC.step(w,.8);const affinity=w.dog.affinity;assert(PC.throwBall(w).returning);for(let i=0;i<4;i++)assert(PC.throwBall(w).returning);walk(w,()=>!w.game);assert.equal(w.spatialStats.cancelled,1);assert.equal(w.dog.affinity,affinity);assert(PC.throwBall(w).ok);PC.step(w,.3);assert(PC.call(w).ok);assert(!w.game&&!w.toy&&!w.spatialFx.length);
 assert(PC.throwBall(w).ok);PC.step(w,.3);assert(PC.pet(w).ok);assert(!w.game&&!w.toy);assert(PC.throwBall(w).ok);PC.step(w,.2);const save=PC.serialize(w,stamp),fresh=make(id);assert(PC.restore(fresh,save,stamp+1000).ok);assert.equal(fresh.dog.affinity,w.dog.affinity);assert(!fresh.game&&!fresh.intent&&!fresh.toy&&!fresh.spatialFx.length);
 PC.setRearrange(w,true);assert(!w.game&&!w.intent&&!w.toy&&!w.spatialFx.length);assert(!PC.throwBall(w).ok);PC.setRearrange(w,false);assert(PC.throwBall(w).ok);PC.step(w,.2);PC.setLayout(w,{cols:8,rows:7,front:w.front,items:[{uid:'plant',fid:'furn_plant',x:3,y:2}]});walk(w,()=>!w.game);assert(Geo.bodyFree(w,w.dog.x,w.dog.y,w.dog.dir,1e-6));
});
for(const id of species)test(id+' call walks to the player; pet responds with its own clip and heart',()=>{const w=make(id),from={x:w.dog.x,y:w.dog.y};assert(PC.call(w).ok);walk(w,()=>!w.intent);assert(Math.hypot(w.dog.x-from.x,w.dog.y-from.y)>.8);assert(Math.hypot(w.dog.x-w.front.x,w.dog.y-(w.front.y-.65))<.03);assert(PC.pet(w).ok);assert.equal(w.dog.anim.name,'petted');assert.equal(w.dog.label,w.profile.pet);assert(w.fx.some(f=>f.type==='heart'));});
test('no meaningful route rejects instead of playing a fake in-place loop',()=>{for(const id of species){const w=make(id);w.cols=1;w.rows=.65;w.front={x:.5,y:.35};Geo.setLayout(w,{cols:1,rows:.65,front:w.front,items:[]});const before=w.dog.affinity;assert(!PC.throwBall(w).ok);assert(!w.game);assert.equal(w.dog.affinity,before)}});
console.log(n+' spatial behavior cases passed using real manifests; no economic reward or dog engine edits');
