// Normal-host local checkout simulation. No prototype flag or public deployment.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import fs from 'node:fs';import assert from 'node:assert/strict';
const out=new URL(process.env.PET_TEST_OUTPUT||'./pet-portal-output/',import.meta.url);fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),results=[];
for(const test of [{width:320,height:667,path:'/preview/'},{width:375,height:667,path:'/preview/'},{width:393,height:852,path:'/preview/'},{width:320,height:667,path:'/preview/pet/game/'},{width:375,height:667,path:'/preview/pet/game/'},{width:393,height:852,path:'/preview/pet/game/'}]){
 const c=await b.newContext({viewport:{width:test.width,height:test.height},deviceScaleFactor:2,isMobile:true,hasTouch:true});
 await c.route('http://preview-candidate.invalid/**',async route=>{const root=new URL('../../../',import.meta.url),url=new URL(route.request().url()),name=url.pathname.endsWith('/')?url.pathname+'index.html':url.pathname,file=new URL('.'+name,root);assert(file.pathname.startsWith(root.pathname));await route.fulfill(fs.existsSync(file)?{path:file.pathname}:{status:404,body:'Not found'});});
 await c.addInitScript(()=>{let t,pg;window.__petCalls=[];window.__petResults=[];Object.defineProperty(window,'__tzz',{get:()=>t,set:v=>{t=v;v?.pets?.manual(true)}});Object.defineProperty(window,'PetGame',{get:()=>pg,set:v=>{pg=v;const create=v.createRuntime;v.createRuntime=opt=>{const rt=create(opt);for(const key of ['call','pet','throwBall']){const fn=rt[key];rt[key]=(...args)=>{window.__petCalls.push([opt.uid,key]);const result=fn(...args);window.__petResults.push(result);return result}}return rt}}});});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const tag=test.width+(test.path.includes('/game/')?'-standalone':'');
 async function boot(){await p.waitForFunction(()=>window.__tzz&&Object.keys(PetGame.SPECIES).every(s=>PetGame.speciesReady(s)));await p.evaluate(async()=>{for(let i=0;i<4;i++){if(__tzz.modalOpen())__tzz.closeModal();await new Promise(r=>setTimeout(r,60));}__tzz.setTab('home');__tzz.homeAct('homeWho','c77');__tzz.homeAct('homeSub','room');__tzz.renderTab();__tzz.pets.draw()});}
 async function draw(){await p.evaluate(()=>{__tzz.renderTab();__tzz.pets.draw()});}
 async function manage(){await p.locator('#petEntry').click();assert.equal(await p.locator('#petPanel').count(),1);assert.equal(await p.locator('#petPanel .pet-bar,#petInteraction').count(),0);}
 async function choose(species){await p.locator(`[data-act="petSelect"][data-arg="${species}"]`).click();assert.equal(await p.locator('.pet-selected').getAttribute('data-species'),species);}
 async function close(){await p.locator('[data-act="petClose"]').click();await p.evaluate(()=>__tzz.pets.draw());assert.equal(await p.locator('#petPanel').count(),0);}
 async function visible(){await p.evaluate(()=>__tzz.pets.draw());const info=await p.evaluate(()=>{const panel=document.querySelector('#panel').getBoundingClientRect(),buttons=[...document.querySelectorAll('#petInteraction .pet-bar button')].map(e=>{const r=e.getBoundingClientRect();return [r.left,r.top,r.right,r.bottom]}),points=(__tzz.pets.view().rooms.c77||[]).map(id=>__tzz.pets.px(id));return {panel:[panel.left,panel.top,panel.right,panel.bottom],buttons,points,wide:document.documentElement.scrollWidth>innerWidth}});assert.equal(info.buttons.length,3);for(const [l,t,r,bt] of info.buttons)assert(l>=info.panel[0]&&r<=info.panel[2]&&t>=info.panel[1]&&bt<=info.panel[3],JSON.stringify(info));for(const q of info.points)assert(q&&q.x>info.panel[0]&&q.x<info.panel[2]&&q.y>info.panel[1]&&q.y<info.panel[3],JSON.stringify(info));assert(!info.wide);}
 await p.goto('http://preview-candidate.invalid'+test.path);await boot();await p.evaluate(()=>{const E=__tzz.E,s=E.newState(Date.now());for(const ceo of E.CEOS){s.ceos[ceo.id].unlocked=true;E.homeOf(s,ceo.id).lv=2;E.homeOf(s,ceo.id).placed=[]}s.coins=50000;s.muted=true;localStorage.setItem(__tzz.SAVE_KEY,JSON.stringify(s));localStorage.setItem(__tzz.BAK_KEY,JSON.stringify(s));localStorage.setItem('tangzhe-save','FORMAL-SENTINEL')});await p.reload();await boot();assert.equal(await p.locator('#petEntry').count(),1);await manage();
 for(const [i,s] of ['dog','cat','red_panda','robot','panda_cub','alpaca','rabbit'].entries()){await choose(s);await p.locator('.pet-selected [data-act="homePetBuy"]').click();if(i>=2)await p.locator('#petBuyStandby').click();await p.evaluate(()=>{const el=document.querySelector('#pbYes');el.click();el.click()});await draw();assert.equal(await p.locator('#petPanel .pet-bar').count(),0);assert.equal(await p.evaluate(()=>__tzz.state.coins),50000-(i+1)*3000);}
 await close();const ids=await p.evaluate(()=>Object.fromEntries(__tzz.state.pets.list.map(p=>[p.species,p.uid])));
 await p.evaluate(ids=>{for(const [s,x] of [['dog',1.6],['cat',5.6]]){const w=__tzz.pets.world(ids[s]);w.dog.x=x;w.dog.y=w.rows-2.2;w.dog.z=0;}__tzz.pets.draw();window.__roomNode=document.querySelector('#room');},ids);await visible();
 for(const species of ['dog','cat']){
  const uid=ids[species],other=ids[species==='dog'?'cat':'dog'];let scroll=await p.locator('#panel').evaluate(e=>e.scrollTop);await p.locator(`[data-act="petTarget"][data-arg="${uid}"]`).click();assert.equal(await p.locator('#petInteraction .pet-bar').getAttribute('data-uid'),uid);assert.equal(await p.locator('#panel').evaluate(e=>e.scrollTop),scroll);
  for(const [act,key] of [['homePetPat','pet'],['homePetCall','call'],['homePetBall','throwBall']]){
   const before=await p.evaluate(id=>JSON.stringify(__tzz.pets.view().pets[id].eng),other);scroll=await p.locator('#panel').evaluate(e=>e.scrollTop);await p.evaluate(()=>{__petCalls.length=0;__petResults.length=0});await p.locator(`#petInteraction [data-act="${act}"]`).click();assert.deepEqual(await p.evaluate(()=>__petCalls),[[uid,key]]);assert.equal(await p.evaluate(()=>__petResults[0]?.ok),true);await p.evaluate(id=>{__tzz.pets.step(id,2);__tzz.pets.draw()},uid);assert.equal(await p.evaluate(id=>JSON.stringify(__tzz.pets.view().pets[id].eng),other),before);assert.equal(await p.locator('#panel').evaluate(e=>e.scrollTop),scroll);assert(await p.evaluate(()=>document.querySelector('#room')===__roomNode));assert.equal(await p.locator('#petPanel').count(),0);await visible();
  }
 }
 // Clicking the actual opaque dog pixels selects/interacts with that dog only.
 await p.evaluate(()=>__petCalls.length=0);const point=await p.evaluate(uid=>__tzz.pets.px(uid),ids.dog);await p.touchscreen.tap(point.x,point.y);assert.deepEqual(await p.evaluate(()=>__petCalls),[[ids.dog,'pet']]);assert.equal(await p.locator('#petInteraction .pet-bar').getAttribute('data-uid'),ids.dog);await visible();
 await p.screenshot({path:new URL(`visible-${tag}.png`,out).pathname});
 // Management has no interactions. Sending the selected target to standby chooses a resident.
 await manage();await choose('dog');await p.locator('[data-act="petStandby"]').click();await draw();await close();assert.equal(await p.locator('#petInteraction .pet-bar').getAttribute('data-uid'),ids.cat);await visible();
 await manage();await choose('rabbit');await p.locator('[data-act="petPlace"]').click();await draw();await close();assert.equal(await p.locator('#petInteraction .pet-bar').getAttribute('data-uid'),ids.rabbit);await visible();
 await manage();await choose('dog');await p.locator('[data-act="petPlace"]').click();const before=await p.evaluate(()=>JSON.stringify(__tzz.state));await p.locator('#petReplaceCancel').click();assert.equal(await p.evaluate(()=>JSON.stringify(__tzz.state)),before);await p.locator('[data-act="petPlace"]').click();await p.locator(`[data-replace-uid="${ids.rabbit}"]`).click();await draw();await p.keyboard.press('Escape');await p.evaluate(()=>__tzz.pets.draw());assert.equal(await p.locator('#petInteraction .pet-bar').getAttribute('data-uid'),ids.dog);await visible();
 await p.evaluate(()=>__tzz.pets.persist());await p.reload();await boot();assert.equal(await p.locator('#petPanel').count(),0);await p.locator('#room').evaluate(e=>e.scrollIntoView({block:'start'}));await visible();assert.equal(await p.evaluate(()=>__tzz.state.coins),29000);assert.equal(await p.evaluate(()=>localStorage.getItem('tangzhe-save')),'FORMAL-SENTINEL');assert.deepEqual(errors,[]);
 const row={...test,status:'pass',sevenPurchases:true,managementHasNoInteractions:true,oneVisibleThreeButtonGroup:true,eachButtonTargetsOnlySelectedPet:true,spriteTapSelectsOne:true,noScrollOrSceneResetOnInteraction:true,standbyTargetFallback:true,replacementCancel:true,closeEscapeReload:true,normalHostnameWithoutFlag:true,errors};results.push(row);fs.writeFileSync(new URL('results.json',out),JSON.stringify(results,null,2));console.log(JSON.stringify(row));await c.unrouteAll({behavior:'wait'});await c.close();
}await b.close();
